// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractMessage_Eth.proto

package protoc_gen_go_eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostCreateContractEndpointRequest struct {
	Stage string `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	// Solidity code of this contract; required when creating a contract. In responses, only returned with contracts initially compiled by BlockCypher.
	Solidity []string `protobuf:"bytes,2,rep,name=solidity,proto3" json:"solidity,omitempty"`
	// Parameters for either contract creation or method execution.
	Params []string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	// Named contract(s) to publish; necessary to specify when first creating a contract.
	Publish []string `protobuf:"bytes,4,rep,name=publish,proto3" json:"publish,omitempty"`
	// Private key associated with a funded Ethereum external account used to publish a contract or execute a method.
	Private string `protobuf:"bytes,5,opt,name=private,proto3" json:"private,omitempty"`
	// Maximum amount of gas to use in contract creation or method execution.
	GasLimit int32 `protobuf:"varint,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// Amount (in wei) to transfer; can be used when creating a contract or calling a method.
	Value int32 `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	// Name of contract as published.
	Name string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// Hex-encoded binary compilation of this contract.
	Bin string `protobuf:"bytes,9,opt,name=bin,proto3" json:"bin,omitempty"`
	// JSON-encoded ABI. Only returned with contracts initially compiled by BlockCypher.
	Abi *any.Any `protobuf:"bytes,10,opt,name=abi,proto3" json:"abi,omitempty"`
	// Hex-encoded address of this contract.
	Address string `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	// Timestamp when this contract was confirmed in the Ethereum blockchain.
	Created *timestamp.Timestamp `protobuf:"bytes,12,opt,name=created,proto3" json:"created,omitempty"`
	// Hex-encoded transaction hash that created this contract.
	CreationTxHash string `protobuf:"bytes,13,opt,name=creation_tx_hash,json=creationTxHash,proto3" json:"creation_tx_hash,omitempty"`
	// If this is a response from a calling a contract method, this array of results may appear if the method returns any.
	Results              []string `protobuf:"bytes,14,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCreateContractEndpointRequest) Reset()         { *m = PostCreateContractEndpointRequest{} }
func (m *PostCreateContractEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PostCreateContractEndpointRequest) ProtoMessage()    {}
func (*PostCreateContractEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d91f12413506c4d9, []int{0}
}

func (m *PostCreateContractEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCreateContractEndpointRequest.Unmarshal(m, b)
}
func (m *PostCreateContractEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCreateContractEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PostCreateContractEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCreateContractEndpointRequest.Merge(m, src)
}
func (m *PostCreateContractEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PostCreateContractEndpointRequest.Size(m)
}
func (m *PostCreateContractEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCreateContractEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostCreateContractEndpointRequest proto.InternalMessageInfo

func (m *PostCreateContractEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *PostCreateContractEndpointRequest) GetSolidity() []string {
	if m != nil {
		return m.Solidity
	}
	return nil
}

func (m *PostCreateContractEndpointRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PostCreateContractEndpointRequest) GetPublish() []string {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *PostCreateContractEndpointRequest) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *PostCreateContractEndpointRequest) GetGasLimit() int32 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *PostCreateContractEndpointRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PostCreateContractEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostCreateContractEndpointRequest) GetBin() string {
	if m != nil {
		return m.Bin
	}
	return ""
}

func (m *PostCreateContractEndpointRequest) GetAbi() *any.Any {
	if m != nil {
		return m.Abi
	}
	return nil
}

func (m *PostCreateContractEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PostCreateContractEndpointRequest) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PostCreateContractEndpointRequest) GetCreationTxHash() string {
	if m != nil {
		return m.CreationTxHash
	}
	return ""
}

func (m *PostCreateContractEndpointRequest) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

type GetContractAddressEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContractAddressEndpointRequest) Reset()         { *m = GetContractAddressEndpointRequest{} }
func (m *GetContractAddressEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetContractAddressEndpointRequest) ProtoMessage()    {}
func (*GetContractAddressEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d91f12413506c4d9, []int{1}
}

func (m *GetContractAddressEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContractAddressEndpointRequest.Unmarshal(m, b)
}
func (m *GetContractAddressEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContractAddressEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetContractAddressEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContractAddressEndpointRequest.Merge(m, src)
}
func (m *GetContractAddressEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetContractAddressEndpointRequest.Size(m)
}
func (m *GetContractAddressEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContractAddressEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContractAddressEndpointRequest proto.InternalMessageInfo

func (m *GetContractAddressEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *GetContractAddressEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PostCallContractMethodEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCallContractMethodEndpointRequest) Reset()         { *m = PostCallContractMethodEndpointRequest{} }
func (m *PostCallContractMethodEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PostCallContractMethodEndpointRequest) ProtoMessage()    {}
func (*PostCallContractMethodEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d91f12413506c4d9, []int{2}
}

func (m *PostCallContractMethodEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCallContractMethodEndpointRequest.Unmarshal(m, b)
}
func (m *PostCallContractMethodEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCallContractMethodEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PostCallContractMethodEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCallContractMethodEndpointRequest.Merge(m, src)
}
func (m *PostCallContractMethodEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PostCallContractMethodEndpointRequest.Size(m)
}
func (m *PostCallContractMethodEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCallContractMethodEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostCallContractMethodEndpointRequest proto.InternalMessageInfo

func (m *PostCallContractMethodEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *PostCallContractMethodEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PostCallContractMethodEndpointRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type ContractArray struct {
	Contract             []*Contract `protobuf:"bytes,1,rep,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContractArray) Reset()         { *m = ContractArray{} }
func (m *ContractArray) String() string { return proto.CompactTextString(m) }
func (*ContractArray) ProtoMessage()    {}
func (*ContractArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_d91f12413506c4d9, []int{3}
}

func (m *ContractArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractArray.Unmarshal(m, b)
}
func (m *ContractArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractArray.Marshal(b, m, deterministic)
}
func (m *ContractArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractArray.Merge(m, src)
}
func (m *ContractArray) XXX_Size() int {
	return xxx_messageInfo_ContractArray.Size(m)
}
func (m *ContractArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractArray.DiscardUnknown(m)
}

var xxx_messageInfo_ContractArray proto.InternalMessageInfo

func (m *ContractArray) GetContract() []*Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func init() {
	proto.RegisterType((*PostCreateContractEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PostCreateContractEndpointRequest")
	proto.RegisterType((*GetContractAddressEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.GetContractAddressEndpointRequest")
	proto.RegisterType((*PostCallContractMethodEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PostCallContractMethodEndpointRequest")
	proto.RegisterType((*ContractArray)(nil), "fairwaycorp.blockchainprotobuf.eth.ContractArray")
}

func init() { proto.RegisterFile("contractMessage_Eth.proto", fileDescriptor_d91f12413506c4d9) }

var fileDescriptor_d91f12413506c4d9 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4b, 0x6f, 0xd4, 0x30,
	0x10, 0x56, 0x9a, 0x76, 0x1f, 0x5e, 0x5a, 0x55, 0x56, 0x05, 0xee, 0x72, 0x20, 0x8d, 0x04, 0xca,
	0x81, 0x64, 0xa5, 0xc2, 0x15, 0xa1, 0xb2, 0xaa, 0xe8, 0x01, 0x24, 0x14, 0x7a, 0x81, 0xcb, 0x6a,
	0x92, 0xb8, 0x89, 0x45, 0x62, 0x07, 0x7b, 0x52, 0x9a, 0x3f, 0xc6, 0xef, 0x43, 0x71, 0x1e, 0x3c,
	0x7a, 0x00, 0x89, 0xdb, 0x7c, 0xf3, 0x8d, 0x3f, 0xcf, 0x93, 0x9c, 0xa6, 0x4a, 0xa2, 0x86, 0x14,
	0xdf, 0x73, 0x63, 0x20, 0xe7, 0xbb, 0x4b, 0x2c, 0xa2, 0x5a, 0x2b, 0x54, 0xd4, 0xbf, 0x01, 0xa1,
	0xbf, 0x41, 0x9b, 0x2a, 0x5d, 0x47, 0x49, 0xa9, 0xd2, 0x2f, 0x69, 0x01, 0x42, 0x5a, 0x32, 0x69,
	0x6e, 0x22, 0x8e, 0xc5, 0xfa, 0x34, 0x57, 0x2a, 0x2f, 0xf9, 0x66, 0x74, 0x6e, 0x40, 0xb6, 0xfd,
	0xf3, 0xf5, 0x93, 0x3f, 0x29, 0x14, 0x15, 0x37, 0x08, 0x55, 0x3d, 0x04, 0x3c, 0x4a, 0x55, 0x55,
	0x29, 0x79, 0xef, 0x63, 0xff, 0xbb, 0x4b, 0xce, 0x3e, 0x28, 0x83, 0x5b, 0xcd, 0x01, 0xf9, 0x76,
	0x48, 0xf0, 0x52, 0x66, 0xb5, 0x12, 0x12, 0x63, 0xfe, 0xb5, 0xe1, 0x06, 0xe9, 0x09, 0x39, 0x30,
	0x08, 0x39, 0x67, 0x8e, 0xe7, 0x04, 0xcb, 0xb8, 0x07, 0x74, 0x4d, 0x16, 0x46, 0x95, 0x22, 0x13,
	0xd8, 0xb2, 0x3d, 0xcf, 0x0d, 0x96, 0xf1, 0x84, 0xe9, 0x43, 0x32, 0xab, 0x41, 0x43, 0x65, 0x98,
	0x6b, 0x99, 0x01, 0x51, 0x46, 0xe6, 0x75, 0x93, 0x94, 0xc2, 0x14, 0x6c, 0xdf, 0x12, 0x23, 0xb4,
	0x8c, 0x16, 0xb7, 0x80, 0x9c, 0x1d, 0xd8, 0x5f, 0x46, 0x48, 0x1f, 0x93, 0x65, 0x0e, 0x66, 0x57,
	0x8a, 0x4a, 0x20, 0x9b, 0x79, 0x4e, 0x70, 0x10, 0x2f, 0x72, 0x30, 0xef, 0x3a, 0xdc, 0xa5, 0x76,
	0x0b, 0x65, 0xc3, 0xd9, 0xdc, 0x12, 0x3d, 0xa0, 0x94, 0xec, 0x4b, 0xa8, 0x38, 0x5b, 0x58, 0x25,
	0x6b, 0xd3, 0x63, 0xe2, 0x26, 0x42, 0xb2, 0xa5, 0x75, 0x75, 0x26, 0x7d, 0x46, 0x5c, 0x48, 0x04,
	0x23, 0x9e, 0x13, 0xac, 0xce, 0x4f, 0xa2, 0xbe, 0x89, 0xd1, 0xd4, 0xf4, 0x0b, 0xd9, 0xc6, 0x5d,
	0x40, 0x97, 0x1a, 0x64, 0x99, 0xe6, 0xc6, 0xb0, 0x55, 0x9f, 0xda, 0x00, 0xe9, 0x4b, 0x32, 0x4f,
	0x6d, 0xe7, 0x32, 0xf6, 0xc0, 0xaa, 0xac, 0xef, 0xa9, 0x5c, 0x8f, 0xa3, 0x88, 0xc7, 0x50, 0x1a,
	0x90, 0x63, 0x6b, 0x0a, 0x25, 0x77, 0x78, 0xb7, 0x2b, 0xc0, 0x14, 0xec, 0xd0, 0x0a, 0x1f, 0x8d,
	0xfe, 0xeb, 0xbb, 0x2b, 0xe8, 0x9b, 0xa2, 0xb9, 0x69, 0x4a, 0x34, 0xec, 0xa8, 0x6f, 0xd7, 0x00,
	0xfd, 0x8f, 0xe4, 0xec, 0x2d, 0xc7, 0x71, 0x60, 0x17, 0x7d, 0x3e, 0xff, 0x36, 0xb7, 0x5f, 0xca,
	0xd9, 0xfb, 0xad, 0x1c, 0x5f, 0x91, 0xa7, 0x76, 0x19, 0xa0, 0x2c, 0xb7, 0xd3, 0xae, 0x62, 0xa1,
	0xb2, 0xff, 0x14, 0xee, 0xd6, 0xa1, 0xb2, 0x42, 0xcc, 0xb5, 0xc4, 0x80, 0xfc, 0x4f, 0xe4, 0x70,
	0x2a, 0x41, 0x6b, 0x68, 0xe9, 0x15, 0x59, 0x8c, 0x57, 0xc2, 0x1c, 0xcf, 0x0d, 0x56, 0xe7, 0xcf,
	0xa3, 0xbf, 0xdf, 0x46, 0x34, 0x8a, 0xc4, 0xd3, 0xeb, 0x37, 0xaf, 0x3f, 0xbf, 0xca, 0x05, 0x16,
	0x4d, 0x12, 0xa5, 0xaa, 0xda, 0x0c, 0x1a, 0x61, 0x27, 0xb2, 0xf9, 0x29, 0x12, 0x4e, 0x17, 0x63,
	0x8d, 0x34, 0xcc, 0xb9, 0x0c, 0x73, 0x15, 0x72, 0x2c, 0x92, 0x99, 0x75, 0xbd, 0xf8, 0x11, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0xc9, 0x40, 0x07, 0xb7, 0x03, 0x00, 0x00,
}
