// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactionMessage_Eth.proto

package protoc_gen_go_eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxArray struct {
	Result               []*TX    `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxArray) Reset()         { *m = TxArray{} }
func (m *TxArray) String() string { return proto.CompactTextString(m) }
func (*TxArray) ProtoMessage()    {}
func (*TxArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{0}
}

func (m *TxArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxArray.Unmarshal(m, b)
}
func (m *TxArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxArray.Marshal(b, m, deterministic)
}
func (m *TxArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxArray.Merge(m, src)
}
func (m *TxArray) XXX_Size() int {
	return xxx_messageInfo_TxArray.Size(m)
}
func (m *TxArray) XXX_DiscardUnknown() {
	xxx_messageInfo_TxArray.DiscardUnknown(m)
}

var xxx_messageInfo_TxArray proto.InternalMessageInfo

func (m *TxArray) GetResult() []*TX {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetTransactionHashEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Txhash               string   `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionHashEndpointRequest) Reset()         { *m = GetTransactionHashEndpointRequest{} }
func (m *GetTransactionHashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionHashEndpointRequest) ProtoMessage()    {}
func (*GetTransactionHashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{1}
}

func (m *GetTransactionHashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionHashEndpointRequest.Unmarshal(m, b)
}
func (m *GetTransactionHashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionHashEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionHashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionHashEndpointRequest.Merge(m, src)
}
func (m *GetTransactionHashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionHashEndpointRequest.Size(m)
}
func (m *GetTransactionHashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionHashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionHashEndpointRequest proto.InternalMessageInfo

func (m *GetTransactionHashEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *GetTransactionHashEndpointRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type GetUnconfirmedTransactionsEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnconfirmedTransactionsEndpointRequest) Reset() {
	*m = GetUnconfirmedTransactionsEndpointRequest{}
}
func (m *GetUnconfirmedTransactionsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetUnconfirmedTransactionsEndpointRequest) ProtoMessage()    {}
func (*GetUnconfirmedTransactionsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{2}
}

func (m *GetUnconfirmedTransactionsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnconfirmedTransactionsEndpointRequest.Unmarshal(m, b)
}
func (m *GetUnconfirmedTransactionsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnconfirmedTransactionsEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetUnconfirmedTransactionsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnconfirmedTransactionsEndpointRequest.Merge(m, src)
}
func (m *GetUnconfirmedTransactionsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetUnconfirmedTransactionsEndpointRequest.Size(m)
}
func (m *GetUnconfirmedTransactionsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnconfirmedTransactionsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnconfirmedTransactionsEndpointRequest proto.InternalMessageInfo

func (m *GetUnconfirmedTransactionsEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

type PostCreateTransactionsEndpointRequest struct {
	Stage string `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	// Height of the block that contains this transaction. If this is an unconfirmed transaction, it will equal -1.
	BlockHeight int32 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// The hash of the transaction.
	Hash string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// Array of Ethereum addresses involved in the transaction.
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// The total number of wei exchanged in this transaction.
	Total int32 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	// The total number of fees—in wei—collected by miners in this transaction. Equal to gas_price * gas_used.
	Fees int32 `protobuf:"varint,6,opt,name=fees,proto3" json:"fees,omitempty"`
	// The size of the transaction in bytes.
	Size int32 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// The amount of gas used by this transaction.
	GasUsed int32 `protobuf:"varint,8,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// The price of gas—in wei—in this transaction.
	GasPrice int32 `protobuf:"varint,9,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// Address of the peer that sent BlockCypher’s servers this transaction. May be empty.
	RelayedBy string `protobuf:"bytes,10,opt,name=relayed_by,json=relayedBy,proto3" json:"relayed_by,omitempty"`
	// Time this transaction was received by BlockCypher’s servers.
	Received *timestamp.Timestamp `protobuf:"bytes,11,opt,name=received,proto3" json:"received,omitempty"`
	// Version number of this transaction.
	Ver int32 `protobuf:"varint,12,opt,name=ver,proto3" json:"ver,omitempty"`
	// true if this is an attempted double spend; false otherwise.
	DoubleSpend bool `protobuf:"varint,13,opt,name=double_spend,json=doubleSpend,proto3" json:"double_spend,omitempty"`
	// Total number of inputs in the transaction.
	VinSz int32 `protobuf:"varint,14,opt,name=vin_sz,json=vinSz,proto3" json:"vin_sz,omitempty"`
	// Total number of outputs in the transaction.
	VoutSz int32 `protobuf:"varint,15,opt,name=vout_sz,json=voutSz,proto3" json:"vout_sz,omitempty"`
	// Number of subsequent blocks, including the block the transaction is in. Unconfirmed transactions have 0 confirmations.
	Confirmations int32 `protobuf:"varint,16,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// An array object containing a single input with a sequence number (used as a nonce for account balances) and an Ethereum account address. Only contains one input in the array; we still use an array to maintain parity with the Bitcoin API.
	Inputs *any.Any `protobuf:"bytes,17,opt,name=inputs,proto3" json:"inputs,omitempty"`
	// An array object containing a single output with value (in wei), script, and an Ethereum account address. Only contains one output in the array; we still use an array to maintain parity with the Bitcoin API.
	Outputs *any.Any `protobuf:"bytes,18,opt,name=outputs,proto3" json:"outputs,omitempty"`
	// Optional If this transaction executed a contract which propagated its own subsequent transactions, then this array will be present, containing the hashes of those subsequent internal transactions.
	InternalTxids []string `protobuf:"bytes,19,rep,name=internal_txids,json=internalTxids,proto3" json:"internal_txids,omitempty"`
	// Optional If this transaction was initiated by a contract, this field will be present, conveying the hash of the parent transaction that executed the contract resulting in this transaction (the inverse of an internal_txids hash).
	ParentTx string `protobuf:"bytes,20,opt,name=parent_tx,json=parentTx,proto3" json:"parent_tx,omitempty"`
	// Optional Time at which transaction was included in a block; only present for confirmed transactions.
	Confirmed *timestamp.Timestamp `protobuf:"bytes,21,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	// Optional If creating a transaction, can optionally set a higher default gas limit (useful if your recepient is a contract). If not set, default is 21000 gas for external accounts and 80000 for contract accounts.
	GasLimit int32 `protobuf:"varint,22,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// Optional If true, this transaction was used to create a contract and contract account. Note that the contract address (in the outputs field) will be blank until the transaction is confirmed.
	ContractCreation bool `protobuf:"varint,23,opt,name=contract_creation,json=contractCreation,proto3" json:"contract_creation,omitempty"`
	// Optional Number of peers that have sent this transaction to BlockCypher; only present for unconfirmed transactions.
	ReceiveCount int32 `protobuf:"varint,24,opt,name=receive_count,json=receiveCount,proto3" json:"receive_count,omitempty"`
	// Optional Hash of the block that contains this transaction; only present for confirmed transactions.
	BlockHash string `protobuf:"bytes,25,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Optional Canonical, zero-indexed location of this transaction in a block; only present for confirmed transactions.
	BlockIndex int32 `protobuf:"varint,26,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	// Optional If this transaction is a double-spend (i.e. double_spend == true) then this is the hash of the transaction it’s double-spending.
	DoubleOf string `protobuf:"bytes,27,opt,name=double_of,json=doubleOf,proto3" json:"double_of,omitempty"`
	// Optional If this transaction has an execution error, then this field will be included (e.g. “out of gas”).
	ExecutionError       string   `protobuf:"bytes,28,opt,name=execution_error,json=executionError,proto3" json:"execution_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCreateTransactionsEndpointRequest) Reset()         { *m = PostCreateTransactionsEndpointRequest{} }
func (m *PostCreateTransactionsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PostCreateTransactionsEndpointRequest) ProtoMessage()    {}
func (*PostCreateTransactionsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{3}
}

func (m *PostCreateTransactionsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCreateTransactionsEndpointRequest.Unmarshal(m, b)
}
func (m *PostCreateTransactionsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCreateTransactionsEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PostCreateTransactionsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCreateTransactionsEndpointRequest.Merge(m, src)
}
func (m *PostCreateTransactionsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PostCreateTransactionsEndpointRequest.Size(m)
}
func (m *PostCreateTransactionsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCreateTransactionsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostCreateTransactionsEndpointRequest proto.InternalMessageInfo

func (m *PostCreateTransactionsEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *PostCreateTransactionsEndpointRequest) GetBlockHeight() int32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *PostCreateTransactionsEndpointRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *PostCreateTransactionsEndpointRequest) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetFees() int32 {
	if m != nil {
		return m.Fees
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetGasUsed() int32 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetGasPrice() int32 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetRelayedBy() string {
	if m != nil {
		return m.RelayedBy
	}
	return ""
}

func (m *PostCreateTransactionsEndpointRequest) GetReceived() *timestamp.Timestamp {
	if m != nil {
		return m.Received
	}
	return nil
}

func (m *PostCreateTransactionsEndpointRequest) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetDoubleSpend() bool {
	if m != nil {
		return m.DoubleSpend
	}
	return false
}

func (m *PostCreateTransactionsEndpointRequest) GetVinSz() int32 {
	if m != nil {
		return m.VinSz
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetVoutSz() int32 {
	if m != nil {
		return m.VoutSz
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetInputs() *any.Any {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PostCreateTransactionsEndpointRequest) GetOutputs() *any.Any {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *PostCreateTransactionsEndpointRequest) GetInternalTxids() []string {
	if m != nil {
		return m.InternalTxids
	}
	return nil
}

func (m *PostCreateTransactionsEndpointRequest) GetParentTx() string {
	if m != nil {
		return m.ParentTx
	}
	return ""
}

func (m *PostCreateTransactionsEndpointRequest) GetConfirmed() *timestamp.Timestamp {
	if m != nil {
		return m.Confirmed
	}
	return nil
}

func (m *PostCreateTransactionsEndpointRequest) GetGasLimit() int32 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetContractCreation() bool {
	if m != nil {
		return m.ContractCreation
	}
	return false
}

func (m *PostCreateTransactionsEndpointRequest) GetReceiveCount() int32 {
	if m != nil {
		return m.ReceiveCount
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *PostCreateTransactionsEndpointRequest) GetBlockIndex() int32 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *PostCreateTransactionsEndpointRequest) GetDoubleOf() string {
	if m != nil {
		return m.DoubleOf
	}
	return ""
}

func (m *PostCreateTransactionsEndpointRequest) GetExecutionError() string {
	if m != nil {
		return m.ExecutionError
	}
	return ""
}

type PostSendTransactionEndpointRequest struct {
	Stage string `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	// A temporary TX, usually returned fully filled.
	Tx *TX `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	// Array of hex-encoded data for you to sign, containing one element for you to sign. Still an array to maintain parity with the Bitcoin API.
	Tosign []string `protobuf:"bytes,3,rep,name=tosign,proto3" json:"tosign,omitempty"`
	// Array of signatures corresponding to all the data in tosign, typically provided by you. Only one signature is required.
	Signatures []string `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Optional Array of errors in the form “error”:“description-of-error”. This is only returned if there was an error in any stage of transaction generation, and is usually accompanied by a HTTP 400 code.
	Errors               []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostSendTransactionEndpointRequest) Reset()         { *m = PostSendTransactionEndpointRequest{} }
func (m *PostSendTransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PostSendTransactionEndpointRequest) ProtoMessage()    {}
func (*PostSendTransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{4}
}

func (m *PostSendTransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostSendTransactionEndpointRequest.Unmarshal(m, b)
}
func (m *PostSendTransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostSendTransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PostSendTransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostSendTransactionEndpointRequest.Merge(m, src)
}
func (m *PostSendTransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PostSendTransactionEndpointRequest.Size(m)
}
func (m *PostSendTransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostSendTransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostSendTransactionEndpointRequest proto.InternalMessageInfo

func (m *PostSendTransactionEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *PostSendTransactionEndpointRequest) GetTx() *TX {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *PostSendTransactionEndpointRequest) GetTosign() []string {
	if m != nil {
		return m.Tosign
	}
	return nil
}

func (m *PostSendTransactionEndpointRequest) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *PostSendTransactionEndpointRequest) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type PostDecodeRawTransactionEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Txhex                string   `protobuf:"bytes,2,opt,name=txhex,proto3" json:"txhex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostDecodeRawTransactionEndpointRequest) Reset() {
	*m = PostDecodeRawTransactionEndpointRequest{}
}
func (m *PostDecodeRawTransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PostDecodeRawTransactionEndpointRequest) ProtoMessage()    {}
func (*PostDecodeRawTransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{5}
}

func (m *PostDecodeRawTransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDecodeRawTransactionEndpointRequest.Unmarshal(m, b)
}
func (m *PostDecodeRawTransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDecodeRawTransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PostDecodeRawTransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDecodeRawTransactionEndpointRequest.Merge(m, src)
}
func (m *PostDecodeRawTransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PostDecodeRawTransactionEndpointRequest.Size(m)
}
func (m *PostDecodeRawTransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDecodeRawTransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostDecodeRawTransactionEndpointRequest proto.InternalMessageInfo

func (m *PostDecodeRawTransactionEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *PostDecodeRawTransactionEndpointRequest) GetTxhex() string {
	if m != nil {
		return m.Txhex
	}
	return ""
}

type PostPushRawTransactionEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Txhex                string   `protobuf:"bytes,2,opt,name=txhex,proto3" json:"txhex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostPushRawTransactionEndpointRequest) Reset()         { *m = PostPushRawTransactionEndpointRequest{} }
func (m *PostPushRawTransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PostPushRawTransactionEndpointRequest) ProtoMessage()    {}
func (*PostPushRawTransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_690b52dc89669b02, []int{6}
}

func (m *PostPushRawTransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostPushRawTransactionEndpointRequest.Unmarshal(m, b)
}
func (m *PostPushRawTransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostPushRawTransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PostPushRawTransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostPushRawTransactionEndpointRequest.Merge(m, src)
}
func (m *PostPushRawTransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PostPushRawTransactionEndpointRequest.Size(m)
}
func (m *PostPushRawTransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostPushRawTransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostPushRawTransactionEndpointRequest proto.InternalMessageInfo

func (m *PostPushRawTransactionEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *PostPushRawTransactionEndpointRequest) GetTxhex() string {
	if m != nil {
		return m.Txhex
	}
	return ""
}

func init() {
	proto.RegisterType((*TxArray)(nil), "fairwaycorp.blockchainprotobuf.eth.TxArray")
	proto.RegisterType((*GetTransactionHashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.GetTransactionHashEndpointRequest")
	proto.RegisterType((*GetUnconfirmedTransactionsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.GetUnconfirmedTransactionsEndpointRequest")
	proto.RegisterType((*PostCreateTransactionsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PostCreateTransactionsEndpointRequest")
	proto.RegisterType((*PostSendTransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PostSendTransactionEndpointRequest")
	proto.RegisterType((*PostDecodeRawTransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PostDecodeRawTransactionEndpointRequest")
	proto.RegisterType((*PostPushRawTransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PostPushRawTransactionEndpointRequest")
}

func init() { proto.RegisterFile("transactionMessage_Eth.proto", fileDescriptor_690b52dc89669b02) }

var fileDescriptor_690b52dc89669b02 = []byte{
	// 833 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdf, 0x6f, 0xdb, 0x36,
	0x10, 0xc7, 0xe1, 0xb8, 0xf1, 0x0f, 0x3a, 0x49, 0x53, 0x2e, 0x6d, 0x98, 0x34, 0x5b, 0x5d, 0x6d,
	0x5d, 0x3d, 0x6c, 0x56, 0x80, 0x0e, 0x28, 0xf6, 0xb2, 0x0d, 0x69, 0x16, 0xb4, 0x05, 0x36, 0x2c,
	0x93, 0x1d, 0x60, 0xd8, 0x8b, 0x40, 0x4b, 0x67, 0x89, 0x98, 0x4d, 0x6a, 0xe4, 0xc9, 0x95, 0xf3,
	0xaf, 0xed, 0x6d, 0x7f, 0xd9, 0x40, 0x52, 0xb6, 0xb3, 0x1f, 0x58, 0x13, 0x60, 0x4f, 0xe6, 0x7d,
	0x78, 0x3c, 0xf1, 0xee, 0xbe, 0x47, 0x93, 0x13, 0xd4, 0x5c, 0x1a, 0x9e, 0xa0, 0x50, 0xf2, 0x07,
	0x30, 0x86, 0x67, 0x10, 0x5f, 0x60, 0x1e, 0x16, 0x5a, 0xa1, 0xa2, 0xc1, 0x94, 0x0b, 0xfd, 0x8e,
	0x2f, 0x13, 0xa5, 0x8b, 0x70, 0x32, 0x53, 0xc9, 0xaf, 0x49, 0xce, 0x85, 0x74, 0x9b, 0x93, 0x72,
	0x1a, 0x02, 0xe6, 0xc7, 0x4f, 0x32, 0xa5, 0xb2, 0x19, 0x9c, 0xae, 0xe0, 0x29, 0x8a, 0x39, 0x18,
	0xe4, 0xf3, 0xc2, 0x07, 0x39, 0x3e, 0xfa, 0xbb, 0x03, 0x97, 0xcb, 0x7a, 0xeb, 0x30, 0x51, 0xf3,
	0xf9, 0xbf, 0x7c, 0x38, 0x78, 0x4b, 0xda, 0xe3, 0xea, 0x4c, 0x6b, 0xbe, 0xa4, 0xdf, 0x90, 0x96,
	0x06, 0x53, 0xce, 0x90, 0x35, 0xfa, 0xcd, 0x41, 0xef, 0xc5, 0xa7, 0xe1, 0xfb, 0x2f, 0x15, 0x8e,
	0x7f, 0x8e, 0xea, 0x53, 0xc1, 0x4f, 0xe4, 0xe9, 0x6b, 0xc0, 0xf1, 0x26, 0xcd, 0x37, 0xdc, 0xe4,
	0x17, 0x32, 0x2d, 0x94, 0x90, 0x18, 0xc1, 0x6f, 0x25, 0x18, 0xa4, 0x07, 0x64, 0xdb, 0x20, 0xcf,
	0x80, 0x35, 0xfa, 0x8d, 0x41, 0x37, 0xf2, 0x06, 0x7d, 0x44, 0x5a, 0x58, 0xe5, 0xdc, 0xe4, 0x6c,
	0xcb, 0xe1, 0xda, 0x0a, 0xce, 0xc8, 0x67, 0xaf, 0x01, 0xaf, 0x64, 0xa2, 0xe4, 0x54, 0xe8, 0x39,
	0xa4, 0x37, 0xa2, 0x9b, 0x5b, 0x85, 0x0e, 0x7e, 0x6f, 0x93, 0x67, 0x97, 0xca, 0xe0, 0xb9, 0x06,
	0x8e, 0x70, 0xe7, 0xf3, 0xf4, 0x29, 0xd9, 0x71, 0xa9, 0xc7, 0x39, 0x88, 0x2c, 0x47, 0x77, 0xc1,
	0xed, 0xa8, 0xe7, 0xd8, 0x1b, 0x87, 0x28, 0x25, 0xf7, 0xdc, 0xdd, 0x9b, 0xee, 0x9c, 0x5b, 0xd3,
	0x13, 0xd2, 0xe5, 0x69, 0xaa, 0xc1, 0x18, 0x30, 0xec, 0x5e, 0xbf, 0x39, 0xe8, 0x46, 0x1b, 0x60,
	0x3f, 0x85, 0x0a, 0xf9, 0x8c, 0x6d, 0xbb, 0x68, 0xde, 0xb0, 0x71, 0xa6, 0x00, 0x86, 0xb5, 0x1c,
	0x74, 0x6b, 0xcb, 0x8c, 0xb8, 0x06, 0xd6, 0xf6, 0xcc, 0xae, 0xe9, 0x11, 0xe9, 0x64, 0xdc, 0xc4,
	0xa5, 0x81, 0x94, 0x75, 0x1c, 0x6f, 0x67, 0xdc, 0x5c, 0x19, 0x48, 0xe9, 0x63, 0xd2, 0xb5, 0x5b,
	0x85, 0x16, 0x09, 0xb0, 0xae, 0xdb, 0xb3, 0xbe, 0x97, 0xd6, 0xa6, 0x1f, 0x12, 0xa2, 0x61, 0xc6,
	0x97, 0x90, 0xc6, 0x93, 0x25, 0x23, 0xee, 0xb6, 0xdd, 0x9a, 0xbc, 0x5a, 0xd2, 0x97, 0xa4, 0xa3,
	0x21, 0x01, 0xb1, 0x80, 0x94, 0xf5, 0xfa, 0x8d, 0x41, 0xef, 0xc5, 0x71, 0xe8, 0x15, 0x15, 0xae,
	0x5b, 0x3e, 0x5e, 0x49, 0x2e, 0x5a, 0xfb, 0xd2, 0x7d, 0xd2, 0x5c, 0x80, 0x66, 0x3b, 0xee, 0x6b,
	0x76, 0x69, 0x6b, 0x96, 0xaa, 0x72, 0x32, 0x83, 0xd8, 0x14, 0x20, 0x53, 0xb6, 0xdb, 0x6f, 0x0c,
	0x3a, 0x51, 0xcf, 0xb3, 0x91, 0x45, 0xf4, 0x21, 0x69, 0x2d, 0x84, 0x8c, 0xcd, 0x35, 0xdb, 0xf3,
	0x25, 0x58, 0x08, 0x39, 0xba, 0xa6, 0x87, 0xa4, 0xbd, 0x50, 0x25, 0x5a, 0x7e, 0xdf, 0xf1, 0x96,
	0x35, 0x47, 0xd7, 0xf4, 0x13, 0xb2, 0x5b, 0x8b, 0x80, 0xbb, 0xe6, 0xb1, 0x7d, 0xb7, 0xfd, 0x57,
	0x48, 0xbf, 0x20, 0x2d, 0x21, 0x8b, 0x12, 0x0d, 0x7b, 0xe0, 0x12, 0x38, 0xf8, 0x47, 0x02, 0x67,
	0x72, 0x19, 0xd5, 0x3e, 0x34, 0x24, 0x6d, 0x55, 0xa2, 0x73, 0xa7, 0xff, 0xe1, 0xbe, 0x72, 0xa2,
	0xcf, 0xc8, 0x9e, 0x90, 0x08, 0x5a, 0xf2, 0x59, 0x8c, 0x95, 0x48, 0x0d, 0xfb, 0xc0, 0x35, 0x76,
	0x77, 0x45, 0xc7, 0x16, 0xda, 0x1e, 0x14, 0x5c, 0x83, 0xc4, 0x18, 0x2b, 0x76, 0xe0, 0xaa, 0xdc,
	0xf1, 0x60, 0x5c, 0xd1, 0xaf, 0x48, 0x77, 0x2d, 0x66, 0xf6, 0xf0, 0xbd, 0x55, 0xde, 0x38, 0xaf,
	0x5a, 0x3b, 0x13, 0x73, 0x81, 0xec, 0xd1, 0xba, 0xb5, 0xdf, 0x5b, 0x9b, 0x7e, 0x4e, 0x1e, 0x24,
	0x4a, 0xa2, 0xe6, 0x09, 0xc6, 0x89, 0x55, 0xba, 0x50, 0x92, 0x1d, 0xba, 0xb2, 0xef, 0xaf, 0x36,
	0xce, 0x6b, 0x4e, 0x3f, 0x26, 0xbb, 0x75, 0xf3, 0xe2, 0x44, 0x95, 0x12, 0x19, 0x73, 0xd1, 0x76,
	0x6a, 0x78, 0x6e, 0x99, 0x15, 0x4b, 0xad, 0x7b, 0x2b, 0xed, 0x23, 0x2f, 0x16, 0xaf, 0x7a, 0xab,
	0xef, 0x27, 0xc4, 0x8f, 0x40, 0x2c, 0x64, 0x0a, 0x15, 0x3b, 0x76, 0x11, 0xfc, 0x89, 0xb7, 0x96,
	0xd8, 0xeb, 0xd6, 0x1a, 0x50, 0x53, 0xf6, 0xd8, 0x57, 0xc1, 0x83, 0x1f, 0xa7, 0xf4, 0x39, 0xb9,
	0x0f, 0x15, 0x24, 0xa5, 0xbd, 0x4e, 0x0c, 0x5a, 0x2b, 0xcd, 0x4e, 0x9c, 0xcb, 0xde, 0x1a, 0x5f,
	0x58, 0x1a, 0xfc, 0xd1, 0x20, 0x81, 0x9d, 0xde, 0x11, 0xc8, 0x9b, 0xb3, 0x7f, 0xbb, 0xd1, 0x7d,
	0x49, 0xb6, 0xb0, 0x72, 0x03, 0x7b, 0xfb, 0xc7, 0x6c, 0x0b, 0x2b, 0xf7, 0x1a, 0x29, 0x23, 0x32,
	0xc9, 0x9a, 0xae, 0xbf, 0xb5, 0x45, 0x3f, 0x22, 0xc4, 0xfe, 0x72, 0x2c, 0xf5, 0x7a, 0xa8, 0x6f,
	0x10, 0x7b, 0xce, 0xe5, 0x62, 0xd8, 0xb6, 0x3f, 0xe7, 0xad, 0xe0, 0x8a, 0x3c, 0xb7, 0x39, 0x7c,
	0x07, 0x89, 0x4a, 0x21, 0xe2, 0xef, 0xee, 0x9c, 0x88, 0x7d, 0x2e, 0xaa, 0x1c, 0xaa, 0xfa, 0x75,
	0xf4, 0x46, 0x30, 0xf2, 0x0f, 0xdb, 0x65, 0x69, 0xf2, 0xff, 0x2d, 0xe8, 0xab, 0x6f, 0x7f, 0xf9,
	0x3a, 0x13, 0x98, 0x97, 0x93, 0x30, 0x51, 0xf3, 0xd3, 0xba, 0x66, 0x43, 0x5b, 0xb4, 0xd3, 0x4d,
	0xd1, 0x86, 0xeb, 0x7f, 0x18, 0xb7, 0x48, 0x86, 0x19, 0xc8, 0x61, 0xa6, 0x86, 0x80, 0xf9, 0xa4,
	0xe5, 0xd0, 0x97, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x64, 0xbe, 0xb2, 0x06, 0xf0, 0x06, 0x00,
	0x00,
}
