// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressforwardingMessage.proto

package btc // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/btc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateForwardEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	// Identifier of the address forwarding request; generated when a new request is created.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The mandatory user token.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// The required destination address for address forwarding.
	Destination string `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	// The address which will automatically forward to destination; generated when a new request is created.
	InputAddress string `protobuf:"bytes,5,opt,name=input_address,json=inputAddress,proto3" json:"input_address,omitempty"`
	// Optional Address to forward processing fees, if specified. Allows you to receive a fee for your own services.
	ProcessFeesAddress string `protobuf:"bytes,6,opt,name=process_fees_address,json=processFeesAddress,proto3" json:"process_fees_address,omitempty"`
	// Optional Fixed processing fee amount to be sent to the fee address. A fixed satoshi amount or a percentage is required if a process_fees_address has been specified.
	ProcessFeesSatoshis int32 `protobuf:"varint,7,opt,name=process_fees_satoshis,json=processFeesSatoshis,proto3" json:"process_fees_satoshis,omitempty"`
	// Optional Percentage of the transaction to be sent to the fee address. A fixed satoshi amount or a percentage is required if a process_fees_address has been specified.
	ProcessFeesPercent float32 `protobuf:"fixed32,8,opt,name=process_fees_percent,json=processFeesPercent,proto3" json:"process_fees_percent,omitempty"`
	// Optional The URL to call anytime a new is forwarded.
	CallbackUrl string `protobuf:"bytes,9,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	// Optional Whether to also call the callback_url with subsequent confirmations of the forwarding transactions. Automatically sets up a WebHook.
	EnableConfirmations bool `protobuf:"varint,10,opt,name=enable_confirmations,json=enableConfirmations,proto3" json:"enable_confirmations,omitempty"`
	// Optional Mining fee amount to include in the forwarding transaction, in satoshis. If not set, defaults to 10,000.
	MiningFeesSatoshis int32 `protobuf:"varint,11,opt,name=mining_fees_satoshis,json=miningFeesSatoshis,proto3" json:"mining_fees_satoshis,omitempty"`
	// Optional History of forwarding transaction hashes for this address forward; not present if this request has yet to forward any transactions.
	Txs                  []string `protobuf:"bytes,12,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateForwardEndpointRequest) Reset()         { *m = CreateForwardEndpointRequest{} }
func (m *CreateForwardEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateForwardEndpointRequest) ProtoMessage()    {}
func (*CreateForwardEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressforwardingMessage_4d7096453585eb31, []int{0}
}
func (m *CreateForwardEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateForwardEndpointRequest.Unmarshal(m, b)
}
func (m *CreateForwardEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateForwardEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CreateForwardEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateForwardEndpointRequest.Merge(dst, src)
}
func (m *CreateForwardEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateForwardEndpointRequest.Size(m)
}
func (m *CreateForwardEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateForwardEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateForwardEndpointRequest proto.InternalMessageInfo

func (m *CreateForwardEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *CreateForwardEndpointRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateForwardEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateForwardEndpointRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *CreateForwardEndpointRequest) GetInputAddress() string {
	if m != nil {
		return m.InputAddress
	}
	return ""
}

func (m *CreateForwardEndpointRequest) GetProcessFeesAddress() string {
	if m != nil {
		return m.ProcessFeesAddress
	}
	return ""
}

func (m *CreateForwardEndpointRequest) GetProcessFeesSatoshis() int32 {
	if m != nil {
		return m.ProcessFeesSatoshis
	}
	return 0
}

func (m *CreateForwardEndpointRequest) GetProcessFeesPercent() float32 {
	if m != nil {
		return m.ProcessFeesPercent
	}
	return 0
}

func (m *CreateForwardEndpointRequest) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

func (m *CreateForwardEndpointRequest) GetEnableConfirmations() bool {
	if m != nil {
		return m.EnableConfirmations
	}
	return false
}

func (m *CreateForwardEndpointRequest) GetMiningFeesSatoshis() int32 {
	if m != nil {
		return m.MiningFeesSatoshis
	}
	return 0
}

func (m *CreateForwardEndpointRequest) GetTxs() []string {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ListForwardsEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	// Returns list of address forwards starting at the start index; useful for paging beyond the limit of 200 address forwards.
	Start                int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListForwardsEndpointRequest) Reset()         { *m = ListForwardsEndpointRequest{} }
func (m *ListForwardsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*ListForwardsEndpointRequest) ProtoMessage()    {}
func (*ListForwardsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressforwardingMessage_4d7096453585eb31, []int{1}
}
func (m *ListForwardsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListForwardsEndpointRequest.Unmarshal(m, b)
}
func (m *ListForwardsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListForwardsEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *ListForwardsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListForwardsEndpointRequest.Merge(dst, src)
}
func (m *ListForwardsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_ListForwardsEndpointRequest.Size(m)
}
func (m *ListForwardsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListForwardsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListForwardsEndpointRequest proto.InternalMessageInfo

func (m *ListForwardsEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *ListForwardsEndpointRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

type AddressForwards struct {
	Forwards             []*AddressForward `protobuf:"bytes,1,rep,name=forwards,proto3" json:"forwards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddressForwards) Reset()         { *m = AddressForwards{} }
func (m *AddressForwards) String() string { return proto.CompactTextString(m) }
func (*AddressForwards) ProtoMessage()    {}
func (*AddressForwards) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressforwardingMessage_4d7096453585eb31, []int{2}
}
func (m *AddressForwards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressForwards.Unmarshal(m, b)
}
func (m *AddressForwards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressForwards.Marshal(b, m, deterministic)
}
func (dst *AddressForwards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressForwards.Merge(dst, src)
}
func (m *AddressForwards) XXX_Size() int {
	return xxx_messageInfo_AddressForwards.Size(m)
}
func (m *AddressForwards) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressForwards.DiscardUnknown(m)
}

var xxx_messageInfo_AddressForwards proto.InternalMessageInfo

func (m *AddressForwards) GetForwards() []*AddressForward {
	if m != nil {
		return m.Forwards
	}
	return nil
}

type DeleteForwardEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Payid                string               `protobuf:"bytes,2,opt,name=payid,proto3" json:"payid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteForwardEndpointRequest) Reset()         { *m = DeleteForwardEndpointRequest{} }
func (m *DeleteForwardEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteForwardEndpointRequest) ProtoMessage()    {}
func (*DeleteForwardEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressforwardingMessage_4d7096453585eb31, []int{3}
}
func (m *DeleteForwardEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteForwardEndpointRequest.Unmarshal(m, b)
}
func (m *DeleteForwardEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteForwardEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteForwardEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteForwardEndpointRequest.Merge(dst, src)
}
func (m *DeleteForwardEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteForwardEndpointRequest.Size(m)
}
func (m *DeleteForwardEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteForwardEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteForwardEndpointRequest proto.InternalMessageInfo

func (m *DeleteForwardEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *DeleteForwardEndpointRequest) GetPayid() string {
	if m != nil {
		return m.Payid
	}
	return ""
}

type DeleteForwardEndpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteForwardEndpointResponse) Reset()         { *m = DeleteForwardEndpointResponse{} }
func (m *DeleteForwardEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteForwardEndpointResponse) ProtoMessage()    {}
func (*DeleteForwardEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_addressforwardingMessage_4d7096453585eb31, []int{4}
}
func (m *DeleteForwardEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteForwardEndpointResponse.Unmarshal(m, b)
}
func (m *DeleteForwardEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteForwardEndpointResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteForwardEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteForwardEndpointResponse.Merge(dst, src)
}
func (m *DeleteForwardEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteForwardEndpointResponse.Size(m)
}
func (m *DeleteForwardEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteForwardEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteForwardEndpointResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateForwardEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.CreateForwardEndpointRequest")
	proto.RegisterType((*ListForwardsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.ListForwardsEndpointRequest")
	proto.RegisterType((*AddressForwards)(nil), "fairwaycorp.blockchainprotobuf.btc.AddressForwards")
	proto.RegisterType((*DeleteForwardEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.DeleteForwardEndpointRequest")
	proto.RegisterType((*DeleteForwardEndpointResponse)(nil), "fairwaycorp.blockchainprotobuf.btc.DeleteForwardEndpointResponse")
}

func init() {
	proto.RegisterFile("addressforwardingMessage.proto", fileDescriptor_addressforwardingMessage_4d7096453585eb31)
}

var fileDescriptor_addressforwardingMessage_4d7096453585eb31 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x76, 0xd9, 0x56, 0xb7, 0x0c, 0xe4, 0x16, 0xc9, 0x82, 0x01, 0x21, 0x5c, 0x72,
	0x69, 0x0a, 0xe5, 0xc2, 0x05, 0xa1, 0x32, 0xd8, 0x09, 0x26, 0x14, 0xc4, 0x85, 0x4b, 0xe5, 0x38,
	0xaf, 0xa9, 0xd5, 0xd4, 0x0e, 0x7e, 0xae, 0xca, 0xfe, 0x02, 0xb8, 0xf2, 0x1f, 0xa3, 0xda, 0x69,
	0x69, 0x41, 0x08, 0x4e, 0xbb, 0xd9, 0xdf, 0xef, 0xfb, 0xf1, 0x71, 0xf2, 0x1e, 0x79, 0xc8, 0x8b,
	0xc2, 0x00, 0xe2, 0x4c, 0x9b, 0x35, 0x37, 0x85, 0x54, 0xe5, 0x7b, 0x40, 0xe4, 0x25, 0xa4, 0xb5,
	0xd1, 0x56, 0xd3, 0x78, 0xc6, 0xa5, 0x59, 0xf3, 0x6b, 0xa1, 0x4d, 0x9d, 0xe6, 0x95, 0x16, 0x0b,
	0x31, 0xe7, 0x52, 0x39, 0x33, 0x5f, 0xcd, 0xd2, 0xdc, 0x8a, 0x7b, 0x7d, 0xa1, 0x97, 0x4b, 0xad,
	0x0e, 0x12, 0xe3, 0x1f, 0x47, 0xe4, 0xfc, 0xc2, 0x00, 0xb7, 0x70, 0xe9, 0x4b, 0xbf, 0x55, 0x45,
	0xad, 0xa5, 0xb2, 0x19, 0x7c, 0x59, 0x01, 0x5a, 0x9a, 0x91, 0x13, 0x05, 0x76, 0xad, 0xcd, 0x82,
	0x05, 0x51, 0x90, 0x9c, 0x8d, 0x5f, 0xa4, 0xff, 0xee, 0x95, 0x5e, 0xf9, 0x94, 0x49, 0x55, 0xe9,
	0xb5, 0x54, 0xe5, 0xa4, 0x92, 0x1c, 0xb3, 0x6d, 0x21, 0x7a, 0x46, 0x5a, 0xb2, 0x60, 0xad, 0x28,
	0x48, 0x3a, 0x59, 0x4b, 0x16, 0x74, 0x40, 0x42, 0xab, 0x17, 0xa0, 0x58, 0xdb, 0x49, 0xfe, 0x42,
	0x23, 0xd2, 0x2d, 0x00, 0xad, 0x54, 0xdc, 0x4a, 0xad, 0xd8, 0x91, 0xf3, 0xf6, 0x25, 0xfa, 0x84,
	0xdc, 0x92, 0xaa, 0x5e, 0xd9, 0x69, 0xf3, 0x75, 0x58, 0xe8, 0x62, 0x7a, 0x4e, 0x9c, 0x78, 0x8d,
	0x3e, 0x25, 0x83, 0xda, 0x68, 0x01, 0x88, 0xd3, 0x19, 0x00, 0xee, 0x62, 0x8f, 0x5d, 0x2c, 0x6d,
	0xbc, 0x4b, 0x00, 0xdc, 0x66, 0x8c, 0xc9, 0xdd, 0x83, 0x0c, 0xe4, 0x56, 0xe3, 0x5c, 0x22, 0x3b,
	0x89, 0x82, 0x24, 0xcc, 0xfa, 0x7b, 0x29, 0x1f, 0x1b, 0xeb, 0x8f, 0x2e, 0x35, 0x18, 0x01, 0xca,
	0xb2, 0xd3, 0x28, 0x48, 0x5a, 0x07, 0x5d, 0x3e, 0x78, 0x87, 0x3e, 0x26, 0x3d, 0xc1, 0xab, 0x2a,
	0xe7, 0x62, 0x31, 0x5d, 0x99, 0x8a, 0x75, 0xfc, 0xfb, 0xb6, 0xda, 0x27, 0x53, 0xd1, 0x67, 0x64,
	0x00, 0x8a, 0xe7, 0x15, 0x4c, 0x85, 0x56, 0x33, 0x69, 0x96, 0xee, 0xd9, 0xc8, 0x48, 0x14, 0x24,
	0xa7, 0x59, 0xdf, 0x7b, 0x17, 0xfb, 0xd6, 0x86, 0x63, 0x29, 0x95, 0x54, 0xe5, 0x6f, 0xe8, 0x5d,
	0x87, 0x4e, 0xbd, 0x77, 0x40, 0x7e, 0x87, 0xb4, 0xed, 0x57, 0x64, 0xbd, 0xa8, 0x9d, 0x74, 0xb2,
	0xcd, 0x31, 0xfe, 0x16, 0x90, 0xfb, 0xef, 0x24, 0xda, 0x66, 0x22, 0xf0, 0x26, 0x46, 0x62, 0x40,
	0x42, 0xb4, 0xdc, 0x58, 0x37, 0x15, 0x61, 0xe6, 0x2f, 0x31, 0x27, 0xb7, 0x9b, 0x9f, 0xb2, 0x65,
	0xa1, 0x57, 0xe4, 0xb4, 0x59, 0x02, 0x64, 0x41, 0xd4, 0x4e, 0xba, 0xe3, 0xf1, 0xff, 0x74, 0x3f,
	0x2c, 0x93, 0xed, 0x6a, 0xc4, 0xdf, 0x03, 0x72, 0xfe, 0x06, 0x2a, 0xb8, 0xd1, 0x05, 0x18, 0x90,
	0xb0, 0xe6, 0xd7, 0xbb, 0x1d, 0xf0, 0x97, 0xf8, 0x11, 0x79, 0xf0, 0x17, 0x12, 0xac, 0xb5, 0x42,
	0x78, 0xfd, 0xea, 0xf3, 0xcb, 0x52, 0xda, 0xf9, 0x2a, 0x4f, 0x85, 0x5e, 0x8e, 0x1a, 0x8a, 0xe1,
	0x06, 0x63, 0xf4, 0x0b, 0x63, 0xb8, 0xe5, 0x18, 0xb9, 0x83, 0x18, 0x96, 0xa0, 0x86, 0xa5, 0x1e,
	0xe5, 0x56, 0xe4, 0xc7, 0x4e, 0x7a, 0xfe, 0x33, 0x00, 0x00, 0xff, 0xff, 0x76, 0xc1, 0xcb, 0x5e,
	0x4f, 0x04, 0x00, 0x00,
}
