// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressforwardingService.proto

package btc // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/btc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddressForwardingServiceClient is the client API for AddressForwardingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressForwardingServiceClient interface {
	CreateForwardEndpoint(ctx context.Context, in *CreateForwardEndpointRequest, opts ...grpc.CallOption) (*AddressForward, error)
	ListForwardsEndpoint(ctx context.Context, in *ListForwardsEndpointRequest, opts ...grpc.CallOption) (*AddressForwards, error)
	DeleteForwardEndpoint(ctx context.Context, in *DeleteForwardEndpointRequest, opts ...grpc.CallOption) (*NullValue, error)
}

type addressForwardingServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressForwardingServiceClient(cc *grpc.ClientConn) AddressForwardingServiceClient {
	return &addressForwardingServiceClient{cc}
}

func (c *addressForwardingServiceClient) CreateForwardEndpoint(ctx context.Context, in *CreateForwardEndpointRequest, opts ...grpc.CallOption) (*AddressForward, error) {
	out := new(AddressForward)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.btc.AddressForwardingService/CreateForwardEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressForwardingServiceClient) ListForwardsEndpoint(ctx context.Context, in *ListForwardsEndpointRequest, opts ...grpc.CallOption) (*AddressForwards, error) {
	out := new(AddressForwards)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.btc.AddressForwardingService/ListForwardsEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressForwardingServiceClient) DeleteForwardEndpoint(ctx context.Context, in *DeleteForwardEndpointRequest, opts ...grpc.CallOption) (*NullValue, error) {
	out := new(NullValue)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.btc.AddressForwardingService/DeleteForwardEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressForwardingServiceServer is the server API for AddressForwardingService service.
type AddressForwardingServiceServer interface {
	CreateForwardEndpoint(context.Context, *CreateForwardEndpointRequest) (*AddressForward, error)
	ListForwardsEndpoint(context.Context, *ListForwardsEndpointRequest) (*AddressForwards, error)
	DeleteForwardEndpoint(context.Context, *DeleteForwardEndpointRequest) (*NullValue, error)
}

func RegisterAddressForwardingServiceServer(s *grpc.Server, srv AddressForwardingServiceServer) {
	s.RegisterService(&_AddressForwardingService_serviceDesc, srv)
}

func _AddressForwardingService_CreateForwardEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForwardEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressForwardingServiceServer).CreateForwardEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.btc.AddressForwardingService/CreateForwardEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressForwardingServiceServer).CreateForwardEndpoint(ctx, req.(*CreateForwardEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressForwardingService_ListForwardsEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListForwardsEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressForwardingServiceServer).ListForwardsEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.btc.AddressForwardingService/ListForwardsEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressForwardingServiceServer).ListForwardsEndpoint(ctx, req.(*ListForwardsEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressForwardingService_DeleteForwardEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteForwardEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressForwardingServiceServer).DeleteForwardEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.btc.AddressForwardingService/DeleteForwardEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressForwardingServiceServer).DeleteForwardEndpoint(ctx, req.(*DeleteForwardEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressForwardingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fairwaycorp.blockchainprotobuf.btc.AddressForwardingService",
	HandlerType: (*AddressForwardingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForwardEndpoint",
			Handler:    _AddressForwardingService_CreateForwardEndpoint_Handler,
		},
		{
			MethodName: "ListForwardsEndpoint",
			Handler:    _AddressForwardingService_ListForwardsEndpoint_Handler,
		},
		{
			MethodName: "DeleteForwardEndpoint",
			Handler:    _AddressForwardingService_DeleteForwardEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressforwardingService.proto",
}

func init() {
	proto.RegisterFile("addressforwardingService.proto", fileDescriptor_addressforwardingService_cb5d06bd1a40d69a)
}

var fileDescriptor_addressforwardingService_cb5d06bd1a40d69a = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xa9, 0x88, 0x87, 0x1c, 0xa3, 0xa2, 0x86, 0x62, 0x31, 0x17, 0x41, 0x48, 0x16, 0xda,
	0x9b, 0x20, 0xf5, 0xff, 0x49, 0x3d, 0x28, 0x78, 0xf0, 0x36, 0xd9, 0x4c, 0xb7, 0x4b, 0xd3, 0x9d,
	0xb8, 0xbb, 0xb1, 0x94, 0xd2, 0x8b, 0xaf, 0xe0, 0x73, 0x78, 0xd0, 0x57, 0xf1, 0x15, 0x7c, 0x10,
	0xe9, 0x36, 0x55, 0xaa, 0x2d, 0x56, 0x6f, 0xcb, 0x0c, 0xdf, 0xf7, 0xfb, 0xed, 0x78, 0xdb, 0x90,
	0xa6, 0x1a, 0x8d, 0x69, 0x91, 0xee, 0x81, 0x4e, 0xa5, 0x12, 0x37, 0xa8, 0x1f, 0x24, 0xc7, 0x38,
	0xd7, 0x64, 0xc9, 0x0f, 0x5b, 0x20, 0x75, 0x0f, 0xfa, 0x9c, 0x74, 0x1e, 0x27, 0x19, 0xf1, 0x0e,
	0x6f, 0x83, 0x54, 0x6e, 0x99, 0x14, 0xad, 0x38, 0xb1, 0x3c, 0xa8, 0x0a, 0x22, 0x91, 0x21, 0x83,
	0x5c, 0x32, 0x50, 0x8a, 0x2c, 0x58, 0x49, 0xca, 0x8c, 0x1b, 0x82, 0x9f, 0x84, 0x4b, 0x34, 0x06,
	0x44, 0x49, 0x08, 0x56, 0x39, 0x75, 0xbb, 0xa4, 0xa6, 0x86, 0xf5, 0xd7, 0x65, 0x6f, 0xf3, 0x68,
	0x9c, 0x3b, 0xff, 0x6e, 0xe6, 0xbf, 0x54, 0xbc, 0xf5, 0x13, 0x8d, 0x60, 0xb1, 0xdc, 0x9d, 0xa9,
	0x34, 0x27, 0xa9, 0xac, 0x7f, 0x18, 0xff, 0xae, 0x1b, 0xcf, 0x8c, 0x5e, 0xe3, 0x7d, 0x81, 0xc6,
	0x06, 0xf5, 0x45, 0x1a, 0xa6, 0xcd, 0xc2, 0xf0, 0xf1, 0xed, 0xfd, 0x69, 0xa9, 0x1a, 0x6e, 0xb0,
	0xc4, 0x72, 0x36, 0x50, 0x68, 0x7b, 0xa4, 0x3b, 0x43, 0x56, 0xfe, 0xd8, 0xec, 0x57, 0xf6, 0xfc,
	0xe7, 0x8a, 0xb7, 0x76, 0x21, 0x8d, 0x2d, 0x33, 0xe6, 0x53, 0xb9, 0xb9, 0x08, 0x70, 0x56, 0x72,
	0x62, 0xdc, 0xf8, 0xbb, 0xb1, 0x09, 0x6b, 0x4e, 0x79, 0xcb, 0x9f, 0xa7, 0xec, 0x6e, 0x7c, 0x8a,
	0x19, 0xfe, 0xf3, 0xc6, 0x33, 0xa3, 0x13, 0xe3, 0x68, 0x91, 0x86, 0xab, 0x22, 0xcb, 0x6e, 0x21,
	0x2b, 0x30, 0xdc, 0x75, 0xae, 0x3b, 0x7e, 0x6d, 0x8e, 0x2b, 0x1b, 0xe4, 0xd0, 0x97, 0xe9, 0xf0,
	0xb8, 0x79, 0x77, 0x20, 0xa4, 0x6d, 0x17, 0x49, 0xcc, 0xa9, 0xcb, 0x4a, 0x46, 0x34, 0x82, 0xb0,
	0x2f, 0x48, 0x34, 0xa1, 0x30, 0xf7, 0xe0, 0x91, 0x40, 0x15, 0x09, 0x1a, 0x75, 0x27, 0x2b, 0x6e,
	0xd4, 0xf8, 0x08, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xce, 0x86, 0x0b, 0x15, 0x03, 0x00, 0x00,
}
