// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analyticsMessage.proto

package btc // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/btc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAnalyticsJobRequest struct {
	Network    NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Enginename string               `protobuf:"bytes,2,opt,name=enginename,proto3" json:"enginename,omitempty"`
	// Address hash this job is querying.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// Minimal/threshold value (in satoshis) to query.
	ValueThreshold int32 `protobuf:"varint,4,opt,name=value_threshold,json=valueThreshold,proto3" json:"value_threshold,omitempty"`
	// Limit of results to return.
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Beginning of time range to query.
	Start string `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	// End of time range to query.
	End string `protobuf:"bytes,7,opt,name=end,proto3" json:"end,omitempty"`
	// Degree of connectiveness to query.
	Degree int32 `protobuf:"varint,8,opt,name=degree,proto3" json:"degree,omitempty"`
	// IP address and port, of the form “0.0.0.0:80”. Ideally an IP and port combination found from another API lookup (for example, relayed_by from the Transaction Hash Endpoint)
	Source               string   `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAnalyticsJobRequest) Reset()         { *m = CreateAnalyticsJobRequest{} }
func (m *CreateAnalyticsJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAnalyticsJobRequest) ProtoMessage()    {}
func (*CreateAnalyticsJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyticsMessage_36f49532434cf008, []int{0}
}
func (m *CreateAnalyticsJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAnalyticsJobRequest.Unmarshal(m, b)
}
func (m *CreateAnalyticsJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAnalyticsJobRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAnalyticsJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAnalyticsJobRequest.Merge(dst, src)
}
func (m *CreateAnalyticsJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAnalyticsJobRequest.Size(m)
}
func (m *CreateAnalyticsJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAnalyticsJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAnalyticsJobRequest proto.InternalMessageInfo

func (m *CreateAnalyticsJobRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *CreateAnalyticsJobRequest) GetEnginename() string {
	if m != nil {
		return m.Enginename
	}
	return ""
}

func (m *CreateAnalyticsJobRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateAnalyticsJobRequest) GetValueThreshold() int32 {
	if m != nil {
		return m.ValueThreshold
	}
	return 0
}

func (m *CreateAnalyticsJobRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CreateAnalyticsJobRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *CreateAnalyticsJobRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *CreateAnalyticsJobRequest) GetDegree() int32 {
	if m != nil {
		return m.Degree
	}
	return 0
}

func (m *CreateAnalyticsJobRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetAnalyticsJobRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Ticket               string               `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAnalyticsJobRequest) Reset()         { *m = GetAnalyticsJobRequest{} }
func (m *GetAnalyticsJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnalyticsJobRequest) ProtoMessage()    {}
func (*GetAnalyticsJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyticsMessage_36f49532434cf008, []int{1}
}
func (m *GetAnalyticsJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnalyticsJobRequest.Unmarshal(m, b)
}
func (m *GetAnalyticsJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnalyticsJobRequest.Marshal(b, m, deterministic)
}
func (dst *GetAnalyticsJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnalyticsJobRequest.Merge(dst, src)
}
func (m *GetAnalyticsJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnalyticsJobRequest.Size(m)
}
func (m *GetAnalyticsJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnalyticsJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnalyticsJobRequest proto.InternalMessageInfo

func (m *GetAnalyticsJobRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *GetAnalyticsJobRequest) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

type GetAnalyticsJobResultsRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Ticket               string               `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Page                 int32                `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAnalyticsJobResultsRequest) Reset()         { *m = GetAnalyticsJobResultsRequest{} }
func (m *GetAnalyticsJobResultsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnalyticsJobResultsRequest) ProtoMessage()    {}
func (*GetAnalyticsJobResultsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analyticsMessage_36f49532434cf008, []int{2}
}
func (m *GetAnalyticsJobResultsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnalyticsJobResultsRequest.Unmarshal(m, b)
}
func (m *GetAnalyticsJobResultsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnalyticsJobResultsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAnalyticsJobResultsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnalyticsJobResultsRequest.Merge(dst, src)
}
func (m *GetAnalyticsJobResultsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnalyticsJobResultsRequest.Size(m)
}
func (m *GetAnalyticsJobResultsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnalyticsJobResultsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnalyticsJobResultsRequest proto.InternalMessageInfo

func (m *GetAnalyticsJobResultsRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *GetAnalyticsJobResultsRequest) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *GetAnalyticsJobResultsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateAnalyticsJobRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.CreateAnalyticsJobRequest")
	proto.RegisterType((*GetAnalyticsJobRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GetAnalyticsJobRequest")
	proto.RegisterType((*GetAnalyticsJobResultsRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GetAnalyticsJobResultsRequest")
}

func init() {
	proto.RegisterFile("analyticsMessage.proto", fileDescriptor_analyticsMessage_36f49532434cf008)
}

var fileDescriptor_analyticsMessage_36f49532434cf008 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0xb6, 0x49, 0xa9, 0x0f, 0x05, 0x19, 0x14, 0x19, 0x24, 0x50, 0x95, 0x0b, 0xbd,
	0x24, 0x91, 0xe0, 0xc2, 0x05, 0xa1, 0xc2, 0x01, 0x09, 0x09, 0x0e, 0x11, 0x27, 0x2e, 0xc8, 0x71,
	0xa6, 0x8e, 0x55, 0xc7, 0x2e, 0xf6, 0x84, 0xaa, 0x77, 0xde, 0x83, 0x57, 0xe1, 0xd1, 0x50, 0xdc,
	0x44, 0xbb, 0xab, 0x3d, 0xec, 0x6d, 0xf7, 0x36, 0xff, 0x37, 0x9e, 0xff, 0x1f, 0x8d, 0x49, 0xca,
	0x0d, 0xd7, 0x67, 0x54, 0xc2, 0x7f, 0x05, 0xef, 0xb9, 0x84, 0xe2, 0xe8, 0x2c, 0x5a, 0x9a, 0xed,
	0xb9, 0x72, 0x27, 0x7e, 0x16, 0xd6, 0x1d, 0x8b, 0x5a, 0x5b, 0x71, 0x10, 0x2d, 0x57, 0x26, 0x34,
	0xeb, 0x7e, 0x5f, 0xd4, 0x28, 0x5e, 0x3c, 0x15, 0xb6, 0xeb, 0xac, 0xb9, 0x31, 0x98, 0xfd, 0x9b,
	0x91, 0xe7, 0x9f, 0x1c, 0x70, 0x84, 0xdd, 0xe4, 0xfc, 0xc5, 0xd6, 0x15, 0xfc, 0xea, 0xc1, 0x23,
	0xad, 0xc8, 0xd2, 0x00, 0x9e, 0xac, 0x3b, 0xb0, 0x68, 0x13, 0x6d, 0xd7, 0x6f, 0xde, 0x15, 0x77,
	0x07, 0x15, 0xdf, 0x2e, 0x23, 0x3b, 0xad, 0xed, 0x49, 0x19, 0xb9, 0xd3, 0x8a, 0xfb, 0x6a, 0x32,
	0xa2, 0xaf, 0x08, 0x01, 0x23, 0x95, 0x01, 0xc3, 0x3b, 0x60, 0xb3, 0x4d, 0xb4, 0x5d, 0x55, 0xd7,
	0x08, 0x65, 0x64, 0xc9, 0x9b, 0xc6, 0x81, 0xf7, 0x6c, 0x1e, 0x9a, 0x93, 0xa4, 0xaf, 0xc9, 0xe3,
	0xdf, 0x5c, 0xf7, 0xf0, 0x13, 0x5b, 0x07, 0xbe, 0xb5, 0xba, 0x61, 0x8b, 0x4d, 0xb4, 0x8d, 0xab,
	0x75, 0xc0, 0xdf, 0x27, 0x4a, 0x9f, 0x91, 0x58, 0xab, 0x4e, 0x21, 0x8b, 0x43, 0xfb, 0x22, 0x06,
	0xea, 0x91, 0x3b, 0x64, 0x49, 0xb0, 0xbd, 0x08, 0xfa, 0x84, 0xcc, 0xc1, 0x34, 0x6c, 0x19, 0xd8,
	0x50, 0xd2, 0x94, 0x24, 0x0d, 0x48, 0x07, 0xc0, 0x1e, 0x85, 0xf1, 0x51, 0x0d, 0xdc, 0xdb, 0xde,
	0x09, 0x60, 0xab, 0xf0, 0x78, 0x54, 0xd9, 0x9f, 0x88, 0xa4, 0x9f, 0x01, 0xef, 0xeb, 0x7e, 0x29,
	0x49, 0x50, 0x89, 0x03, 0xe0, 0x78, 0xbb, 0x51, 0x65, 0x7f, 0x23, 0xf2, 0xf2, 0xd6, 0x1a, 0xbe,
	0xd7, 0xe8, 0x1f, 0x60, 0x1b, 0x4a, 0xc9, 0xe2, 0xc8, 0x25, 0x84, 0x2f, 0x8c, 0xab, 0x50, 0x7f,
	0xfc, 0xf0, 0xe3, 0xbd, 0x54, 0xd8, 0xf6, 0x75, 0x21, 0x6c, 0x57, 0x8e, 0xd1, 0xf9, 0x90, 0x5d,
	0x5e, 0x65, 0xe7, 0x53, 0x78, 0x19, 0x0a, 0x91, 0x4b, 0x30, 0xb9, 0xb4, 0x65, 0x8d, 0xa2, 0x4e,
	0x02, 0x7a, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x03, 0x29, 0x21, 0x3b, 0x06, 0x03, 0x00, 0x00,
}
