// Code generated by protoc-gen-go. DO NOT EDIT.
// source: microtransactionMessage.proto

package btc // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/btc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MicroTX struct {
	// Hex-encoded public key from which you’re sending coins.
	FromPubkey string `protobuf:"bytes,1,opt,name=from_pubkey,json=fromPubkey,proto3" json:"from_pubkey,omitempty"`
	// Hex-encoded private key from which you’re sending coins.
	FromPrivate string `protobuf:"bytes,2,opt,name=from_private,json=fromPrivate,proto3" json:"from_private,omitempty"`
	// WIF-encoded private key from which you’re sending coins.
	FromWif string `protobuf:"bytes,3,opt,name=from_wif,json=fromWif,proto3" json:"from_wif,omitempty"`
	// The target address to which you’re sending coins.
	ToAddress string `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// Value you’re sending/you’ve sent in satoshis.
	ValueSatoshis int64 `protobuf:"varint,5,opt,name=value_satoshis,json=valueSatoshis,proto3" json:"value_satoshis,omitempty"`
	// Your Block API token
	Token string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	// Optional Address Block will use to send back your change. If not set, defaults to the address from which the coins were originally sent. While not required, we recommend that you set a change address.
	ChangeAddress string `protobuf:"bytes,7,opt,name=change_address,json=changeAddress,proto3" json:"change_address,omitempty"`
	// Optional If not set, defaults to true, which means the API will wait for Block to guarantee the transaction, using our Confidence Factor. The guarantee usually takes around 8 seconds. If manually set to false, the Microtransaction endpoint will return as soon as the transaction is broadcast.
	WaitGuarantee bool `protobuf:"varint,8,opt,name=wait_guarantee,json=waitGuarantee,proto3" json:"wait_guarantee,omitempty"`
	// Optional Hex-encoded data for you to sign after initiating the microtransaction. Sent in reply to a microtransaction generated using from_pubkey/a public key.
	Tosign []string `protobuf:"bytes,9,rep,name=tosign,proto3" json:"tosign,omitempty"`
	// Optional Hex-encoded signatures for you to send back after having received (and signed) tosign.
	Signatures []string `protobuf:"bytes,10,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Optional Partial list of inputs that will be used with this transaction. Inputs themsleves are heavily pared down, see cURL sample. Only returned when using from_pubkey.
	Inputs []*TXInput `protobuf:"bytes,11,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Optional Partial list of outputs that will be used with this transaction. Outputs themselves are heavily pared down, see cURL sample. Only returned when using from_pubkey.
	Outputs []*TXOutput `protobuf:"bytes,12,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Optional Block’s optimally calculated fees for this MicroTX to guarantee swift 99% confirmation, only returned when using from_pubkey. Block pays these fees for the first 8,000 microtransactions, but like regular transactions, it is deducted from the source address thereafter.
	Fees int32 `protobuf:"varint,13,opt,name=fees,proto3" json:"fees,omitempty"`
	// Optional The hash of the finalized transaction, once sent.
	Hash                 string   `protobuf:"bytes,14,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MicroTX) Reset()         { *m = MicroTX{} }
func (m *MicroTX) String() string { return proto.CompactTextString(m) }
func (*MicroTX) ProtoMessage()    {}
func (*MicroTX) Descriptor() ([]byte, []int) {
	return fileDescriptor_microtransactionMessage_7c217386e9c71d87, []int{0}
}
func (m *MicroTX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MicroTX.Unmarshal(m, b)
}
func (m *MicroTX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MicroTX.Marshal(b, m, deterministic)
}
func (dst *MicroTX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MicroTX.Merge(dst, src)
}
func (m *MicroTX) XXX_Size() int {
	return xxx_messageInfo_MicroTX.Size(m)
}
func (m *MicroTX) XXX_DiscardUnknown() {
	xxx_messageInfo_MicroTX.DiscardUnknown(m)
}

var xxx_messageInfo_MicroTX proto.InternalMessageInfo

func (m *MicroTX) GetFromPubkey() string {
	if m != nil {
		return m.FromPubkey
	}
	return ""
}

func (m *MicroTX) GetFromPrivate() string {
	if m != nil {
		return m.FromPrivate
	}
	return ""
}

func (m *MicroTX) GetFromWif() string {
	if m != nil {
		return m.FromWif
	}
	return ""
}

func (m *MicroTX) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MicroTX) GetValueSatoshis() int64 {
	if m != nil {
		return m.ValueSatoshis
	}
	return 0
}

func (m *MicroTX) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MicroTX) GetChangeAddress() string {
	if m != nil {
		return m.ChangeAddress
	}
	return ""
}

func (m *MicroTX) GetWaitGuarantee() bool {
	if m != nil {
		return m.WaitGuarantee
	}
	return false
}

func (m *MicroTX) GetTosign() []string {
	if m != nil {
		return m.Tosign
	}
	return nil
}

func (m *MicroTX) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MicroTX) GetInputs() []*TXInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *MicroTX) GetOutputs() []*TXOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *MicroTX) GetFees() int32 {
	if m != nil {
		return m.Fees
	}
	return 0
}

func (m *MicroTX) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type MicrotransactionEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	// Hex-encoded public key from which you’re sending coins.
	FromPubkey string `protobuf:"bytes,2,opt,name=from_pubkey,json=fromPubkey,proto3" json:"from_pubkey,omitempty"`
	// Hex-encoded private key from which you’re sending coins.
	FromPrivate string `protobuf:"bytes,3,opt,name=from_private,json=fromPrivate,proto3" json:"from_private,omitempty"`
	// WIF-encoded private key from which you’re sending coins.
	FromWif string `protobuf:"bytes,4,opt,name=from_wif,json=fromWif,proto3" json:"from_wif,omitempty"`
	// The target address to which you’re sending coins.
	ToAddress string `protobuf:"bytes,5,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// Value you’re sending/you’ve sent in satoshis.
	ValueSatoshis int64 `protobuf:"varint,6,opt,name=value_satoshis,json=valueSatoshis,proto3" json:"value_satoshis,omitempty"`
	// Your Block API token
	Token string `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	// Optional Address Block will use to send back your change. If not set, defaults to the address from which the coins were originally sent. While not required, we recommend that you set a change address.
	ChangeAddress string `protobuf:"bytes,8,opt,name=change_address,json=changeAddress,proto3" json:"change_address,omitempty"`
	// Optional If not set, defaults to true, which means the API will wait for Block to guarantee the transaction, using our Confidence Factor. The guarantee usually takes around 8 seconds. If manually set to false, the Microtransaction endpoint will return as soon as the transaction is broadcast.
	WaitGuarantee bool `protobuf:"varint,9,opt,name=wait_guarantee,json=waitGuarantee,proto3" json:"wait_guarantee,omitempty"`
	// Optional Hex-encoded data for you to sign after initiating the microtransaction. Sent in reply to a microtransaction generated using from_pubkey/a public key.
	Tosign []string `protobuf:"bytes,10,rep,name=tosign,proto3" json:"tosign,omitempty"`
	// Optional Hex-encoded signatures for you to send back after having received (and signed) tosign.
	Signatures []string `protobuf:"bytes,11,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Optional Partial list of inputs that will be used with this transaction. Inputs themsleves are heavily pared down, see cURL sample. Only returned when using from_pubkey.
	Inputs []*TXInput `protobuf:"bytes,12,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Optional Partial list of outputs that will be used with this transaction. Outputs themselves are heavily pared down, see cURL sample. Only returned when using from_pubkey.
	Outputs []*TXOutput `protobuf:"bytes,13,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Optional Block’s optimally calculated fees for this MicroTX to guarantee swift 99% confirmation, only returned when using from_pubkey. Block pays these fees for the first 8,000 microtransactions, but like regular transactions, it is deducted from the source address thereafter.
	Fees int32 `protobuf:"varint,14,opt,name=fees,proto3" json:"fees,omitempty"`
	// Optional The hash of the finalized transaction, once sent.
	Hash                 string   `protobuf:"bytes,15,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MicrotransactionEndpointRequest) Reset()         { *m = MicrotransactionEndpointRequest{} }
func (m *MicrotransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*MicrotransactionEndpointRequest) ProtoMessage()    {}
func (*MicrotransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_microtransactionMessage_7c217386e9c71d87, []int{1}
}
func (m *MicrotransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MicrotransactionEndpointRequest.Unmarshal(m, b)
}
func (m *MicrotransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MicrotransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *MicrotransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MicrotransactionEndpointRequest.Merge(dst, src)
}
func (m *MicrotransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_MicrotransactionEndpointRequest.Size(m)
}
func (m *MicrotransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MicrotransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MicrotransactionEndpointRequest proto.InternalMessageInfo

func (m *MicrotransactionEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *MicrotransactionEndpointRequest) GetFromPubkey() string {
	if m != nil {
		return m.FromPubkey
	}
	return ""
}

func (m *MicrotransactionEndpointRequest) GetFromPrivate() string {
	if m != nil {
		return m.FromPrivate
	}
	return ""
}

func (m *MicrotransactionEndpointRequest) GetFromWif() string {
	if m != nil {
		return m.FromWif
	}
	return ""
}

func (m *MicrotransactionEndpointRequest) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *MicrotransactionEndpointRequest) GetValueSatoshis() int64 {
	if m != nil {
		return m.ValueSatoshis
	}
	return 0
}

func (m *MicrotransactionEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MicrotransactionEndpointRequest) GetChangeAddress() string {
	if m != nil {
		return m.ChangeAddress
	}
	return ""
}

func (m *MicrotransactionEndpointRequest) GetWaitGuarantee() bool {
	if m != nil {
		return m.WaitGuarantee
	}
	return false
}

func (m *MicrotransactionEndpointRequest) GetTosign() []string {
	if m != nil {
		return m.Tosign
	}
	return nil
}

func (m *MicrotransactionEndpointRequest) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MicrotransactionEndpointRequest) GetInputs() []*TXInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *MicrotransactionEndpointRequest) GetOutputs() []*TXOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *MicrotransactionEndpointRequest) GetFees() int32 {
	if m != nil {
		return m.Fees
	}
	return 0
}

func (m *MicrotransactionEndpointRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*MicroTX)(nil), "fairwaycorp.blockchainprotobuf.btc.MicroTX")
	proto.RegisterType((*MicrotransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.MicrotransactionEndpointRequest")
}

func init() {
	proto.RegisterFile("microtransactionMessage.proto", fileDescriptor_microtransactionMessage_7c217386e9c71d87)
}

var fileDescriptor_microtransactionMessage_7c217386e9c71d87 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0xe9, 0xa6, 0x6d, 0xda, 0xe9, 0x1f, 0x61, 0x14, 0x19, 0x85, 0x75, 0x63, 0x41, 0x08,
	0x68, 0x53, 0x58, 0x5f, 0x7c, 0x11, 0xa9, 0xa2, 0xe2, 0x43, 0x75, 0x19, 0x17, 0x5c, 0x7c, 0x29,
	0x93, 0xe9, 0x24, 0x19, 0xda, 0xce, 0xd4, 0x99, 0xc9, 0x86, 0xfd, 0xcc, 0x7e, 0x08, 0x25, 0x37,
	0xad, 0xbb, 0x14, 0x49, 0xfb, 0xb0, 0x4f, 0xb9, 0xf7, 0xdc, 0x7b, 0xce, 0x0d, 0xc9, 0x0f, 0x9d,
	0xae, 0x25, 0x37, 0xda, 0x19, 0xa6, 0x2c, 0xe3, 0x4e, 0x6a, 0x35, 0x13, 0xd6, 0xb2, 0x54, 0x44,
	0x1b, 0xa3, 0x9d, 0xc6, 0xa3, 0x84, 0x49, 0x53, 0xb0, 0x1b, 0xae, 0xcd, 0x26, 0x8a, 0x57, 0x9a,
	0x2f, 0x79, 0xc6, 0xa4, 0x82, 0x61, 0x9c, 0x27, 0x51, 0xec, 0xf8, 0xd3, 0x87, 0x5c, 0xaf, 0xd7,
	0x7b, 0xc6, 0xd1, 0x1f, 0x0f, 0xf9, 0xb3, 0x32, 0xfa, 0xf2, 0x0a, 0x9f, 0xa1, 0x5e, 0x62, 0xf4,
	0x7a, 0xbe, 0xc9, 0xe3, 0xa5, 0xb8, 0x21, 0x8d, 0xa0, 0x11, 0x76, 0x29, 0x2a, 0xa5, 0x0b, 0x50,
	0xf0, 0x73, 0xd4, 0xaf, 0x16, 0x8c, 0xbc, 0x66, 0x4e, 0x90, 0x13, 0xd8, 0x00, 0xd3, 0x45, 0x25,
	0xe1, 0x27, 0xa8, 0x03, 0x2b, 0x85, 0x4c, 0x88, 0x07, 0x63, 0xbf, 0xec, 0x7f, 0xc8, 0x04, 0x9f,
	0x22, 0xe4, 0xf4, 0x9c, 0x2d, 0x16, 0x46, 0x58, 0x4b, 0x9a, 0x30, 0xec, 0x3a, 0x3d, 0xad, 0x04,
	0xfc, 0x02, 0x0d, 0xaf, 0xd9, 0x2a, 0x17, 0x73, 0xcb, 0x9c, 0xb6, 0x99, 0xb4, 0xa4, 0x15, 0x34,
	0x42, 0x8f, 0x0e, 0x40, 0xfd, 0xbe, 0x15, 0xf1, 0x23, 0xd4, 0x72, 0x7a, 0x29, 0x14, 0x69, 0x43,
	0x40, 0xd5, 0x94, 0x66, 0x9e, 0x31, 0x95, 0x8a, 0x7f, 0xf9, 0x3e, 0x8c, 0x07, 0x95, 0x7a, 0xe7,
	0x46, 0xc1, 0xa4, 0x9b, 0xa7, 0x39, 0x33, 0x4c, 0x39, 0x21, 0x48, 0x27, 0x68, 0x84, 0x1d, 0x3a,
	0x28, 0xd5, 0xcf, 0x3b, 0x11, 0x3f, 0x46, 0x6d, 0xa7, 0xad, 0x4c, 0x15, 0xe9, 0x06, 0x5e, 0xd8,
	0xa5, 0xdb, 0x0e, 0x3f, 0x43, 0xa8, 0x7c, 0x32, 0x97, 0x1b, 0x61, 0x09, 0x82, 0xd9, 0x1d, 0x05,
	0x7f, 0x40, 0x6d, 0xa9, 0x36, 0xb9, 0xb3, 0xa4, 0x17, 0x78, 0x61, 0xef, 0xfc, 0x65, 0x74, 0xf8,
	0xb7, 0x44, 0x97, 0x57, 0x5f, 0x4a, 0x0f, 0xdd, 0x5a, 0xf1, 0x27, 0xe4, 0xeb, 0xdc, 0x41, 0x4a,
	0x1f, 0x52, 0x5e, 0x1d, 0x97, 0xf2, 0x0d, 0x4c, 0x74, 0x67, 0xc6, 0x18, 0x35, 0x13, 0x21, 0x2c,
	0x19, 0x04, 0x8d, 0xb0, 0x45, 0xa1, 0x2e, 0xb5, 0x8c, 0xd9, 0x8c, 0x0c, 0xe1, 0xe3, 0x40, 0x3d,
	0xfa, 0xdd, 0x44, 0x67, 0xb3, 0x3d, 0xb8, 0x3e, 0xaa, 0xc5, 0x46, 0x4b, 0xe5, 0xa8, 0xf8, 0x95,
	0x0b, 0xeb, 0x30, 0x45, 0xbe, 0x12, 0xae, 0xd0, 0x66, 0x09, 0x54, 0x0c, 0xcf, 0xdf, 0x1c, 0xf3,
	0x4e, 0x5f, 0x2b, 0xcb, 0x74, 0xb5, 0xd2, 0x85, 0x54, 0xe9, 0x74, 0x25, 0x99, 0xa5, 0xbb, 0xa0,
	0x7d, 0xda, 0x4e, 0x0e, 0xd2, 0xe6, 0xd5, 0xd3, 0xd6, 0xac, 0xa3, 0xad, 0x75, 0x98, 0xb6, 0x76,
	0x2d, 0x6d, 0x7e, 0x3d, 0x6d, 0x9d, 0xe3, 0x68, 0xeb, 0xd6, 0xd3, 0x86, 0x6a, 0x68, 0xeb, 0xd5,
	0xd0, 0xd6, 0xbf, 0x17, 0xda, 0x06, 0xf7, 0x41, 0xdb, 0xf0, 0x3f, 0xb4, 0x3d, 0xb8, 0xa5, 0xed,
	0xfd, 0xbb, 0x9f, 0x6f, 0x53, 0xe9, 0xb2, 0x3c, 0x8e, 0xb8, 0x5e, 0x4f, 0xb6, 0xa7, 0xc6, 0xe5,
	0xad, 0xc9, 0xed, 0xad, 0xf1, 0xee, 0xd8, 0x04, 0x0a, 0x3e, 0x4e, 0x85, 0x1a, 0xa7, 0x7a, 0x12,
	0x3b, 0x1e, 0xb7, 0x41, 0x7a, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x09, 0x95, 0x82, 0x7e, 0x11,
	0x05, 0x00, 0x00,
}
