// Code generated by protoc-gen-go. DO NOT EDIT.
// source: walletMessage.proto

package btc // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/btc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListWallets struct {
	WalletNames          []string `protobuf:"bytes,1,rep,name=wallet_names,json=walletNames,proto3" json:"wallet_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListWallets) Reset()         { *m = ListWallets{} }
func (m *ListWallets) String() string { return proto.CompactTextString(m) }
func (*ListWallets) ProtoMessage()    {}
func (*ListWallets) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{0}
}
func (m *ListWallets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWallets.Unmarshal(m, b)
}
func (m *ListWallets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWallets.Marshal(b, m, deterministic)
}
func (dst *ListWallets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWallets.Merge(dst, src)
}
func (m *ListWallets) XXX_Size() int {
	return xxx_messageInfo_ListWallets.Size(m)
}
func (m *ListWallets) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWallets.DiscardUnknown(m)
}

var xxx_messageInfo_ListWallets proto.InternalMessageInfo

func (m *ListWallets) GetWalletNames() []string {
	if m != nil {
		return m.WalletNames
	}
	return nil
}

type WalletAddressKeychain struct {
	// --- Wallet ---
	// User token associated with this wallet.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Name of the wallet.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// List of addresses associated with this wallet.
	Addresses []string `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// --- AddressKeychain ---
	// Standard address representation.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// Hex-encoded Public key.
	Public string `protobuf:"bytes,5,opt,name=public,proto3" json:"public,omitempty"`
	// Hex-encoded Private key.
	Private string `protobuf:"bytes,6,opt,name=private,proto3" json:"private,omitempty"`
	// Wallet import format, a common encoding for the private key.
	Wif string `protobuf:"bytes,7,opt,name=wif,proto3" json:"wif,omitempty"`
	// Optional Array of public keys to provide to generate a multisig address.
	Pubkeys []string `protobuf:"bytes,8,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	// Optional If generating a multisig address, the type of multisig script;typically “multisig-n-of-m”, where n and m are integers.
	ScriptType string `protobuf:"bytes,9,opt,name=script_type,json=scriptType,proto3" json:"script_type,omitempty"`
	// Optional If generating an OAP address, this represents the parent blockchain’s underlying address (the typical address listed above).
	OriginalAddress string `protobuf:"bytes,10,opt,name=original_address,json=originalAddress,proto3" json:"original_address,omitempty"`
	// Optional The OAP address, if generated using the Generate Asset Address Endpoint.
	OapAddress           string   `protobuf:"bytes,11,opt,name=oap_address,json=oapAddress,proto3" json:"oap_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletAddressKeychain) Reset()         { *m = WalletAddressKeychain{} }
func (m *WalletAddressKeychain) String() string { return proto.CompactTextString(m) }
func (*WalletAddressKeychain) ProtoMessage()    {}
func (*WalletAddressKeychain) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{1}
}
func (m *WalletAddressKeychain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletAddressKeychain.Unmarshal(m, b)
}
func (m *WalletAddressKeychain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletAddressKeychain.Marshal(b, m, deterministic)
}
func (dst *WalletAddressKeychain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletAddressKeychain.Merge(dst, src)
}
func (m *WalletAddressKeychain) XXX_Size() int {
	return xxx_messageInfo_WalletAddressKeychain.Size(m)
}
func (m *WalletAddressKeychain) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletAddressKeychain.DiscardUnknown(m)
}

var xxx_messageInfo_WalletAddressKeychain proto.InternalMessageInfo

func (m *WalletAddressKeychain) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *WalletAddressKeychain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WalletAddressKeychain) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *WalletAddressKeychain) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WalletAddressKeychain) GetPublic() string {
	if m != nil {
		return m.Public
	}
	return ""
}

func (m *WalletAddressKeychain) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *WalletAddressKeychain) GetWif() string {
	if m != nil {
		return m.Wif
	}
	return ""
}

func (m *WalletAddressKeychain) GetPubkeys() []string {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *WalletAddressKeychain) GetScriptType() string {
	if m != nil {
		return m.ScriptType
	}
	return ""
}

func (m *WalletAddressKeychain) GetOriginalAddress() string {
	if m != nil {
		return m.OriginalAddress
	}
	return ""
}

func (m *WalletAddressKeychain) GetOapAddress() string {
	if m != nil {
		return m.OapAddress
	}
	return ""
}

type CreateWalletEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Token                string               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Addresses            []string             `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateWalletEndpointRequest) Reset()         { *m = CreateWalletEndpointRequest{} }
func (m *CreateWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletEndpointRequest) ProtoMessage()    {}
func (*CreateWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{2}
}
func (m *CreateWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletEndpointRequest.Unmarshal(m, b)
}
func (m *CreateWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CreateWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletEndpointRequest.Merge(dst, src)
}
func (m *CreateWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletEndpointRequest.Size(m)
}
func (m *CreateWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletEndpointRequest proto.InternalMessageInfo

func (m *CreateWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *CreateWalletEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateWalletEndpointRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CreateWalletHDEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Token                string               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Chains               []*HDChain           `protobuf:"bytes,4,rep,name=chains,proto3" json:"chains,omitempty"`
	Hd                   bool                 `protobuf:"varint,5,opt,name=hd,proto3" json:"hd,omitempty"`
	ExtendedPublicKey    string               `protobuf:"bytes,6,opt,name=extended_public_key,json=extendedPublicKey,proto3" json:"extended_public_key,omitempty"`
	SubchainIndexes      []int32              `protobuf:"varint,7,rep,packed,name=subchain_indexes,json=subchainIndexes,proto3" json:"subchain_indexes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateWalletHDEndpointRequest) Reset()         { *m = CreateWalletHDEndpointRequest{} }
func (m *CreateWalletHDEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletHDEndpointRequest) ProtoMessage()    {}
func (*CreateWalletHDEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{3}
}
func (m *CreateWalletHDEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletHDEndpointRequest.Unmarshal(m, b)
}
func (m *CreateWalletHDEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletHDEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CreateWalletHDEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletHDEndpointRequest.Merge(dst, src)
}
func (m *CreateWalletHDEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletHDEndpointRequest.Size(m)
}
func (m *CreateWalletHDEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletHDEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletHDEndpointRequest proto.InternalMessageInfo

func (m *CreateWalletHDEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *CreateWalletHDEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateWalletHDEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateWalletHDEndpointRequest) GetChains() []*HDChain {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *CreateWalletHDEndpointRequest) GetHd() bool {
	if m != nil {
		return m.Hd
	}
	return false
}

func (m *CreateWalletHDEndpointRequest) GetExtendedPublicKey() string {
	if m != nil {
		return m.ExtendedPublicKey
	}
	return ""
}

func (m *CreateWalletHDEndpointRequest) GetSubchainIndexes() []int32 {
	if m != nil {
		return m.SubchainIndexes
	}
	return nil
}

type ListWalletsEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListWalletsEndpointRequest) Reset()         { *m = ListWalletsEndpointRequest{} }
func (m *ListWalletsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*ListWalletsEndpointRequest) ProtoMessage()    {}
func (*ListWalletsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{4}
}
func (m *ListWalletsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWalletsEndpointRequest.Unmarshal(m, b)
}
func (m *ListWalletsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWalletsEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *ListWalletsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWalletsEndpointRequest.Merge(dst, src)
}
func (m *ListWalletsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_ListWalletsEndpointRequest.Size(m)
}
func (m *ListWalletsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWalletsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWalletsEndpointRequest proto.InternalMessageInfo

func (m *ListWalletsEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

type GetWalletEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetWalletEndpointRequest) Reset()         { *m = GetWalletEndpointRequest{} }
func (m *GetWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletEndpointRequest) ProtoMessage()    {}
func (*GetWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{5}
}
func (m *GetWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletEndpointRequest.Unmarshal(m, b)
}
func (m *GetWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *GetWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletEndpointRequest.Merge(dst, src)
}
func (m *GetWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletEndpointRequest.Size(m)
}
func (m *GetWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletEndpointRequest proto.InternalMessageInfo

func (m *GetWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *GetWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddAddressesToWalletEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name    string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// If omitWalletAddresses is true, the response will omit address information (useful to speed up the API call for larger wallets).
	OmitWalletAddresses  bool     `protobuf:"varint,3,opt,name=omitWalletAddresses,proto3" json:"omitWalletAddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAddressesToWalletEndpointRequest) Reset()         { *m = AddAddressesToWalletEndpointRequest{} }
func (m *AddAddressesToWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*AddAddressesToWalletEndpointRequest) ProtoMessage()    {}
func (*AddAddressesToWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{6}
}
func (m *AddAddressesToWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAddressesToWalletEndpointRequest.Unmarshal(m, b)
}
func (m *AddAddressesToWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAddressesToWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *AddAddressesToWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAddressesToWalletEndpointRequest.Merge(dst, src)
}
func (m *AddAddressesToWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_AddAddressesToWalletEndpointRequest.Size(m)
}
func (m *AddAddressesToWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAddressesToWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAddressesToWalletEndpointRequest proto.InternalMessageInfo

func (m *AddAddressesToWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *AddAddressesToWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddAddressesToWalletEndpointRequest) GetOmitWalletAddresses() bool {
	if m != nil {
		return m.OmitWalletAddresses
	}
	return false
}

type GetWalletAddressesEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name    string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Returns only used addresses if set to true and only unused if false. Only valid on HD wallets.
	Used bool `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	// Returns only addresses with zero balance if set to true and only addresses with non-zero balance if false. Only valid on HD wallets.
	Zerobalance          bool     `protobuf:"varint,4,opt,name=zerobalance,proto3" json:"zerobalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletAddressesEndpointRequest) Reset()         { *m = GetWalletAddressesEndpointRequest{} }
func (m *GetWalletAddressesEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletAddressesEndpointRequest) ProtoMessage()    {}
func (*GetWalletAddressesEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{7}
}
func (m *GetWalletAddressesEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletAddressesEndpointRequest.Unmarshal(m, b)
}
func (m *GetWalletAddressesEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletAddressesEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *GetWalletAddressesEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletAddressesEndpointRequest.Merge(dst, src)
}
func (m *GetWalletAddressesEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletAddressesEndpointRequest.Size(m)
}
func (m *GetWalletAddressesEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletAddressesEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletAddressesEndpointRequest proto.InternalMessageInfo

func (m *GetWalletAddressesEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *GetWalletAddressesEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWalletAddressesEndpointRequest) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

func (m *GetWalletAddressesEndpointRequest) GetZerobalance() bool {
	if m != nil {
		return m.Zerobalance
	}
	return false
}

type RemoveAddressesFromWalletEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RemoveAddressesFromWalletEndpointRequest) Reset() {
	*m = RemoveAddressesFromWalletEndpointRequest{}
}
func (m *RemoveAddressesFromWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAddressesFromWalletEndpointRequest) ProtoMessage()    {}
func (*RemoveAddressesFromWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{8}
}
func (m *RemoveAddressesFromWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAddressesFromWalletEndpointRequest.Unmarshal(m, b)
}
func (m *RemoveAddressesFromWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAddressesFromWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveAddressesFromWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAddressesFromWalletEndpointRequest.Merge(dst, src)
}
func (m *RemoveAddressesFromWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAddressesFromWalletEndpointRequest.Size(m)
}
func (m *RemoveAddressesFromWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAddressesFromWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAddressesFromWalletEndpointRequest proto.InternalMessageInfo

func (m *RemoveAddressesFromWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *RemoveAddressesFromWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveAddressesFromWalletEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GenerateAdressInWalletEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenerateAdressInWalletEndpointRequest) Reset()         { *m = GenerateAdressInWalletEndpointRequest{} }
func (m *GenerateAdressInWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAdressInWalletEndpointRequest) ProtoMessage()    {}
func (*GenerateAdressInWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{9}
}
func (m *GenerateAdressInWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAdressInWalletEndpointRequest.Unmarshal(m, b)
}
func (m *GenerateAdressInWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAdressInWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateAdressInWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAdressInWalletEndpointRequest.Merge(dst, src)
}
func (m *GenerateAdressInWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAdressInWalletEndpointRequest.Size(m)
}
func (m *GenerateAdressInWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAdressInWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAdressInWalletEndpointRequest proto.InternalMessageInfo

func (m *GenerateAdressInWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *GenerateAdressInWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeriveAddressInWalletEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name    string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Number of addresses to derive. If not set, default is one address.
	Count int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// Derives address(es) on this specific subchain. If not set, address will be generated on the first chain in the HD wallet.
	SubchainIndex        int64    `protobuf:"varint,4,opt,name=subchain_index,json=subchainIndex,proto3" json:"subchain_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeriveAddressInWalletEndpointRequest) Reset()         { *m = DeriveAddressInWalletEndpointRequest{} }
func (m *DeriveAddressInWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeriveAddressInWalletEndpointRequest) ProtoMessage()    {}
func (*DeriveAddressInWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{10}
}
func (m *DeriveAddressInWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeriveAddressInWalletEndpointRequest.Unmarshal(m, b)
}
func (m *DeriveAddressInWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeriveAddressInWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *DeriveAddressInWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeriveAddressInWalletEndpointRequest.Merge(dst, src)
}
func (m *DeriveAddressInWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeriveAddressInWalletEndpointRequest.Size(m)
}
func (m *DeriveAddressInWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeriveAddressInWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeriveAddressInWalletEndpointRequest proto.InternalMessageInfo

func (m *DeriveAddressInWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *DeriveAddressInWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeriveAddressInWalletEndpointRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *DeriveAddressInWalletEndpointRequest) GetSubchainIndex() int64 {
	if m != nil {
		return m.SubchainIndex
	}
	return 0
}

type DeleteWalletEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.btc.NetworkAllowingAlias" json:"network,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteWalletEndpointRequest) Reset()         { *m = DeleteWalletEndpointRequest{} }
func (m *DeleteWalletEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteWalletEndpointRequest) ProtoMessage()    {}
func (*DeleteWalletEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletMessage_44e9d63716b6e29e, []int{11}
}
func (m *DeleteWalletEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWalletEndpointRequest.Unmarshal(m, b)
}
func (m *DeleteWalletEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWalletEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteWalletEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWalletEndpointRequest.Merge(dst, src)
}
func (m *DeleteWalletEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteWalletEndpointRequest.Size(m)
}
func (m *DeleteWalletEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWalletEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWalletEndpointRequest proto.InternalMessageInfo

func (m *DeleteWalletEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAINNET
}

func (m *DeleteWalletEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ListWallets)(nil), "fairwaycorp.blockchainprotobuf.btc.ListWallets")
	proto.RegisterType((*WalletAddressKeychain)(nil), "fairwaycorp.blockchainprotobuf.btc.WalletAddressKeychain")
	proto.RegisterType((*CreateWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.CreateWalletEndpointRequest")
	proto.RegisterType((*CreateWalletHDEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.CreateWalletHDEndpointRequest")
	proto.RegisterType((*ListWalletsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.ListWalletsEndpointRequest")
	proto.RegisterType((*GetWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GetWalletEndpointRequest")
	proto.RegisterType((*AddAddressesToWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.AddAddressesToWalletEndpointRequest")
	proto.RegisterType((*GetWalletAddressesEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GetWalletAddressesEndpointRequest")
	proto.RegisterType((*RemoveAddressesFromWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.RemoveAddressesFromWalletEndpointRequest")
	proto.RegisterType((*GenerateAdressInWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GenerateAdressInWalletEndpointRequest")
	proto.RegisterType((*DeriveAddressInWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.DeriveAddressInWalletEndpointRequest")
	proto.RegisterType((*DeleteWalletEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.DeleteWalletEndpointRequest")
}

func init() { proto.RegisterFile("walletMessage.proto", fileDescriptor_walletMessage_44e9d63716b6e29e) }

var fileDescriptor_walletMessage_44e9d63716b6e29e = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4f, 0x6f, 0xd3, 0x4a,
	0x10, 0x97, 0xf3, 0xb7, 0x99, 0xbc, 0xd7, 0xf6, 0x6d, 0xde, 0x7b, 0xb2, 0x5a, 0x10, 0xa9, 0xa1,
	0x52, 0x10, 0x4a, 0x52, 0x95, 0x0b, 0x17, 0x84, 0x42, 0x03, 0x6d, 0x55, 0xa8, 0x90, 0x55, 0x09,
	0x89, 0x4b, 0xb4, 0xb6, 0xa7, 0xc9, 0x2a, 0xce, 0xae, 0xf1, 0xae, 0x9b, 0x9a, 0x23, 0x12, 0x67,
	0xbe, 0x08, 0x5f, 0x80, 0x13, 0x42, 0xe2, 0x86, 0xf8, 0x4e, 0xc8, 0x6b, 0x3b, 0x4d, 0x50, 0x10,
	0x9c, 0x1a, 0x6e, 0x33, 0xbf, 0xf9, 0xeb, 0x99, 0x9f, 0x67, 0xa1, 0x31, 0xa5, 0xbe, 0x8f, 0xea,
	0x39, 0x4a, 0x49, 0x87, 0xd8, 0x09, 0x42, 0xa1, 0x04, 0xb1, 0xce, 0x29, 0x0b, 0xa7, 0x34, 0x76,
	0x45, 0x18, 0x74, 0x1c, 0x5f, 0xb8, 0x63, 0x77, 0x44, 0x19, 0xd7, 0x46, 0x27, 0x3a, 0xef, 0x38,
	0xca, 0xdd, 0x6a, 0xb8, 0x62, 0x32, 0x11, 0x7c, 0x21, 0xd0, 0xda, 0x83, 0xfa, 0x33, 0x26, 0xd5,
	0x4b, 0x9d, 0x53, 0x92, 0x1d, 0xf8, 0x2b, 0x4d, 0x3f, 0xe0, 0x74, 0x82, 0xd2, 0x34, 0x9a, 0xc5,
	0x56, 0xcd, 0xae, 0xa7, 0xd8, 0x69, 0x02, 0x59, 0x5f, 0x0a, 0xf0, 0x5f, 0xea, 0xde, 0xf3, 0xbc,
	0x10, 0xa5, 0x3c, 0xc1, 0x58, 0x17, 0x23, 0xff, 0x42, 0x59, 0x89, 0x31, 0x72, 0xd3, 0x68, 0x1a,
	0xad, 0x9a, 0x9d, 0x2a, 0x84, 0x40, 0x29, 0xc9, 0x65, 0x16, 0x34, 0xa8, 0x65, 0x72, 0x03, 0x6a,
	0x34, 0x0d, 0x46, 0x69, 0x16, 0x75, 0x8d, 0x2b, 0x80, 0x98, 0x50, 0xcd, 0x14, 0xb3, 0xa4, 0x83,
	0x72, 0x95, 0xfc, 0x0f, 0x95, 0x20, 0x72, 0x7c, 0xe6, 0x9a, 0x65, 0x6d, 0xc8, 0xb4, 0x24, 0x22,
	0x08, 0xd9, 0x05, 0x55, 0x68, 0x56, 0xd2, 0x88, 0x4c, 0x25, 0x9b, 0x50, 0x9c, 0xb2, 0x73, 0xb3,
	0xaa, 0xd1, 0x44, 0xd4, 0xbe, 0x91, 0x33, 0xc6, 0x58, 0x9a, 0x6b, 0xba, 0x72, 0xae, 0x92, 0x5b,
	0x50, 0x97, 0x6e, 0xc8, 0x02, 0x35, 0x50, 0x71, 0x80, 0x66, 0x4d, 0xc7, 0x40, 0x0a, 0x9d, 0xc5,
	0x01, 0x92, 0xbb, 0xb0, 0x29, 0x42, 0x36, 0x64, 0x9c, 0xfa, 0x83, 0xbc, 0x43, 0xd0, 0x5e, 0x1b,
	0x39, 0x9e, 0xcd, 0x24, 0xc9, 0x25, 0x68, 0x30, 0xf3, 0xaa, 0xa7, 0xb9, 0x04, 0x0d, 0x32, 0x07,
	0xeb, 0xa3, 0x01, 0xdb, 0x07, 0x21, 0x52, 0x85, 0xe9, 0x30, 0x9f, 0x70, 0x2f, 0x10, 0x8c, 0x2b,
	0x1b, 0x5f, 0x47, 0x28, 0x15, 0xb1, 0xa1, 0xca, 0x51, 0x4d, 0x45, 0x38, 0xd6, 0xe3, 0x5c, 0xdf,
	0x7f, 0xd0, 0xf9, 0xf5, 0x8e, 0x3b, 0xa7, 0x69, 0x48, 0xcf, 0xf7, 0xc5, 0x94, 0xf1, 0x61, 0xcf,
	0x67, 0x54, 0xda, 0x79, 0xa2, 0xab, 0x05, 0x15, 0x96, 0x2d, 0xa8, 0xf8, 0xb3, 0x05, 0x95, 0x7e,
	0x58, 0x90, 0xf5, 0xad, 0x00, 0x37, 0xe7, 0x7b, 0x3f, 0xea, 0xff, 0x59, 0xdd, 0x1f, 0x40, 0x45,
	0x27, 0x4f, 0x5b, 0xaf, 0xef, 0xdf, 0xfb, 0x9d, 0xe2, 0x47, 0xfd, 0x83, 0x04, 0xb3, 0xb3, 0x50,
	0xb2, 0x0e, 0x85, 0x91, 0xa7, 0x79, 0xb6, 0x66, 0x17, 0x46, 0x1e, 0xe9, 0x40, 0x03, 0x2f, 0x15,
	0x72, 0x0f, 0xbd, 0x41, 0x4a, 0xbb, 0xc1, 0x18, 0xe3, 0x8c, 0x6f, 0xff, 0xe4, 0xa6, 0x17, 0xda,
	0x72, 0x82, 0x71, 0x42, 0x16, 0x19, 0x39, 0x3a, 0xd9, 0x80, 0x71, 0x0f, 0x2f, 0x51, 0x9a, 0xd5,
	0x66, 0xb1, 0x55, 0xb6, 0x37, 0x72, 0xfc, 0x38, 0x85, 0xad, 0x00, 0xb6, 0xe6, 0x7e, 0xc2, 0x6b,
	0x98, 0xa5, 0xf5, 0xd6, 0x00, 0xf3, 0x10, 0xd5, 0xf5, 0x51, 0x6f, 0xc9, 0x15, 0xb0, 0x3e, 0x19,
	0x70, 0xbb, 0xe7, 0x79, 0xbd, 0x9c, 0x57, 0x67, 0x62, 0xa5, 0xfd, 0x90, 0x3d, 0x68, 0x88, 0x09,
	0x53, 0x0b, 0xc7, 0x4d, 0xdf, 0xa7, 0x84, 0x02, 0xcb, 0x4c, 0xd6, 0x67, 0x03, 0x76, 0x66, 0x63,
	0x9c, 0xc1, 0xab, 0xea, 0x9f, 0x40, 0x29, 0x92, 0xe8, 0x65, 0x0d, 0x6b, 0x99, 0x34, 0xa1, 0xfe,
	0x06, 0x43, 0xe1, 0x50, 0x9f, 0x72, 0x17, 0xf5, 0x3d, 0x5d, 0xb3, 0xe7, 0x21, 0xeb, 0x83, 0x01,
	0x2d, 0x1b, 0x27, 0xe2, 0x02, 0x67, 0x1f, 0xf0, 0x34, 0x14, 0x93, 0xd5, 0xae, 0x62, 0xee, 0x09,
	0x28, 0x2e, 0x3c, 0x01, 0xd6, 0x7b, 0x03, 0x76, 0x0f, 0x91, 0x63, 0x48, 0x15, 0xf6, 0x34, 0x74,
	0xcc, 0x57, 0x4b, 0xe3, 0xaf, 0x06, 0xdc, 0xe9, 0x63, 0xc8, 0x66, 0x03, 0x5c, 0x71, 0x43, 0xc9,
	0xa1, 0x74, 0x45, 0xc4, 0x95, 0x1e, 0x5d, 0xd9, 0x4e, 0x15, 0xb2, 0x0b, 0xeb, 0x8b, 0xf7, 0x48,
	0x93, 0xa1, 0x68, 0xff, 0xbd, 0x70, 0x8d, 0xac, 0x77, 0x06, 0x6c, 0xf7, 0xd1, 0xc7, 0xeb, 0x7c,
	0x97, 0x96, 0x7c, 0xc4, 0xe3, 0x47, 0xaf, 0x1e, 0x0e, 0x99, 0x1a, 0x45, 0x4e, 0xc7, 0x15, 0x93,
	0x6e, 0x56, 0xa2, 0x9d, 0xd4, 0xe8, 0x5e, 0xd5, 0x68, 0xe7, 0x45, 0xba, 0x5a, 0x70, 0xdb, 0x43,
	0xe4, 0xed, 0xa1, 0xe8, 0x3a, 0xca, 0x75, 0x2a, 0x1a, 0xba, 0xff, 0x3d, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x0b, 0xf1, 0x0b, 0x30, 0x09, 0x00, 0x00,
}
