// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webhooksService.proto

package btc // import "github.com/chainweaver/protobuf/protoc-gen-go/btc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebHooksServiceClient is the client API for WebHooksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebHooksServiceClient interface {
	CreateWebHookEndpoint(ctx context.Context, in *CreateWebHookEndpointRequest, opts ...grpc.CallOption) (*Event, error)
	ListWebHooksEndpoint(ctx context.Context, in *ListWebHooksEndpointRequest, opts ...grpc.CallOption) (*Events, error)
	WebHookIDEndpoint(ctx context.Context, in *WebHookIDEndpointRequest, opts ...grpc.CallOption) (*Event, error)
	DeleteWebHookEndpoint(ctx context.Context, in *DeleteWebHookEndpointRequest, opts ...grpc.CallOption) (*NullValue, error)
}

type webHooksServiceClient struct {
	cc *grpc.ClientConn
}

func NewWebHooksServiceClient(cc *grpc.ClientConn) WebHooksServiceClient {
	return &webHooksServiceClient{cc}
}

func (c *webHooksServiceClient) CreateWebHookEndpoint(ctx context.Context, in *CreateWebHookEndpointRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/chainweaver.protobuf.btc.WebHooksService/CreateWebHookEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webHooksServiceClient) ListWebHooksEndpoint(ctx context.Context, in *ListWebHooksEndpointRequest, opts ...grpc.CallOption) (*Events, error) {
	out := new(Events)
	err := c.cc.Invoke(ctx, "/chainweaver.protobuf.btc.WebHooksService/ListWebHooksEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webHooksServiceClient) WebHookIDEndpoint(ctx context.Context, in *WebHookIDEndpointRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/chainweaver.protobuf.btc.WebHooksService/WebHookIDEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webHooksServiceClient) DeleteWebHookEndpoint(ctx context.Context, in *DeleteWebHookEndpointRequest, opts ...grpc.CallOption) (*NullValue, error) {
	out := new(NullValue)
	err := c.cc.Invoke(ctx, "/chainweaver.protobuf.btc.WebHooksService/DeleteWebHookEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebHooksServiceServer is the server API for WebHooksService service.
type WebHooksServiceServer interface {
	CreateWebHookEndpoint(context.Context, *CreateWebHookEndpointRequest) (*Event, error)
	ListWebHooksEndpoint(context.Context, *ListWebHooksEndpointRequest) (*Events, error)
	WebHookIDEndpoint(context.Context, *WebHookIDEndpointRequest) (*Event, error)
	DeleteWebHookEndpoint(context.Context, *DeleteWebHookEndpointRequest) (*NullValue, error)
}

func RegisterWebHooksServiceServer(s *grpc.Server, srv WebHooksServiceServer) {
	s.RegisterService(&_WebHooksService_serviceDesc, srv)
}

func _WebHooksService_CreateWebHookEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebHookEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebHooksServiceServer).CreateWebHookEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainweaver.protobuf.btc.WebHooksService/CreateWebHookEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebHooksServiceServer).CreateWebHookEndpoint(ctx, req.(*CreateWebHookEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebHooksService_ListWebHooksEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebHooksEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebHooksServiceServer).ListWebHooksEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainweaver.protobuf.btc.WebHooksService/ListWebHooksEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebHooksServiceServer).ListWebHooksEndpoint(ctx, req.(*ListWebHooksEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebHooksService_WebHookIDEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebHookIDEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebHooksServiceServer).WebHookIDEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainweaver.protobuf.btc.WebHooksService/WebHookIDEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebHooksServiceServer).WebHookIDEndpoint(ctx, req.(*WebHookIDEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebHooksService_DeleteWebHookEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebHookEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebHooksServiceServer).DeleteWebHookEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chainweaver.protobuf.btc.WebHooksService/DeleteWebHookEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebHooksServiceServer).DeleteWebHookEndpoint(ctx, req.(*DeleteWebHookEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebHooksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chainweaver.protobuf.btc.WebHooksService",
	HandlerType: (*WebHooksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWebHookEndpoint",
			Handler:    _WebHooksService_CreateWebHookEndpoint_Handler,
		},
		{
			MethodName: "ListWebHooksEndpoint",
			Handler:    _WebHooksService_ListWebHooksEndpoint_Handler,
		},
		{
			MethodName: "WebHookIDEndpoint",
			Handler:    _WebHooksService_WebHookIDEndpoint_Handler,
		},
		{
			MethodName: "DeleteWebHookEndpoint",
			Handler:    _WebHooksService_DeleteWebHookEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webhooksService.proto",
}

func init() {
	proto.RegisterFile("webhooksService.proto", fileDescriptor_webhooksService_04cab6c59a0f1a45)
}

var fileDescriptor_webhooksService_04cab6c59a0f1a45 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x89, 0x88, 0x43, 0x16, 0xf1, 0x6c, 0x45, 0x43, 0xa1, 0x25, 0x2e, 0x52, 0x68, 0x0e,
	0x5b, 0x74, 0x70, 0xd4, 0x16, 0x14, 0xd4, 0x41, 0x41, 0xc1, 0xed, 0xee, 0xfa, 0xbc, 0x1e, 0x4d,
	0xef, 0xd5, 0xdc, 0xa5, 0x1d, 0x4a, 0x17, 0x77, 0x07, 0x75, 0xf7, 0x4b, 0xf9, 0x15, 0xdc, 0xfc,
	0x12, 0x62, 0x9a, 0x94, 0x8a, 0x09, 0xd5, 0x2d, 0xbc, 0xfc, 0xff, 0xbf, 0xfb, 0xdd, 0x3d, 0xb7,
	0x3c, 0x06, 0xde, 0x43, 0xec, 0x9b, 0x6b, 0x88, 0x46, 0x4a, 0x40, 0x30, 0x8c, 0xd0, 0x22, 0xd9,
	0x16, 0x3d, 0xa6, 0xf4, 0x18, 0xd8, 0x08, 0xa2, 0xd9, 0x88, 0xc7, 0xf7, 0x01, 0xb7, 0xc2, 0xab,
	0x48, 0x44, 0x19, 0x02, 0x65, 0x43, 0x45, 0x99, 0xd6, 0x68, 0x99, 0x55, 0xa8, 0xcd, 0x2c, 0xe4,
	0xcd, 0x71, 0x17, 0x60, 0x0c, 0x93, 0x29, 0xce, 0xdb, 0x14, 0x38, 0x18, 0xa0, 0xfe, 0x31, 0x6c,
	0x7e, 0xae, 0xba, 0xeb, 0xb7, 0xc0, 0x4f, 0x17, 0x4e, 0x27, 0xcf, 0x8e, 0x5b, 0x3e, 0x89, 0x80,
	0x59, 0x48, 0xff, 0x74, 0x74, 0x77, 0x88, 0x4a, 0x5b, 0x72, 0x18, 0x14, 0x29, 0x05, 0xb9, 0x85,
	0x2b, 0x78, 0x88, 0xc1, 0x58, 0xaf, 0x5a, 0xdc, 0xeb, 0x8c, 0x40, 0x5b, 0xbf, 0xfa, 0xf8, 0xfe,
	0xf1, 0xba, 0xb2, 0xe3, 0x97, 0x28, 0xb7, 0x82, 0x4e, 0x34, 0xd8, 0x31, 0x46, 0xfd, 0x29, 0x4d,
	0xae, 0x71, 0xe4, 0xd4, 0xc9, 0x93, 0xe3, 0x96, 0xce, 0x95, 0xb1, 0x99, 0xeb, 0x5c, 0xe9, 0xa0,
	0x18, 0x9d, 0x97, 0xcf, 0x8c, 0x6a, 0x4b, 0x8c, 0x8c, 0x5f, 0x49, 0x94, 0xb6, 0x48, 0xae, 0x12,
	0x79, 0x71, 0xdc, 0x8d, 0x94, 0x7d, 0xd6, 0x9e, 0xcb, 0x34, 0x8b, 0xa9, 0xbf, 0xc2, 0x7f, 0x7e,
	0x9b, 0xbd, 0x44, 0xc4, 0x27, 0xb5, 0x3c, 0x11, 0x3a, 0x49, 0x97, 0xad, 0xba, 0x53, 0xf2, 0xe6,
	0xb8, 0xe5, 0x36, 0x84, 0xf0, 0xaf, 0xc5, 0xe5, 0x16, 0x32, 0xb9, 0xdd, 0xe2, 0xde, 0x65, 0x1c,
	0x86, 0x37, 0x2c, 0x8c, 0x21, 0x13, 0xac, 0x2f, 0x15, 0x3c, 0x6e, 0xdd, 0xed, 0x4b, 0x65, 0x7b,
	0x31, 0x0f, 0x04, 0x0e, 0xe8, 0x02, 0x9a, 0x66, 0xe8, 0xd9, 0x87, 0x68, 0x48, 0xd0, 0x0d, 0x89,
	0xdf, 0x40, 0xbe, 0x96, 0x8c, 0x5a, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x49, 0x20, 0x0a, 0x17,
	0x26, 0x03, 0x00, 0x00,
}
