// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressService_Eth.proto

package eth // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/eth"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddressServiceClient is the client API for AddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressServiceClient interface {
	BalanceAddressEndpoint(ctx context.Context, in *BalanceAddressEndpointRequest, opts ...grpc.CallOption) (*Address, error)
	AddressEndpoint(ctx context.Context, in *AddressEndpointRequest, opts ...grpc.CallOption) (*Address, error)
	GenerateAddressEndpoint(ctx context.Context, in *GenerateAddressEndpointRequest, opts ...grpc.CallOption) (*AddressKeychain, error)
}

type addressServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressServiceClient(cc *grpc.ClientConn) AddressServiceClient {
	return &addressServiceClient{cc}
}

func (c *addressServiceClient) BalanceAddressEndpoint(ctx context.Context, in *BalanceAddressEndpointRequest, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.eth.AddressService/BalanceAddressEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) AddressEndpoint(ctx context.Context, in *AddressEndpointRequest, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.eth.AddressService/AddressEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) GenerateAddressEndpoint(ctx context.Context, in *GenerateAddressEndpointRequest, opts ...grpc.CallOption) (*AddressKeychain, error) {
	out := new(AddressKeychain)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.eth.AddressService/GenerateAddressEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServiceServer is the server API for AddressService service.
type AddressServiceServer interface {
	BalanceAddressEndpoint(context.Context, *BalanceAddressEndpointRequest) (*Address, error)
	AddressEndpoint(context.Context, *AddressEndpointRequest) (*Address, error)
	GenerateAddressEndpoint(context.Context, *GenerateAddressEndpointRequest) (*AddressKeychain, error)
}

func RegisterAddressServiceServer(s *grpc.Server, srv AddressServiceServer) {
	s.RegisterService(&_AddressService_serviceDesc, srv)
}

func _AddressService_BalanceAddressEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceAddressEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).BalanceAddressEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.eth.AddressService/BalanceAddressEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).BalanceAddressEndpoint(ctx, req.(*BalanceAddressEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_AddressEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).AddressEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.eth.AddressService/AddressEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).AddressEndpoint(ctx, req.(*AddressEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_GenerateAddressEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAddressEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).GenerateAddressEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.eth.AddressService/GenerateAddressEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).GenerateAddressEndpoint(ctx, req.(*GenerateAddressEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fairwaycorp.blockchainprotobuf.eth.AddressService",
	HandlerType: (*AddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BalanceAddressEndpoint",
			Handler:    _AddressService_BalanceAddressEndpoint_Handler,
		},
		{
			MethodName: "AddressEndpoint",
			Handler:    _AddressService_AddressEndpoint_Handler,
		},
		{
			MethodName: "GenerateAddressEndpoint",
			Handler:    _AddressService_GenerateAddressEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressService_Eth.proto",
}

func init() {
	proto.RegisterFile("addressService_Eth.proto", fileDescriptor_addressService_Eth_8502590320793476)
}

var fileDescriptor_addressService_Eth_8502590320793476 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0x4f, 0x4a, 0x33, 0x31,
	0x18, 0xc6, 0x99, 0x8f, 0x0f, 0x17, 0xb3, 0x50, 0x88, 0x60, 0xcb, 0xe0, 0x1f, 0x18, 0x50, 0x44,
	0x99, 0x04, 0xec, 0xae, 0x20, 0xd2, 0x42, 0x71, 0x21, 0x6e, 0x74, 0xe7, 0x46, 0x32, 0xe9, 0xdb,
	0x4c, 0x68, 0x9b, 0x77, 0x4c, 0x52, 0x4b, 0x29, 0xdd, 0x78, 0x05, 0x4f, 0x20, 0x78, 0x02, 0x57,
	0xde, 0xc3, 0x2b, 0x78, 0x10, 0x69, 0x3a, 0xa5, 0x6a, 0x2b, 0xb6, 0xb8, 0x1b, 0xe6, 0xe1, 0x79,
	0x7e, 0xbf, 0x37, 0x61, 0x99, 0x37, 0x9b, 0x06, 0xac, 0xbd, 0x06, 0x73, 0xaf, 0x04, 0xdc, 0x36,
	0x5c, 0x46, 0x73, 0x83, 0x0e, 0x49, 0xdc, 0xe2, 0xca, 0xf4, 0xf9, 0x40, 0xa0, 0xc9, 0x69, 0xda,
	0x41, 0xd1, 0x16, 0x19, 0x57, 0xda, 0x87, 0x69, 0xaf, 0x45, 0xc1, 0x65, 0xd1, 0xb6, 0x44, 0x94,
	0x1d, 0x60, 0x3c, 0x57, 0x8c, 0x6b, 0x8d, 0x8e, 0x3b, 0x85, 0xda, 0x4e, 0x16, 0xa2, 0xe9, 0xf6,
	0x25, 0x58, 0xcb, 0xe5, 0xa7, 0xed, 0xa8, 0x24, 0xb0, 0xdb, 0x45, 0x3d, 0x17, 0x9c, 0x3c, 0xff,
	0x0f, 0xd7, 0x6b, 0x5f, 0x8c, 0xc8, 0x6b, 0x10, 0x6e, 0xd5, 0x79, 0x87, 0x6b, 0x01, 0x45, 0xd2,
	0xd0, 0xcd, 0x1c, 0x95, 0x76, 0xa4, 0x46, 0x7f, 0x77, 0xa4, 0x8b, 0xbb, 0x57, 0x70, 0xd7, 0x03,
	0xeb, 0xa2, 0xe3, 0x65, 0x26, 0x8a, 0x6e, 0x4c, 0x1f, 0xde, 0xde, 0x1f, 0xff, 0x1d, 0x92, 0x03,
	0x06, 0x2e, 0x63, 0x43, 0x0d, 0xae, 0x8f, 0xa6, 0x3d, 0x62, 0xe3, 0x3b, 0x2d, 0x1b, 0x16, 0xe7,
	0x8e, 0x58, 0x3a, 0x41, 0x92, 0xa7, 0x20, 0xdc, 0xf8, 0xee, 0x5c, 0x5d, 0x01, 0xf8, 0x27, 0xd9,
	0x7d, 0x2f, 0xbb, 0x47, 0x76, 0x16, 0xc8, 0xce, 0x5c, 0xc9, 0x4b, 0x10, 0x96, 0xce, 0x41, 0x83,
	0xe1, 0x6e, 0xee, 0x7d, 0xeb, 0xcb, 0xf0, 0x7e, 0x28, 0x4f, 0x9d, 0x2b, 0x2b, 0x38, 0x5f, 0xc0,
	0xc0, 0x67, 0xf1, 0xae, 0x77, 0x2f, 0xc7, 0x9b, 0x0b, 0xdc, 0xab, 0xc1, 0x51, 0xfd, 0xec, 0xe6,
	0x54, 0x2a, 0x97, 0xf5, 0x52, 0x2a, 0xb0, 0xcb, 0x0a, 0x40, 0x32, 0x26, 0xb0, 0x19, 0x21, 0x99,
	0x22, 0x98, 0xff, 0x10, 0x89, 0x04, 0x9d, 0x48, 0x1c, 0x4f, 0xa6, 0x6b, 0xfe, 0x57, 0xe5, 0x23,
	0x00, 0x00, 0xff, 0xff, 0x31, 0x36, 0x5b, 0xf4, 0xff, 0x02, 0x00, 0x00,
}
