// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractMessage_Eth.proto

package eth // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/eth"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateContractEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	// Solidity code of this contract; required when creating a contract. In responses, only returned with contracts initially compiled by BlockCypher.
	Solidity string `protobuf:"bytes,2,opt,name=solidity,proto3" json:"solidity,omitempty"`
	// Parameters for either contract creation or method execution.
	Params []string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	// Named contract(s) to publish; necessary to specify when first creating a contract.
	Publish []string `protobuf:"bytes,4,rep,name=publish,proto3" json:"publish,omitempty"`
	// Private key associated with a funded Ethereum external account used to publish a contract or execute a method.
	Private string `protobuf:"bytes,5,opt,name=private,proto3" json:"private,omitempty"`
	// Maximum amount of gas to use in contract creation or method execution.
	GasLimit int32 `protobuf:"varint,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// Amount (in wei) to transfer; can be used when creating a contract or calling a method.
	Value int32 `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	// Name of contract as published.
	Name string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// Hex-encoded binary compilation of this contract.
	Bin string `protobuf:"bytes,9,opt,name=bin,proto3" json:"bin,omitempty"`
	// JSON-encoded ABI. Only returned with contracts initially compiled by BlockCypher.
	Abi string `protobuf:"bytes,10,opt,name=abi,proto3" json:"abi,omitempty"`
	// Hex-encoded address of this contract.
	Address string `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	// Timestamp when this contract was confirmed in the Ethereum blockchain.
	Created string `protobuf:"bytes,12,opt,name=created,proto3" json:"created,omitempty"`
	// Hex-encoded transaction hash that created this contract.
	CreationTxHash string `protobuf:"bytes,13,opt,name=creation_tx_hash,json=creationTxHash,proto3" json:"creation_tx_hash,omitempty"`
	// If this is a response from a calling a contract method, this array of results may appear if the method returns any.
	Results              []string `protobuf:"bytes,14,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContractEndpointRequest) Reset()         { *m = CreateContractEndpointRequest{} }
func (m *CreateContractEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContractEndpointRequest) ProtoMessage()    {}
func (*CreateContractEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contractMessage_Eth_02df266c902aee70, []int{0}
}
func (m *CreateContractEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContractEndpointRequest.Unmarshal(m, b)
}
func (m *CreateContractEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContractEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContractEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContractEndpointRequest.Merge(dst, src)
}
func (m *CreateContractEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContractEndpointRequest.Size(m)
}
func (m *CreateContractEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContractEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContractEndpointRequest proto.InternalMessageInfo

func (m *CreateContractEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *CreateContractEndpointRequest) GetSolidity() string {
	if m != nil {
		return m.Solidity
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *CreateContractEndpointRequest) GetPublish() []string {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *CreateContractEndpointRequest) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetGasLimit() int32 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CreateContractEndpointRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CreateContractEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetBin() string {
	if m != nil {
		return m.Bin
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetCreationTxHash() string {
	if m != nil {
		return m.CreationTxHash
	}
	return ""
}

func (m *CreateContractEndpointRequest) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

type ContractAddressEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	QueryAddress         string               `protobuf:"bytes,2,opt,name=query_address,json=queryAddress,proto3" json:"query_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ContractAddressEndpointRequest) Reset()         { *m = ContractAddressEndpointRequest{} }
func (m *ContractAddressEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*ContractAddressEndpointRequest) ProtoMessage()    {}
func (*ContractAddressEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contractMessage_Eth_02df266c902aee70, []int{1}
}
func (m *ContractAddressEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractAddressEndpointRequest.Unmarshal(m, b)
}
func (m *ContractAddressEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractAddressEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *ContractAddressEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractAddressEndpointRequest.Merge(dst, src)
}
func (m *ContractAddressEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_ContractAddressEndpointRequest.Size(m)
}
func (m *ContractAddressEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractAddressEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContractAddressEndpointRequest proto.InternalMessageInfo

func (m *ContractAddressEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *ContractAddressEndpointRequest) GetQueryAddress() string {
	if m != nil {
		return m.QueryAddress
	}
	return ""
}

type CallContractMethodEndpointRequest struct {
	Network      NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	QueryAddress string               `protobuf:"bytes,2,opt,name=query_address,json=queryAddress,proto3" json:"query_address,omitempty"`
	Method       string               `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// Solidity code of this contract; required when creating a contract. In responses, only returned with contracts initially compiled by BlockCypher.
	Solidity string `protobuf:"bytes,4,opt,name=solidity,proto3" json:"solidity,omitempty"`
	// Parameters for either contract creation or method execution.
	Params []string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	// Named contract(s) to publish; necessary to specify when first creating a contract.
	Publish []string `protobuf:"bytes,6,rep,name=publish,proto3" json:"publish,omitempty"`
	// Private key associated with a funded Ethereum external account used to publish a contract or execute a method.
	Private string `protobuf:"bytes,7,opt,name=private,proto3" json:"private,omitempty"`
	// Maximum amount of gas to use in contract creation or method execution.
	GasLimit int32 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// Amount (in wei) to transfer; can be used when creating a contract or calling a method.
	Value int32 `protobuf:"varint,9,opt,name=value,proto3" json:"value,omitempty"`
	// Name of contract as published.
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	// Hex-encoded binary compilation of this contract.
	Bin string `protobuf:"bytes,11,opt,name=bin,proto3" json:"bin,omitempty"`
	// JSON-encoded ABI. Only returned with contracts initially compiled by BlockCypher.
	Abi string `protobuf:"bytes,12,opt,name=abi,proto3" json:"abi,omitempty"`
	// Hex-encoded address of this contract.
	Address string `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	// Timestamp when this contract was confirmed in the Ethereum blockchain.
	Created string `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	// Hex-encoded transaction hash that created this contract.
	CreationTxHash string `protobuf:"bytes,15,opt,name=creation_tx_hash,json=creationTxHash,proto3" json:"creation_tx_hash,omitempty"`
	// If this is a response from a calling a contract method, this array of results may appear if the method returns any.
	Results              []string `protobuf:"bytes,16,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallContractMethodEndpointRequest) Reset()         { *m = CallContractMethodEndpointRequest{} }
func (m *CallContractMethodEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CallContractMethodEndpointRequest) ProtoMessage()    {}
func (*CallContractMethodEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contractMessage_Eth_02df266c902aee70, []int{2}
}
func (m *CallContractMethodEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallContractMethodEndpointRequest.Unmarshal(m, b)
}
func (m *CallContractMethodEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallContractMethodEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CallContractMethodEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallContractMethodEndpointRequest.Merge(dst, src)
}
func (m *CallContractMethodEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CallContractMethodEndpointRequest.Size(m)
}
func (m *CallContractMethodEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallContractMethodEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallContractMethodEndpointRequest proto.InternalMessageInfo

func (m *CallContractMethodEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *CallContractMethodEndpointRequest) GetQueryAddress() string {
	if m != nil {
		return m.QueryAddress
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetSolidity() string {
	if m != nil {
		return m.Solidity
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *CallContractMethodEndpointRequest) GetPublish() []string {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *CallContractMethodEndpointRequest) GetPrivate() string {
	if m != nil {
		return m.Private
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetGasLimit() int32 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CallContractMethodEndpointRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CallContractMethodEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetBin() string {
	if m != nil {
		return m.Bin
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetAbi() string {
	if m != nil {
		return m.Abi
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetCreationTxHash() string {
	if m != nil {
		return m.CreationTxHash
	}
	return ""
}

func (m *CallContractMethodEndpointRequest) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

type Contracts struct {
	Contract             []*Contract `protobuf:"bytes,1,rep,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Contracts) Reset()         { *m = Contracts{} }
func (m *Contracts) String() string { return proto.CompactTextString(m) }
func (*Contracts) ProtoMessage()    {}
func (*Contracts) Descriptor() ([]byte, []int) {
	return fileDescriptor_contractMessage_Eth_02df266c902aee70, []int{3}
}
func (m *Contracts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contracts.Unmarshal(m, b)
}
func (m *Contracts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contracts.Marshal(b, m, deterministic)
}
func (dst *Contracts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contracts.Merge(dst, src)
}
func (m *Contracts) XXX_Size() int {
	return xxx_messageInfo_Contracts.Size(m)
}
func (m *Contracts) XXX_DiscardUnknown() {
	xxx_messageInfo_Contracts.DiscardUnknown(m)
}

var xxx_messageInfo_Contracts proto.InternalMessageInfo

func (m *Contracts) GetContract() []*Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateContractEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.CreateContractEndpointRequest")
	proto.RegisterType((*ContractAddressEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.ContractAddressEndpointRequest")
	proto.RegisterType((*CallContractMethodEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.CallContractMethodEndpointRequest")
	proto.RegisterType((*Contracts)(nil), "fairwaycorp.blockchainprotobuf.eth.Contracts")
}

func init() {
	proto.RegisterFile("contractMessage_Eth.proto", fileDescriptor_contractMessage_Eth_02df266c902aee70)
}

var fileDescriptor_contractMessage_Eth_02df266c902aee70 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x15, 0x32, 0xfd, 0x89, 0xfb, 0x43, 0x65, 0x21, 0x30, 0x83, 0x40, 0xa5, 0x6c, 0xb2,
	0xa0, 0xa9, 0x34, 0x6c, 0xd8, 0x20, 0x54, 0xaa, 0x91, 0x66, 0x01, 0x2c, 0x22, 0xd8, 0xb0, 0xa9,
	0x6e, 0x12, 0x4f, 0x62, 0x8d, 0x63, 0x77, 0x6c, 0x67, 0x3a, 0x7d, 0x14, 0x5e, 0x86, 0x57, 0x03,
	0xc5, 0x49, 0x8a, 0x46, 0x9d, 0x50, 0x56, 0x88, 0xdd, 0x3d, 0xf7, 0xd4, 0xc7, 0xd7, 0xbd, 0x9f,
	0x82, 0x9e, 0xc6, 0x52, 0x18, 0x05, 0xb1, 0xf9, 0x44, 0xb5, 0x86, 0x94, 0xae, 0xcf, 0x4d, 0x16,
	0x6c, 0x94, 0x34, 0x12, 0xcf, 0x2e, 0x81, 0xa9, 0x2d, 0xec, 0x62, 0xa9, 0x36, 0x41, 0xc4, 0x65,
	0x7c, 0x15, 0x67, 0xc0, 0x84, 0x35, 0xa3, 0xe2, 0x32, 0xa0, 0x26, 0x3b, 0x7d, 0x12, 0xcb, 0x3c,
	0x97, 0xe2, 0xe0, 0xf0, 0xec, 0x87, 0x8b, 0x9e, 0xaf, 0x14, 0x05, 0x43, 0x57, 0xf5, 0x05, 0xe7,
	0x22, 0xd9, 0x48, 0x26, 0x4c, 0x48, 0xaf, 0x0b, 0xaa, 0x0d, 0x0e, 0x51, 0x4f, 0x50, 0xb3, 0x95,
	0xea, 0x8a, 0x38, 0x53, 0xc7, 0x1f, 0x9f, 0xbd, 0x0d, 0x8e, 0x5f, 0x18, 0x7c, 0xae, 0x8e, 0x2c,
	0x39, 0x97, 0x5b, 0x26, 0xd2, 0x25, 0x67, 0xa0, 0xc3, 0x26, 0x08, 0x9f, 0xa2, 0xbe, 0x96, 0x9c,
	0x25, 0xcc, 0xec, 0xc8, 0x83, 0xa9, 0xe3, 0x7b, 0xe1, 0x5e, 0xe3, 0xc7, 0xa8, 0xbb, 0x01, 0x05,
	0xb9, 0x26, 0xee, 0xd4, 0xf5, 0xbd, 0xb0, 0x56, 0x98, 0xa0, 0xde, 0xa6, 0x88, 0x38, 0xd3, 0x19,
	0x39, 0xb1, 0x46, 0x23, 0xad, 0xa3, 0xd8, 0x0d, 0x18, 0x4a, 0x3a, 0x36, 0xac, 0x91, 0xf8, 0x19,
	0xf2, 0x52, 0xd0, 0x6b, 0xce, 0x72, 0x66, 0x48, 0x77, 0xea, 0xf8, 0x9d, 0xb0, 0x9f, 0x82, 0xfe,
	0x58, 0x6a, 0xfc, 0x08, 0x75, 0x6e, 0x80, 0x17, 0x94, 0xf4, 0xac, 0x51, 0x09, 0x8c, 0xd1, 0x89,
	0x80, 0x9c, 0x92, 0xbe, 0x4d, 0xb2, 0x35, 0x9e, 0x20, 0x37, 0x62, 0x82, 0x78, 0xb6, 0x55, 0x96,
	0x65, 0x07, 0x22, 0x46, 0x50, 0xd5, 0x81, 0x88, 0x95, 0x43, 0x40, 0x92, 0x28, 0xaa, 0x35, 0x19,
	0x54, 0x43, 0xd4, 0xb2, 0x74, 0x62, 0xfb, 0x0f, 0x27, 0x64, 0x58, 0x39, 0xb5, 0xc4, 0x3e, 0x9a,
	0xd8, 0x92, 0x49, 0xb1, 0x36, 0xb7, 0xeb, 0x0c, 0x74, 0x46, 0x46, 0xf6, 0x27, 0xe3, 0xa6, 0xff,
	0xe5, 0xf6, 0x02, 0xaa, 0x27, 0x2a, 0xaa, 0x0b, 0x6e, 0x34, 0x19, 0x57, 0x8f, 0xaf, 0xe5, 0xec,
	0xbb, 0x83, 0x5e, 0x34, 0xab, 0x5b, 0x56, 0x37, 0xfe, 0x8b, 0x0d, 0xbe, 0x42, 0xa3, 0xeb, 0x82,
	0xaa, 0xdd, 0xba, 0x79, 0x74, 0xb5, 0xc6, 0xa1, 0x6d, 0xd6, 0x73, 0xcc, 0x7e, 0xba, 0xe8, 0xe5,
	0x0a, 0x38, 0x5f, 0xed, 0xd9, 0x35, 0x99, 0x4c, 0xfe, 0x97, 0xf1, 0x4a, 0xd2, 0x72, 0x3b, 0x11,
	0x71, 0xad, 0x5b, 0xab, 0x3b, 0x74, 0x9e, 0xb4, 0xd2, 0xd9, 0x69, 0xa3, 0xb3, 0xdb, 0x4a, 0x67,
	0xef, 0x0f, 0x74, 0xf6, 0xdb, 0xe8, 0xf4, 0xee, 0xa3, 0x13, 0x1d, 0xd2, 0x39, 0x38, 0xa0, 0x73,
	0x78, 0x2f, 0x9d, 0xa3, 0x56, 0x3a, 0xc7, 0xc7, 0xe9, 0x7c, 0x78, 0x8c, 0xce, 0xc9, 0x5d, 0x3a,
	0xbf, 0x22, 0xaf, 0x59, 0xbe, 0xc6, 0x17, 0xa8, 0xdf, 0x7c, 0xc5, 0x88, 0x33, 0x75, 0xfd, 0xc1,
	0xd9, 0xeb, 0xbf, 0xd9, 0x74, 0x13, 0x10, 0xee, 0x4f, 0x7f, 0x78, 0xff, 0xed, 0x5d, 0xca, 0x4c,
	0x56, 0x44, 0x41, 0x2c, 0xf3, 0x45, 0x9d, 0x31, 0x2f, 0x43, 0x16, 0xbf, 0x43, 0xe6, 0x4d, 0xca,
	0xc2, 0x16, 0xf1, 0x3c, 0xa5, 0x62, 0x9e, 0xca, 0x05, 0x35, 0x59, 0xd4, 0xb5, 0xad, 0x37, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xff, 0x09, 0xbd, 0xf4, 0x57, 0x05, 0x00, 0x00,
}
