// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contractService_Eth.proto

package eth // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/eth"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContractServiceClient is the client API for ContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContractServiceClient interface {
	CreateContractEndpoint(ctx context.Context, in *CreateContractEndpointRequest, opts ...grpc.CallOption) (*Contracts, error)
	GetContractAddressEndpoint(ctx context.Context, in *GetContractAddressEndpointRequest, opts ...grpc.CallOption) (*Contract, error)
	CallContractMethodEndpoint(ctx context.Context, in *CallContractMethodEndpointRequest, opts ...grpc.CallOption) (*Contract, error)
}

type contractServiceClient struct {
	cc *grpc.ClientConn
}

func NewContractServiceClient(cc *grpc.ClientConn) ContractServiceClient {
	return &contractServiceClient{cc}
}

func (c *contractServiceClient) CreateContractEndpoint(ctx context.Context, in *CreateContractEndpointRequest, opts ...grpc.CallOption) (*Contracts, error) {
	out := new(Contracts)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.eth.ContractService/CreateContractEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) GetContractAddressEndpoint(ctx context.Context, in *GetContractAddressEndpointRequest, opts ...grpc.CallOption) (*Contract, error) {
	out := new(Contract)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.eth.ContractService/GetContractAddressEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) CallContractMethodEndpoint(ctx context.Context, in *CallContractMethodEndpointRequest, opts ...grpc.CallOption) (*Contract, error) {
	out := new(Contract)
	err := c.cc.Invoke(ctx, "/fairwaycorp.blockchainprotobuf.eth.ContractService/CallContractMethodEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServiceServer is the server API for ContractService service.
type ContractServiceServer interface {
	CreateContractEndpoint(context.Context, *CreateContractEndpointRequest) (*Contracts, error)
	GetContractAddressEndpoint(context.Context, *GetContractAddressEndpointRequest) (*Contract, error)
	CallContractMethodEndpoint(context.Context, *CallContractMethodEndpointRequest) (*Contract, error)
}

func RegisterContractServiceServer(s *grpc.Server, srv ContractServiceServer) {
	s.RegisterService(&_ContractService_serviceDesc, srv)
}

func _ContractService_CreateContractEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContractEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).CreateContractEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.eth.ContractService/CreateContractEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).CreateContractEndpoint(ctx, req.(*CreateContractEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_GetContractAddressEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractAddressEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).GetContractAddressEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.eth.ContractService/GetContractAddressEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).GetContractAddressEndpoint(ctx, req.(*GetContractAddressEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_CallContractMethodEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallContractMethodEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).CallContractMethodEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fairwaycorp.blockchainprotobuf.eth.ContractService/CallContractMethodEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).CallContractMethodEndpoint(ctx, req.(*CallContractMethodEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContractService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fairwaycorp.blockchainprotobuf.eth.ContractService",
	HandlerType: (*ContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContractEndpoint",
			Handler:    _ContractService_CreateContractEndpoint_Handler,
		},
		{
			MethodName: "GetContractAddressEndpoint",
			Handler:    _ContractService_GetContractAddressEndpoint_Handler,
		},
		{
			MethodName: "CallContractMethodEndpoint",
			Handler:    _ContractService_CallContractMethodEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contractService_Eth.proto",
}

func init() {
	proto.RegisterFile("contractService_Eth.proto", fileDescriptor_contractService_Eth_fe6dffe2bc5f3978)
}

var fileDescriptor_contractService_Eth_fe6dffe2bc5f3978 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x3d, 0x4e, 0xeb, 0x40,
	0x14, 0x85, 0xe5, 0xa7, 0xa7, 0x57, 0xb8, 0x79, 0x92, 0x0b, 0x7e, 0x2c, 0x68, 0x4c, 0x83, 0x22,
	0xec, 0xe1, 0x47, 0xa2, 0x88, 0x40, 0x28, 0x58, 0x11, 0x15, 0x0d, 0x74, 0x34, 0xd1, 0x78, 0x7c,
	0x63, 0x8f, 0x62, 0xcf, 0x75, 0x66, 0xae, 0x89, 0xa2, 0x28, 0x0d, 0x5b, 0x60, 0x21, 0x2c, 0x82,
	0x05, 0x50, 0x50, 0xd2, 0xb2, 0x10, 0x14, 0x27, 0x0e, 0x20, 0x88, 0x48, 0xe8, 0x2c, 0x5f, 0x9d,
	0xf3, 0x7d, 0x47, 0x63, 0x6f, 0x0a, 0x54, 0xa4, 0xb9, 0xa0, 0x6b, 0xd0, 0xb7, 0x52, 0x40, 0xa7,
	0x4d, 0x69, 0x50, 0x68, 0x24, 0x74, 0xbc, 0x2e, 0x97, 0x7a, 0xc0, 0x87, 0x02, 0x75, 0x11, 0x44,
	0x19, 0x8a, 0x9e, 0x48, 0xb9, 0x54, 0xd5, 0x31, 0x2a, 0xbb, 0x01, 0x50, 0xea, 0x6e, 0x25, 0x88,
	0x49, 0x06, 0x8c, 0x17, 0x92, 0x71, 0xa5, 0x90, 0x38, 0x49, 0x54, 0x66, 0xda, 0xe0, 0xce, 0xcb,
	0x2f, 0xc1, 0x18, 0x9e, 0x7c, 0x28, 0x77, 0xd7, 0x05, 0xe6, 0x39, 0xaa, 0x2f, 0x87, 0xc3, 0x97,
	0xbf, 0xf6, 0xff, 0xf0, 0xb3, 0x93, 0xf3, 0x60, 0xd9, 0x6b, 0xa1, 0x06, 0x4e, 0x50, 0x5f, 0xda,
	0x2a, 0x2e, 0x50, 0x2a, 0x72, 0x5a, 0xc1, 0xcf, 0x96, 0xc1, 0xf7, 0xd9, 0x2b, 0xe8, 0x97, 0x60,
	0xc8, 0xf5, 0x97, 0xaa, 0x98, 0x85, 0x8d, 0xb7, 0x73, 0xf7, 0xfc, 0x7a, 0xff, 0x67, 0xdb, 0xdb,
	0x60, 0x40, 0x29, 0x1b, 0x29, 0xa0, 0x01, 0xea, 0xde, 0x98, 0xd5, 0x5b, 0x4d, 0xd3, 0x6a, 0x38,
	0x8f, 0x96, 0xed, 0x5e, 0x00, 0xd5, 0xa9, 0x56, 0x1c, 0x6b, 0x30, 0x66, 0x6e, 0xdd, 0x5e, 0x06,
	0xb9, 0x38, 0x5f, 0x9b, 0xef, 0xad, 0x62, 0xee, 0xed, 0x57, 0xe2, 0x0d, 0x67, 0x77, 0x91, 0x38,
	0x1b, 0xf5, 0x4b, 0xd0, 0xc3, 0x0e, 0x9f, 0xd2, 0xc6, 0xce, 0x93, 0x65, 0xbb, 0x21, 0xcf, 0xb2,
	0x70, 0xfe, 0x8c, 0x94, 0x62, 0xbc, 0xda, 0x8a, 0xc5, 0xf9, 0xdf, 0xad, 0x38, 0xa9, 0x56, 0x1c,
	0x7b, 0x07, 0xcb, 0xae, 0x60, 0xa3, 0xbc, 0xc2, 0x8e, 0x9b, 0x56, 0xe3, 0xfc, 0xec, 0xe6, 0x34,
	0x91, 0x94, 0x96, 0x51, 0x20, 0x30, 0x67, 0x33, 0xae, 0x3f, 0x01, 0xb3, 0x77, 0xb0, 0x5f, 0x93,
	0x59, 0xf5, 0x21, 0xfc, 0x04, 0x94, 0x9f, 0xe0, 0x04, 0x18, 0xfd, 0xab, 0x7e, 0x1d, 0xbd, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x92, 0xb1, 0x1b, 0x2d, 0x38, 0x03, 0x00, 0x00,
}
