// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactionMessage_Eth.proto

package eth // import "github.com/fairway-corp/blockchain-protobuf/protoc-gen-go/eth"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxArray struct {
	Result               []*TX    `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxArray) Reset()         { *m = TxArray{} }
func (m *TxArray) String() string { return proto.CompactTextString(m) }
func (*TxArray) ProtoMessage()    {}
func (*TxArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{0}
}
func (m *TxArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxArray.Unmarshal(m, b)
}
func (m *TxArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxArray.Marshal(b, m, deterministic)
}
func (dst *TxArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxArray.Merge(dst, src)
}
func (m *TxArray) XXX_Size() int {
	return xxx_messageInfo_TxArray.Size(m)
}
func (m *TxArray) XXX_DiscardUnknown() {
	xxx_messageInfo_TxArray.DiscardUnknown(m)
}

var xxx_messageInfo_TxArray proto.InternalMessageInfo

func (m *TxArray) GetResult() []*TX {
	if m != nil {
		return m.Result
	}
	return nil
}

type TransactionHashEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	Txhash               string               `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionHashEndpointRequest) Reset()         { *m = TransactionHashEndpointRequest{} }
func (m *TransactionHashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionHashEndpointRequest) ProtoMessage()    {}
func (*TransactionHashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{1}
}
func (m *TransactionHashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHashEndpointRequest.Unmarshal(m, b)
}
func (m *TransactionHashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHashEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *TransactionHashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHashEndpointRequest.Merge(dst, src)
}
func (m *TransactionHashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionHashEndpointRequest.Size(m)
}
func (m *TransactionHashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHashEndpointRequest proto.InternalMessageInfo

func (m *TransactionHashEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *TransactionHashEndpointRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type UnconfirmedTransactionsEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UnconfirmedTransactionsEndpointRequest) Reset() {
	*m = UnconfirmedTransactionsEndpointRequest{}
}
func (m *UnconfirmedTransactionsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*UnconfirmedTransactionsEndpointRequest) ProtoMessage()    {}
func (*UnconfirmedTransactionsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{2}
}
func (m *UnconfirmedTransactionsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnconfirmedTransactionsEndpointRequest.Unmarshal(m, b)
}
func (m *UnconfirmedTransactionsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnconfirmedTransactionsEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *UnconfirmedTransactionsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnconfirmedTransactionsEndpointRequest.Merge(dst, src)
}
func (m *UnconfirmedTransactionsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_UnconfirmedTransactionsEndpointRequest.Size(m)
}
func (m *UnconfirmedTransactionsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnconfirmedTransactionsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnconfirmedTransactionsEndpointRequest proto.InternalMessageInfo

func (m *UnconfirmedTransactionsEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

type CreateTransactionsEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	// Height of the block that contains this transaction. If this is an unconfirmed transaction, it will equal -1.
	BlockHeight int32 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// The hash of the transaction.
	Hash string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	// Array of Ethereum addresses involved in the transaction.
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// The total number of wei exchanged in this transaction.
	Total uint64 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	// The total number of fees—in wei—collected by miners in this transaction. Equal to gas_price * gas_used.
	Fees uint64 `protobuf:"varint,6,opt,name=fees,proto3" json:"fees,omitempty"`
	// The size of the transaction in bytes.
	Size uint64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// The amount of gas used by this transaction.
	GasUsed uint64 `protobuf:"varint,8,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// The price of gas—in wei—in this transaction.
	GasPrice uint64 `protobuf:"varint,9,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// Address of the peer that sent BlockCypher’s servers this transaction. May be empty.
	RelayedBy string `protobuf:"bytes,10,opt,name=relayed_by,json=relayedBy,proto3" json:"relayed_by,omitempty"`
	// Time this transaction was received by BlockCypher’s servers.
	Received string `protobuf:"bytes,11,opt,name=received,proto3" json:"received,omitempty"`
	// Version number of this transaction.
	Ver int32 `protobuf:"varint,12,opt,name=ver,proto3" json:"ver,omitempty"`
	// true if this is an attempted double spend; false otherwise.
	DoubleSpend bool `protobuf:"varint,13,opt,name=double_spend,json=doubleSpend,proto3" json:"double_spend,omitempty"`
	// Total number of inputs in the transaction.
	VinSz int32 `protobuf:"varint,14,opt,name=vin_sz,json=vinSz,proto3" json:"vin_sz,omitempty"`
	// Total number of outputs in the transaction.
	VoutSz int32 `protobuf:"varint,15,opt,name=vout_sz,json=voutSz,proto3" json:"vout_sz,omitempty"`
	// Number of subsequent blocks, including the block the transaction is in. Unconfirmed transactions have 0 confirmations.
	Confirmations int32 `protobuf:"varint,16,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// An array object containing a single input with a sequence number (used as a nonce for account balances) and an Ethereum account address. Only contains one input in the array; we still use an array to maintain parity with the Bitcoin API.
	Inputs []*InputType `protobuf:"bytes,17,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// An array object containing a single output with value (in wei), script, and an Ethereum account address. Only contains one output in the array; we still use an array to maintain parity with the Bitcoin API.
	Outputs []*OutputType `protobuf:"bytes,18,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Optional If this transaction executed a contract which propagated its own subsequent transactions, then this array will be present, containing the hashes of those subsequent internal transactions.
	InternalTxids []string `protobuf:"bytes,19,rep,name=internal_txids,json=internalTxids,proto3" json:"internal_txids,omitempty"`
	// Optional If this transaction was initiated by a contract, this field will be present, conveying the hash of the parent transaction that executed the contract resulting in this transaction (the inverse of an internal_txids hash).
	ParentTx string `protobuf:"bytes,20,opt,name=parent_tx,json=parentTx,proto3" json:"parent_tx,omitempty"`
	// Optional Time at which transaction was included in a block; only present for confirmed transactions.
	Confirmed string `protobuf:"bytes,21,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	// Optional If creating a transaction, can optionally set a higher default gas limit (useful if your recepient is a contract). If not set, default is 21000 gas for external accounts and 80000 for contract accounts.
	GasLimit int32 `protobuf:"varint,22,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// Optional If true, this transaction was used to create a contract and contract account. Note that the contract address (in the outputs field) will be blank until the transaction is confirmed.
	ContractCreation bool `protobuf:"varint,23,opt,name=contract_creation,json=contractCreation,proto3" json:"contract_creation,omitempty"`
	// Optional Number of peers that have sent this transaction to BlockCypher; only present for unconfirmed transactions.
	ReceiveCount int32 `protobuf:"varint,24,opt,name=receive_count,json=receiveCount,proto3" json:"receive_count,omitempty"`
	// Optional Hash of the block that contains this transaction; only present for confirmed transactions.
	BlockHash string `protobuf:"bytes,25,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Optional Canonical, zero-indexed location of this transaction in a block; only present for confirmed transactions.
	BlockIndex int32 `protobuf:"varint,26,opt,name=block_index,json=blockIndex,proto3" json:"block_index,omitempty"`
	// Optional If this transaction is a double-spend (i.e. double_spend == true) then this is the hash of the transaction it’s double-spending.
	DoubleOf string `protobuf:"bytes,27,opt,name=double_of,json=doubleOf,proto3" json:"double_of,omitempty"`
	// Optional If this transaction has an execution error, then this field will be included (e.g. “out of gas”).
	ExecutionError       string   `protobuf:"bytes,28,opt,name=execution_error,json=executionError,proto3" json:"execution_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransactionsEndpointRequest) Reset()         { *m = CreateTransactionsEndpointRequest{} }
func (m *CreateTransactionsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionsEndpointRequest) ProtoMessage()    {}
func (*CreateTransactionsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{3}
}
func (m *CreateTransactionsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionsEndpointRequest.Unmarshal(m, b)
}
func (m *CreateTransactionsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionsEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTransactionsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionsEndpointRequest.Merge(dst, src)
}
func (m *CreateTransactionsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionsEndpointRequest.Size(m)
}
func (m *CreateTransactionsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionsEndpointRequest proto.InternalMessageInfo

func (m *CreateTransactionsEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *CreateTransactionsEndpointRequest) GetBlockHeight() int32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *CreateTransactionsEndpointRequest) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetFees() uint64 {
	if m != nil {
		return m.Fees
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetRelayedBy() string {
	if m != nil {
		return m.RelayedBy
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetReceived() string {
	if m != nil {
		return m.Received
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetDoubleSpend() bool {
	if m != nil {
		return m.DoubleSpend
	}
	return false
}

func (m *CreateTransactionsEndpointRequest) GetVinSz() int32 {
	if m != nil {
		return m.VinSz
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetVoutSz() int32 {
	if m != nil {
		return m.VoutSz
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetInputs() []*InputType {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *CreateTransactionsEndpointRequest) GetOutputs() []*OutputType {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *CreateTransactionsEndpointRequest) GetInternalTxids() []string {
	if m != nil {
		return m.InternalTxids
	}
	return nil
}

func (m *CreateTransactionsEndpointRequest) GetParentTx() string {
	if m != nil {
		return m.ParentTx
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetConfirmed() string {
	if m != nil {
		return m.Confirmed
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetGasLimit() int32 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetContractCreation() bool {
	if m != nil {
		return m.ContractCreation
	}
	return false
}

func (m *CreateTransactionsEndpointRequest) GetReceiveCount() int32 {
	if m != nil {
		return m.ReceiveCount
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetBlockIndex() int32 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *CreateTransactionsEndpointRequest) GetDoubleOf() string {
	if m != nil {
		return m.DoubleOf
	}
	return ""
}

func (m *CreateTransactionsEndpointRequest) GetExecutionError() string {
	if m != nil {
		return m.ExecutionError
	}
	return ""
}

type SendTransactionEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	// A temporary TX, usually returned fully filled.
	Tx *TX `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	// Array of hex-encoded data for you to sign, containing one element for you to sign. Still an array to maintain parity with the Bitcoin API.
	Tosign []string `protobuf:"bytes,3,rep,name=tosign,proto3" json:"tosign,omitempty"`
	// Array of signatures corresponding to all the data in tosign, typically provided by you. Only one signature is required.
	Signatures []string `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Optional Array of errors in the form “error”:“description-of-error”. This is only returned if there was an error in any stage of transaction generation, and is usually accompanied by a HTTP 400 code.
	Errors               []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionEndpointRequest) Reset()         { *m = SendTransactionEndpointRequest{} }
func (m *SendTransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionEndpointRequest) ProtoMessage()    {}
func (*SendTransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{4}
}
func (m *SendTransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionEndpointRequest.Unmarshal(m, b)
}
func (m *SendTransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *SendTransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionEndpointRequest.Merge(dst, src)
}
func (m *SendTransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionEndpointRequest.Size(m)
}
func (m *SendTransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionEndpointRequest proto.InternalMessageInfo

func (m *SendTransactionEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *SendTransactionEndpointRequest) GetTx() *TX {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SendTransactionEndpointRequest) GetTosign() []string {
	if m != nil {
		return m.Tosign
	}
	return nil
}

func (m *SendTransactionEndpointRequest) GetSignatures() []string {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *SendTransactionEndpointRequest) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type DecodeRawTransactionEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	Tx                   string               `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DecodeRawTransactionEndpointRequest) Reset()         { *m = DecodeRawTransactionEndpointRequest{} }
func (m *DecodeRawTransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DecodeRawTransactionEndpointRequest) ProtoMessage()    {}
func (*DecodeRawTransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{5}
}
func (m *DecodeRawTransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodeRawTransactionEndpointRequest.Unmarshal(m, b)
}
func (m *DecodeRawTransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodeRawTransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *DecodeRawTransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodeRawTransactionEndpointRequest.Merge(dst, src)
}
func (m *DecodeRawTransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DecodeRawTransactionEndpointRequest.Size(m)
}
func (m *DecodeRawTransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodeRawTransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecodeRawTransactionEndpointRequest proto.InternalMessageInfo

func (m *DecodeRawTransactionEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *DecodeRawTransactionEndpointRequest) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

type PushRawTransactionEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=fairwaycorp.blockchainprotobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	Tx                   string               `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PushRawTransactionEndpointRequest) Reset()         { *m = PushRawTransactionEndpointRequest{} }
func (m *PushRawTransactionEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PushRawTransactionEndpointRequest) ProtoMessage()    {}
func (*PushRawTransactionEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d, []int{6}
}
func (m *PushRawTransactionEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRawTransactionEndpointRequest.Unmarshal(m, b)
}
func (m *PushRawTransactionEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRawTransactionEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *PushRawTransactionEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRawTransactionEndpointRequest.Merge(dst, src)
}
func (m *PushRawTransactionEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PushRawTransactionEndpointRequest.Size(m)
}
func (m *PushRawTransactionEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRawTransactionEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRawTransactionEndpointRequest proto.InternalMessageInfo

func (m *PushRawTransactionEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *PushRawTransactionEndpointRequest) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func init() {
	proto.RegisterType((*TxArray)(nil), "fairwaycorp.blockchainprotobuf.eth.TxArray")
	proto.RegisterType((*TransactionHashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.TransactionHashEndpointRequest")
	proto.RegisterType((*UnconfirmedTransactionsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.UnconfirmedTransactionsEndpointRequest")
	proto.RegisterType((*CreateTransactionsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.CreateTransactionsEndpointRequest")
	proto.RegisterType((*SendTransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.SendTransactionEndpointRequest")
	proto.RegisterType((*DecodeRawTransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.DecodeRawTransactionEndpointRequest")
	proto.RegisterType((*PushRawTransactionEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.eth.PushRawTransactionEndpointRequest")
}

func init() {
	proto.RegisterFile("transactionMessage_Eth.proto", fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d)
}

var fileDescriptor_transactionMessage_Eth_b59134b1d5836c6d = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xd1, 0x6f, 0x1b, 0xc5,
	0x13, 0xc7, 0x75, 0x71, 0x6c, 0xc7, 0x93, 0xc4, 0x4d, 0xf7, 0xd7, 0x36, 0xdb, 0x34, 0xbf, 0xe0,
	0xb8, 0x50, 0x2c, 0x21, 0x3b, 0x52, 0x91, 0x10, 0x2f, 0x80, 0xd2, 0x10, 0x29, 0x91, 0x80, 0x56,
	0x17, 0x57, 0x42, 0xbc, 0x9c, 0xd6, 0x77, 0xe3, 0xbb, 0x55, 0xcf, 0xbb, 0x66, 0x77, 0xcf, 0x39,
	0x47, 0xbc, 0x23, 0x24, 0xfe, 0x58, 0xfe, 0x00, 0x1e, 0xd0, 0xce, 0x9d, 0x9d, 0x20, 0x21, 0x91,
	0xa7, 0xf0, 0xe4, 0x9d, 0xcf, 0xfa, 0xfb, 0xbd, 0xd9, 0x99, 0xd9, 0x85, 0x43, 0x67, 0x84, 0xb2,
	0x22, 0x76, 0x52, 0xab, 0xef, 0xd1, 0x5a, 0x91, 0x62, 0x74, 0xee, 0xb2, 0xd1, 0xdc, 0x68, 0xa7,
	0x59, 0x7f, 0x2a, 0xa4, 0xb9, 0x16, 0xcb, 0x58, 0x9b, 0xf9, 0x68, 0x92, 0xeb, 0xf8, 0x43, 0x9c,
	0x09, 0xa9, 0x68, 0x73, 0x52, 0x4c, 0x47, 0xe8, 0xb2, 0x83, 0xfd, 0x58, 0xcf, 0x66, 0xff, 0x20,
	0xee, 0x5f, 0x42, 0x7b, 0x5c, 0x9e, 0x1a, 0x23, 0x96, 0xec, 0x6b, 0x68, 0x19, 0xb4, 0x45, 0xee,
	0x78, 0xd0, 0x6b, 0x0c, 0xb6, 0x5f, 0xbf, 0x1a, 0xfd, 0xbb, 0xf1, 0x68, 0xfc, 0x63, 0x58, 0xab,
	0xfa, 0xbf, 0x07, 0x70, 0x34, 0xbe, 0x4d, 0xf4, 0x42, 0xd8, 0xec, 0x5c, 0x25, 0x73, 0x2d, 0x95,
	0x0b, 0xf1, 0xe7, 0x02, 0xad, 0x63, 0x21, 0xb4, 0x15, 0xba, 0x6b, 0x6d, 0x3e, 0xf0, 0xa0, 0x17,
	0x0c, 0xba, 0xaf, 0xbf, 0xbc, 0xcf, 0x37, 0x7e, 0xa8, 0x24, 0xa7, 0x79, 0xae, 0xaf, 0xa5, 0x4a,
	0x4f, 0x73, 0x29, 0x6c, 0xb8, 0x32, 0x62, 0xcf, 0xa0, 0xe5, 0xca, 0x4c, 0xd8, 0x8c, 0x6f, 0xf4,
	0x82, 0x41, 0x27, 0xac, 0xa3, 0xfe, 0x2f, 0xf0, 0xea, 0xbd, 0x8a, 0xb5, 0x9a, 0x4a, 0x33, 0xc3,
	0xe4, 0x4e, 0x62, 0xf6, 0x01, 0xb2, 0xea, 0xff, 0xd1, 0x86, 0xe3, 0x33, 0x83, 0xc2, 0xe1, 0x03,
	0x7f, 0x99, 0x1d, 0xc3, 0x0e, 0xe9, 0xa2, 0x0c, 0x65, 0x9a, 0x39, 0xaa, 0x4a, 0x33, 0xdc, 0x26,
	0x76, 0x41, 0x88, 0x31, 0xd8, 0xa4, 0x82, 0x35, 0xa8, 0x60, 0xb4, 0x66, 0x87, 0xd0, 0x11, 0x49,
	0x62, 0xd0, 0x5a, 0xb4, 0x7c, 0xb3, 0xd7, 0x18, 0x74, 0xc2, 0x5b, 0xc0, 0x9e, 0x40, 0xd3, 0x69,
	0x27, 0x72, 0xde, 0xec, 0x05, 0x83, 0xcd, 0xb0, 0x0a, 0xbc, 0xcf, 0x14, 0xd1, 0xf2, 0x16, 0x41,
	0x5a, 0x7b, 0x66, 0xe5, 0x0d, 0xf2, 0x76, 0xc5, 0xfc, 0x9a, 0x3d, 0x87, 0xad, 0x54, 0xd8, 0xa8,
	0xb0, 0x98, 0xf0, 0x2d, 0xe2, 0xed, 0x54, 0xd8, 0xf7, 0x16, 0x13, 0xf6, 0x02, 0x3a, 0x7e, 0x6b,
	0x6e, 0x64, 0x8c, 0xbc, 0x43, 0x7b, 0xfe, 0xbf, 0xef, 0x7c, 0xcc, 0xfe, 0x0f, 0x60, 0x30, 0x17,
	0x4b, 0x4c, 0xa2, 0xc9, 0x92, 0x03, 0x65, 0xdb, 0xa9, 0xc9, 0x9b, 0x25, 0x3b, 0x80, 0x2d, 0x83,
	0x31, 0xca, 0x05, 0x26, 0x7c, 0x9b, 0x36, 0xd7, 0x31, 0xdb, 0x83, 0xc6, 0x02, 0x0d, 0xdf, 0xa1,
	0xc3, 0xfb, 0xa5, 0xaf, 0x4b, 0xa2, 0x8b, 0x49, 0x8e, 0x91, 0x9d, 0xa3, 0x4a, 0xf8, 0x6e, 0x2f,
	0x18, 0x6c, 0x85, 0xdb, 0x15, 0xbb, 0xf2, 0x88, 0x3d, 0x85, 0xd6, 0x42, 0xaa, 0xc8, 0xde, 0xf0,
	0x2e, 0xe9, 0x9a, 0x0b, 0xa9, 0xae, 0x6e, 0xd8, 0x3e, 0xb4, 0x17, 0xba, 0x70, 0x9e, 0x3f, 0x22,
	0xde, 0xf2, 0xe1, 0xd5, 0x0d, 0xfb, 0x18, 0x76, 0xeb, 0x01, 0x13, 0xd4, 0x5e, 0xbe, 0x47, 0xdb,
	0x7f, 0x87, 0xec, 0x1c, 0x5a, 0x52, 0xcd, 0x0b, 0x67, 0xf9, 0x63, 0xba, 0x57, 0xc3, 0xfb, 0xf4,
	0xf8, 0xd2, 0x2b, 0xc6, 0xcb, 0x39, 0x86, 0xb5, 0x98, 0x5d, 0x40, 0x5b, 0x17, 0x8e, 0x7c, 0x18,
	0xf9, 0x8c, 0xee, 0xe3, 0xf3, 0x96, 0x24, 0x64, 0xb4, 0x92, 0xb3, 0x4f, 0xa0, 0x2b, 0x95, 0x43,
	0xa3, 0x44, 0x1e, 0xb9, 0x52, 0x26, 0x96, 0xff, 0x8f, 0xfa, 0xbd, 0xbb, 0xa2, 0x63, 0x0f, 0x7d,
	0x6b, 0xe6, 0xc2, 0xa0, 0x72, 0x91, 0x2b, 0xf9, 0x93, 0xaa, 0xbe, 0x15, 0x18, 0x97, 0x7e, 0x5c,
	0xd6, 0x77, 0x8b, 0x3f, 0xad, 0x3a, 0xb3, 0x06, 0xab, 0xae, 0xe6, 0x72, 0x26, 0x1d, 0x7f, 0x46,
	0x45, 0xf1, 0x5d, 0xfd, 0xce, 0xc7, 0xec, 0x33, 0x78, 0x1c, 0x6b, 0xe5, 0x8c, 0x88, 0x5d, 0x14,
	0xfb, 0x2b, 0x22, 0xb5, 0xe2, 0xfb, 0xd4, 0x8d, 0xbd, 0xd5, 0xc6, 0x59, 0xcd, 0xd9, 0x4b, 0xd8,
	0xad, 0x7b, 0x1a, 0xc5, 0xba, 0x50, 0x8e, 0x73, 0x72, 0xdb, 0xa9, 0xe1, 0x99, 0x67, 0x7e, 0x4e,
	0xea, 0x91, 0xf7, 0x53, 0xfd, 0xbc, 0xca, 0xa6, 0x1a, 0x78, 0x3f, 0xda, 0x1f, 0x41, 0x35, 0xfd,
	0x91, 0x54, 0x09, 0x96, 0xfc, 0x80, 0x1c, 0x2a, 0xc5, 0xa5, 0x27, 0x3e, 0xdd, 0x7a, 0x34, 0xf4,
	0x94, 0xbf, 0xa8, 0x4e, 0x5a, 0x81, 0xb7, 0x53, 0xf6, 0x29, 0x3c, 0xc2, 0x12, 0xe3, 0xc2, 0xa7,
	0x13, 0xa1, 0x31, 0xda, 0xf0, 0x43, 0xfa, 0x4b, 0x77, 0x8d, 0xcf, 0x3d, 0xed, 0xff, 0x19, 0xc0,
	0xd1, 0x15, 0xaa, 0xbb, 0x4f, 0xcd, 0x43, 0xdc, 0xf7, 0x2f, 0x60, 0xc3, 0x95, 0x74, 0xcb, 0xef,
	0xff, 0x64, 0x6f, 0xb8, 0x92, 0xde, 0x4d, 0x6d, 0x65, 0xaa, 0x78, 0x83, 0xba, 0x5f, 0x47, 0xec,
	0x08, 0xc0, 0xff, 0x0a, 0x57, 0x98, 0xf5, 0x4b, 0x70, 0x87, 0x78, 0x1d, 0x55, 0xc1, 0xf2, 0x66,
	0xa5, 0xab, 0xa2, 0xfe, 0x6f, 0x01, 0xbc, 0xfc, 0x16, 0x63, 0x9d, 0x60, 0x28, 0xae, 0x1f, 0xb8,
	0x06, 0xdd, 0x75, 0x0d, 0x3a, 0xfe, 0x6c, 0xfd, 0x5f, 0x03, 0x38, 0x7e, 0x57, 0xd8, 0xec, 0x3f,
	0xcf, 0xe4, 0xcd, 0x37, 0x3f, 0x7d, 0x95, 0x4a, 0x97, 0x15, 0x93, 0x51, 0xac, 0x67, 0x27, 0xb5,
	0xfd, 0xd0, 0xfb, 0x9f, 0xdc, 0xfa, 0x0f, 0x57, 0x1f, 0x38, 0xa1, 0x45, 0x3c, 0x4c, 0x51, 0x0d,
	0x53, 0x7d, 0x82, 0x2e, 0x9b, 0xb4, 0x08, 0x7d, 0xfe, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0,
	0xcf, 0x23, 0x21, 0x04, 0x08, 0x00, 0x00,
}
