// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webhooksMessage.proto

package eth // import "github.com/chainweaver/protobuf/protoc-gen-go/eth"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateWebHookEndpointRequest struct {
	Network NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=chainweaver.protobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	// Identifier of the event; generated when a new request is created.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Type of event; can be unconfirmed-tx, new-block, confirmed-tx, tx-confirmation, double-spend-tx.
	Event string `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	// optional Only objects with a matching hash will be sent. The hash can either be for a block or a transaction.
	Hash string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	// optional Only transactions associated with the given address will be sent.
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// optional Used in concert with the tx-confirmation event type to set the number of confirmations desired for which to receive an update. You’ll receive an updated TX for every confirmation up to this amount. The maximum allowed is 10; if not set, it will default to 6.
	Confirmations int32 `protobuf:"varint,6,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	// optional Callback URL for this Event’s WebHook; not applicable for WebSockets usage.
	Url string `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	// Number of errors when attempting to POST to callback URL; not applicable for WebSockets usage.
	CallbackErrors int32 `protobuf:"varint,8,opt,name=callback_errors,json=callbackErrors,proto3" json:"callback_errors,omitempty"`
	// Token
	Token                string   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWebHookEndpointRequest) Reset()         { *m = CreateWebHookEndpointRequest{} }
func (m *CreateWebHookEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWebHookEndpointRequest) ProtoMessage()    {}
func (*CreateWebHookEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhooksMessage_b653c6ad48214df9, []int{0}
}
func (m *CreateWebHookEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWebHookEndpointRequest.Unmarshal(m, b)
}
func (m *CreateWebHookEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWebHookEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *CreateWebHookEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWebHookEndpointRequest.Merge(dst, src)
}
func (m *CreateWebHookEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWebHookEndpointRequest.Size(m)
}
func (m *CreateWebHookEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWebHookEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWebHookEndpointRequest proto.InternalMessageInfo

func (m *CreateWebHookEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *CreateWebHookEndpointRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateWebHookEndpointRequest) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *CreateWebHookEndpointRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CreateWebHookEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateWebHookEndpointRequest) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *CreateWebHookEndpointRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateWebHookEndpointRequest) GetCallbackErrors() int32 {
	if m != nil {
		return m.CallbackErrors
	}
	return 0
}

func (m *CreateWebHookEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListWebHooksEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=chainweaver.protobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	Token                string               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListWebHooksEndpointRequest) Reset()         { *m = ListWebHooksEndpointRequest{} }
func (m *ListWebHooksEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*ListWebHooksEndpointRequest) ProtoMessage()    {}
func (*ListWebHooksEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhooksMessage_b653c6ad48214df9, []int{1}
}
func (m *ListWebHooksEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListWebHooksEndpointRequest.Unmarshal(m, b)
}
func (m *ListWebHooksEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListWebHooksEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *ListWebHooksEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListWebHooksEndpointRequest.Merge(dst, src)
}
func (m *ListWebHooksEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_ListWebHooksEndpointRequest.Size(m)
}
func (m *ListWebHooksEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListWebHooksEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListWebHooksEndpointRequest proto.InternalMessageInfo

func (m *ListWebHooksEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *ListWebHooksEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Events struct {
	Event                []*Event `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhooksMessage_b653c6ad48214df9, []int{2}
}
func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (dst *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(dst, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type WebHookIDEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=chainweaver.protobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	Webhookid            string               `protobuf:"bytes,2,opt,name=webhookid,proto3" json:"webhookid,omitempty"`
	Token                string               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WebHookIDEndpointRequest) Reset()         { *m = WebHookIDEndpointRequest{} }
func (m *WebHookIDEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*WebHookIDEndpointRequest) ProtoMessage()    {}
func (*WebHookIDEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhooksMessage_b653c6ad48214df9, []int{3}
}
func (m *WebHookIDEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebHookIDEndpointRequest.Unmarshal(m, b)
}
func (m *WebHookIDEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebHookIDEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *WebHookIDEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebHookIDEndpointRequest.Merge(dst, src)
}
func (m *WebHookIDEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_WebHookIDEndpointRequest.Size(m)
}
func (m *WebHookIDEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebHookIDEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebHookIDEndpointRequest proto.InternalMessageInfo

func (m *WebHookIDEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *WebHookIDEndpointRequest) GetWebhookid() string {
	if m != nil {
		return m.Webhookid
	}
	return ""
}

func (m *WebHookIDEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteWebHookEndpointRequest struct {
	Network              NetworkAllowingAlias `protobuf:"varint,1,opt,name=network,proto3,enum=chainweaver.protobuf.eth.NetworkAllowingAlias" json:"network,omitempty"`
	Webhookid            string               `protobuf:"bytes,2,opt,name=webhookid,proto3" json:"webhookid,omitempty"`
	Token                string               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteWebHookEndpointRequest) Reset()         { *m = DeleteWebHookEndpointRequest{} }
func (m *DeleteWebHookEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteWebHookEndpointRequest) ProtoMessage()    {}
func (*DeleteWebHookEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webhooksMessage_b653c6ad48214df9, []int{4}
}
func (m *DeleteWebHookEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteWebHookEndpointRequest.Unmarshal(m, b)
}
func (m *DeleteWebHookEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteWebHookEndpointRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteWebHookEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteWebHookEndpointRequest.Merge(dst, src)
}
func (m *DeleteWebHookEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteWebHookEndpointRequest.Size(m)
}
func (m *DeleteWebHookEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteWebHookEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteWebHookEndpointRequest proto.InternalMessageInfo

func (m *DeleteWebHookEndpointRequest) GetNetwork() NetworkAllowingAlias {
	if m != nil {
		return m.Network
	}
	return NetworkAllowingAlias_MAIN
}

func (m *DeleteWebHookEndpointRequest) GetWebhookid() string {
	if m != nil {
		return m.Webhookid
	}
	return ""
}

func (m *DeleteWebHookEndpointRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateWebHookEndpointRequest)(nil), "chainweaver.protobuf.eth.CreateWebHookEndpointRequest")
	proto.RegisterType((*ListWebHooksEndpointRequest)(nil), "chainweaver.protobuf.eth.ListWebHooksEndpointRequest")
	proto.RegisterType((*Events)(nil), "chainweaver.protobuf.eth.Events")
	proto.RegisterType((*WebHookIDEndpointRequest)(nil), "chainweaver.protobuf.eth.WebHookIDEndpointRequest")
	proto.RegisterType((*DeleteWebHookEndpointRequest)(nil), "chainweaver.protobuf.eth.DeleteWebHookEndpointRequest")
}

func init() {
	proto.RegisterFile("webhooksMessage.proto", fileDescriptor_webhooksMessage_b653c6ad48214df9)
}

var fileDescriptor_webhooksMessage_b653c6ad48214df9 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0x49, 0xf2, 0xda, 0xda, 0x11, 0xab, 0x8c, 0x0a, 0x83, 0x16, 0x0c, 0x45, 0x30, 0x9b,
	0x97, 0xe2, 0x7b, 0xb8, 0x96, 0xa7, 0x2d, 0x54, 0x50, 0x17, 0xd9, 0x08, 0x6e, 0x64, 0x92, 0xdc,
	0x26, 0x43, 0x92, 0xb9, 0x75, 0x66, 0xd2, 0xac, 0xfc, 0x1e, 0x2e, 0xfc, 0x16, 0x7e, 0x41, 0xe9,
	0x24, 0xe9, 0x9f, 0x45, 0x37, 0x42, 0xdf, 0xee, 0xde, 0x1f, 0x73, 0x38, 0x67, 0xce, 0x0c, 0x79,
	0xde, 0x40, 0x9c, 0x23, 0x16, 0xfa, 0x0b, 0x68, 0xcd, 0x33, 0x08, 0x37, 0x0a, 0x0d, 0x52, 0x96,
	0xe4, 0x5c, 0xc8, 0x06, 0xf8, 0x16, 0x54, 0x8b, 0xe2, 0x7a, 0x1d, 0x82, 0xc9, 0x5f, 0x3c, 0x4d,
	0xb0, 0xaa, 0x50, 0x9e, 0x1c, 0x9f, 0xfd, 0x75, 0xc9, 0xf4, 0xa3, 0x02, 0x6e, 0xe0, 0x1b, 0xc4,
	0x2b, 0xc4, 0x62, 0x29, 0xd3, 0x0d, 0x0a, 0x69, 0x22, 0xf8, 0x59, 0x83, 0x36, 0x74, 0x45, 0x46,
	0x12, 0x4c, 0x83, 0xaa, 0x60, 0x8e, 0xef, 0x04, 0x93, 0x9b, 0x30, 0x3c, 0xe7, 0x10, 0x7e, 0x6d,
	0x0f, 0xde, 0x95, 0x25, 0x36, 0x42, 0x66, 0x77, 0xa5, 0xe0, 0x3a, 0xea, 0xe5, 0x74, 0x42, 0x5c,
	0x91, 0x32, 0xd7, 0x77, 0x82, 0x71, 0xe4, 0x8a, 0x94, 0x3e, 0x23, 0x03, 0xd8, 0x82, 0x34, 0xcc,
	0xb3, 0xa8, 0x5d, 0x28, 0x25, 0x57, 0x39, 0xd7, 0x39, 0xbb, 0xb2, 0xd0, 0xce, 0x94, 0x91, 0x11,
	0x4f, 0x53, 0x05, 0x5a, 0xb3, 0x81, 0xc5, 0xfd, 0x4a, 0x5f, 0x93, 0x47, 0x09, 0xca, 0xb5, 0x50,
	0x15, 0x37, 0x02, 0xa5, 0x66, 0x43, 0xdf, 0x09, 0x06, 0xd1, 0x29, 0xa4, 0x4f, 0x88, 0x57, 0xab,
	0x92, 0x8d, 0xac, 0x76, 0x37, 0xd2, 0x37, 0xe4, 0x71, 0xc2, 0xcb, 0x32, 0xe6, 0x49, 0xf1, 0x03,
	0x94, 0x42, 0xa5, 0xd9, 0x03, 0xab, 0x9c, 0xf4, 0x78, 0x69, 0xe9, 0x2e, 0xa4, 0xc1, 0x02, 0x24,
	0x1b, 0xb7, 0x21, 0xed, 0x32, 0xfb, 0x45, 0x5e, 0x7e, 0x16, 0xda, 0x74, 0x95, 0xe9, 0xcb, 0x75,
	0xb6, 0xb7, 0x77, 0x8f, 0xed, 0xdf, 0x93, 0xe1, 0x72, 0x57, 0x96, 0xa6, 0xef, 0xfa, 0x0e, 0x1d,
	0xdf, 0x0b, 0x1e, 0xde, 0xbc, 0x3a, 0xef, 0x63, 0x05, 0x5d, 0xc9, 0xb3, 0xdf, 0x0e, 0x61, 0x5d,
	0xf8, 0x4f, 0x8b, 0xcb, 0xa5, 0x9f, 0x92, 0x71, 0xf7, 0x49, 0xf7, 0x0f, 0x7f, 0x00, 0x87, 0xbb,
	0x79, 0xc7, 0x77, 0xfb, 0xe3, 0x90, 0xe9, 0x02, 0x4a, 0xb8, 0x87, 0x0f, 0xf9, 0x1f, 0xf1, 0x3e,
	0xdc, 0x7e, 0x7f, 0x9b, 0x09, 0x93, 0xd7, 0x71, 0x98, 0x60, 0x35, 0x3f, 0x32, 0x9e, 0xf7, 0xc6,
	0xed, 0x90, 0x5c, 0x67, 0x20, 0xaf, 0x33, 0x9c, 0x83, 0xc9, 0xe3, 0xa1, 0x45, 0xb7, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x6a, 0x0e, 0xd0, 0xb8, 0xb3, 0x03, 0x00, 0x00,
}
