// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assetMessage.proto

package protoc_gen_go_btc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IssueAssetEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueAssetEndpointRequest) Reset()         { *m = IssueAssetEndpointRequest{} }
func (m *IssueAssetEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*IssueAssetEndpointRequest) ProtoMessage()    {}
func (*IssueAssetEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3ec776296c6c53, []int{0}
}

func (m *IssueAssetEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueAssetEndpointRequest.Unmarshal(m, b)
}
func (m *IssueAssetEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueAssetEndpointRequest.Marshal(b, m, deterministic)
}
func (m *IssueAssetEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueAssetEndpointRequest.Merge(m, src)
}
func (m *IssueAssetEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_IssueAssetEndpointRequest.Size(m)
}
func (m *IssueAssetEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueAssetEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueAssetEndpointRequest proto.InternalMessageInfo

func (m *IssueAssetEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

type TransferAssetEndpointRequest struct {
	Stage   string `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Assetid string `protobuf:"bytes,2,opt,name=assetid,proto3" json:"assetid,omitempty"`
	// The private key being used to issue or transfer assets.
	FromPrivate string `protobuf:"bytes,3,opt,name=from_private,json=fromPrivate,proto3" json:"from_private,omitempty"`
	// The target OAP address assets for issue or transfer.
	ToAddress string `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// The amount of assets being issued or transfered.
	Amount int32 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// Optional Hex-encoded metadata that can optionally be encoded into the issue or transfer transaction.
	Metadata             string   `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferAssetEndpointRequest) Reset()         { *m = TransferAssetEndpointRequest{} }
func (m *TransferAssetEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*TransferAssetEndpointRequest) ProtoMessage()    {}
func (*TransferAssetEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3ec776296c6c53, []int{1}
}

func (m *TransferAssetEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferAssetEndpointRequest.Unmarshal(m, b)
}
func (m *TransferAssetEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferAssetEndpointRequest.Marshal(b, m, deterministic)
}
func (m *TransferAssetEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferAssetEndpointRequest.Merge(m, src)
}
func (m *TransferAssetEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_TransferAssetEndpointRequest.Size(m)
}
func (m *TransferAssetEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferAssetEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferAssetEndpointRequest proto.InternalMessageInfo

func (m *TransferAssetEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *TransferAssetEndpointRequest) GetAssetid() string {
	if m != nil {
		return m.Assetid
	}
	return ""
}

func (m *TransferAssetEndpointRequest) GetFromPrivate() string {
	if m != nil {
		return m.FromPrivate
	}
	return ""
}

func (m *TransferAssetEndpointRequest) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *TransferAssetEndpointRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransferAssetEndpointRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type ListAssetTXsEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Assetid              string   `protobuf:"bytes,2,opt,name=assetid,proto3" json:"assetid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAssetTXsEndpointRequest) Reset()         { *m = ListAssetTXsEndpointRequest{} }
func (m *ListAssetTXsEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*ListAssetTXsEndpointRequest) ProtoMessage()    {}
func (*ListAssetTXsEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3ec776296c6c53, []int{2}
}

func (m *ListAssetTXsEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAssetTXsEndpointRequest.Unmarshal(m, b)
}
func (m *ListAssetTXsEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAssetTXsEndpointRequest.Marshal(b, m, deterministic)
}
func (m *ListAssetTXsEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAssetTXsEndpointRequest.Merge(m, src)
}
func (m *ListAssetTXsEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_ListAssetTXsEndpointRequest.Size(m)
}
func (m *ListAssetTXsEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAssetTXsEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAssetTXsEndpointRequest proto.InternalMessageInfo

func (m *ListAssetTXsEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *ListAssetTXsEndpointRequest) GetAssetid() string {
	if m != nil {
		return m.Assetid
	}
	return ""
}

type GetAssetTXEndpointRequest struct {
	Stage                string   `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Assetid              string   `protobuf:"bytes,2,opt,name=assetid,proto3" json:"assetid,omitempty"`
	Txhash               string   `protobuf:"bytes,3,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetTXEndpointRequest) Reset()         { *m = GetAssetTXEndpointRequest{} }
func (m *GetAssetTXEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssetTXEndpointRequest) ProtoMessage()    {}
func (*GetAssetTXEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3ec776296c6c53, []int{3}
}

func (m *GetAssetTXEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetTXEndpointRequest.Unmarshal(m, b)
}
func (m *GetAssetTXEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetTXEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetAssetTXEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetTXEndpointRequest.Merge(m, src)
}
func (m *GetAssetTXEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetAssetTXEndpointRequest.Size(m)
}
func (m *GetAssetTXEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetTXEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetTXEndpointRequest proto.InternalMessageInfo

func (m *GetAssetTXEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *GetAssetTXEndpointRequest) GetAssetid() string {
	if m != nil {
		return m.Assetid
	}
	return ""
}

func (m *GetAssetTXEndpointRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type GetAssetAddressEndpointRequest struct {
	Stage                string   `protobuf:"bytes,10,opt,name=stage,proto3" json:"stage,omitempty"`
	Assetid              string   `protobuf:"bytes,1,opt,name=assetid,proto3" json:"assetid,omitempty"`
	Oapaddr              string   `protobuf:"bytes,2,opt,name=oapaddr,proto3" json:"oapaddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetAddressEndpointRequest) Reset()         { *m = GetAssetAddressEndpointRequest{} }
func (m *GetAssetAddressEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssetAddressEndpointRequest) ProtoMessage()    {}
func (*GetAssetAddressEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb3ec776296c6c53, []int{4}
}

func (m *GetAssetAddressEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetAddressEndpointRequest.Unmarshal(m, b)
}
func (m *GetAssetAddressEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetAddressEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetAssetAddressEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetAddressEndpointRequest.Merge(m, src)
}
func (m *GetAssetAddressEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetAssetAddressEndpointRequest.Size(m)
}
func (m *GetAssetAddressEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetAddressEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetAddressEndpointRequest proto.InternalMessageInfo

func (m *GetAssetAddressEndpointRequest) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *GetAssetAddressEndpointRequest) GetAssetid() string {
	if m != nil {
		return m.Assetid
	}
	return ""
}

func (m *GetAssetAddressEndpointRequest) GetOapaddr() string {
	if m != nil {
		return m.Oapaddr
	}
	return ""
}

func init() {
	proto.RegisterType((*IssueAssetEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.IssueAssetEndpointRequest")
	proto.RegisterType((*TransferAssetEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.TransferAssetEndpointRequest")
	proto.RegisterType((*ListAssetTXsEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.ListAssetTXsEndpointRequest")
	proto.RegisterType((*GetAssetTXEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GetAssetTXEndpointRequest")
	proto.RegisterType((*GetAssetAddressEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.btc.GetAssetAddressEndpointRequest")
}

func init() { proto.RegisterFile("assetMessage.proto", fileDescriptor_fb3ec776296c6c53) }

var fileDescriptor_fb3ec776296c6c53 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4b, 0xeb, 0x40,
	0x10, 0xc7, 0xc9, 0x7b, 0xaf, 0xe9, 0xeb, 0xbc, 0x77, 0x5a, 0xa4, 0x6c, 0xfd, 0x45, 0xcd, 0xa9,
	0x97, 0xa4, 0x88, 0x67, 0x91, 0x0a, 0x22, 0x82, 0x05, 0x29, 0x3d, 0x88, 0x97, 0x32, 0xd9, 0x6c,
	0x92, 0x55, 0x93, 0x8d, 0xbb, 0x13, 0x7f, 0xfc, 0x7f, 0xfe, 0x61, 0x92, 0x6d, 0xa2, 0x78, 0x28,
	0x08, 0xbd, 0xe5, 0xf3, 0x9d, 0xcc, 0x7e, 0x67, 0x86, 0x2f, 0x30, 0xb4, 0x56, 0xd2, 0x5c, 0x5a,
	0x8b, 0x99, 0x8c, 0x2a, 0xa3, 0x49, 0xb3, 0x20, 0x45, 0x65, 0x5e, 0xf0, 0x4d, 0x68, 0x53, 0x45,
	0xf1, 0xa3, 0x16, 0x0f, 0x22, 0x47, 0x55, 0xba, 0x62, 0x5c, 0xa7, 0x51, 0x4c, 0x22, 0x38, 0x86,
	0xd1, 0x95, 0xb5, 0xb5, 0x9c, 0x35, 0xed, 0x17, 0x65, 0x52, 0x69, 0x55, 0xd2, 0x42, 0x3e, 0xd5,
	0xd2, 0x12, 0xdb, 0x81, 0x9e, 0x25, 0xcc, 0x24, 0xf7, 0xc6, 0xde, 0x64, 0xb0, 0x58, 0x43, 0xf0,
	0xee, 0xc1, 0xfe, 0xd2, 0x60, 0x69, 0x53, 0x69, 0x7e, 0xde, 0xc6, 0x38, 0xf4, 0xdd, 0x8c, 0x2a,
	0xe1, 0xbf, 0x9c, 0xde, 0x21, 0x3b, 0x82, 0xff, 0xa9, 0xd1, 0xc5, 0xaa, 0x32, 0xea, 0x19, 0x49,
	0xf2, 0xdf, 0xae, 0xfc, 0xaf, 0xd1, 0x6e, 0xd6, 0x12, 0x3b, 0x00, 0x20, 0xbd, 0xc2, 0x24, 0x31,
	0xd2, 0x5a, 0xfe, 0xc7, 0xfd, 0x30, 0x20, 0x3d, 0x5b, 0x0b, 0x6c, 0x08, 0x3e, 0x16, 0xba, 0x2e,
	0x89, 0xf7, 0xc6, 0xde, 0xa4, 0xb7, 0x68, 0x89, 0xed, 0xc2, 0xdf, 0x42, 0x12, 0x26, 0x48, 0xc8,
	0x7d, 0xd7, 0xf4, 0xc9, 0xc1, 0x1c, 0xf6, 0xae, 0x95, 0x25, 0xb7, 0xc1, 0xf2, 0xd6, 0x6e, 0xb9,
	0x44, 0x20, 0x60, 0x74, 0x29, 0xbb, 0xd7, 0xb6, 0xbd, 0xc8, 0x10, 0x7c, 0x7a, 0xcd, 0xd1, 0xe6,
	0xed, 0x2d, 0x5a, 0x0a, 0xee, 0xe1, 0xb0, 0x33, 0x69, 0x57, 0xdf, 0xe8, 0x04, 0x1b, 0x9c, 0xbc,
	0xef, 0x4e, 0x1c, 0xfa, 0x1a, 0xab, 0xe6, 0xb0, 0xdd, 0x0c, 0x2d, 0x9e, 0x9f, 0xdd, 0x9d, 0x66,
	0x8a, 0xf2, 0x3a, 0x8e, 0x84, 0x2e, 0xa6, 0x6d, 0x94, 0xc2, 0x26, 0x4b, 0xd3, 0xaf, 0x2c, 0x85,
	0x5d, 0x98, 0xa6, 0xee, 0x43, 0x84, 0x99, 0x2c, 0xc3, 0x4c, 0x87, 0x31, 0x89, 0xd8, 0x77, 0xd2,
	0xc9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x54, 0xa2, 0x88, 0x9b, 0x02, 0x00, 0x00,
}
