// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadataMessage.proto

package protoc_gen_go

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyValues struct {
	Keypair              []*KeyPair `protobuf:"bytes,1,rep,name=keypair,proto3" json:"keypair,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *KeyValues) Reset()         { *m = KeyValues{} }
func (m *KeyValues) String() string { return proto.CompactTextString(m) }
func (*KeyValues) ProtoMessage()    {}
func (*KeyValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{0}
}

func (m *KeyValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValues.Unmarshal(m, b)
}
func (m *KeyValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValues.Marshal(b, m, deterministic)
}
func (m *KeyValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValues.Merge(m, src)
}
func (m *KeyValues) XXX_Size() int {
	return xxx_messageInfo_KeyValues.Size(m)
}
func (m *KeyValues) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValues.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValues proto.InternalMessageInfo

func (m *KeyValues) GetKeypair() []*KeyPair {
	if m != nil {
		return m.Keypair
	}
	return nil
}

type KeyPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPair) Reset()         { *m = KeyPair{} }
func (m *KeyPair) String() string { return proto.CompactTextString(m) }
func (*KeyPair) ProtoMessage()    {}
func (*KeyPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{1}
}

func (m *KeyPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPair.Unmarshal(m, b)
}
func (m *KeyPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPair.Marshal(b, m, deterministic)
}
func (m *KeyPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPair.Merge(m, src)
}
func (m *KeyPair) XXX_Size() int {
	return xxx_messageInfo_KeyPair.Size(m)
}
func (m *KeyPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPair proto.InternalMessageInfo

func (m *KeyPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyPair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetMetadataAddressEndpointRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Private              bool     `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataAddressEndpointRequest) Reset()         { *m = GetMetadataAddressEndpointRequest{} }
func (m *GetMetadataAddressEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataAddressEndpointRequest) ProtoMessage()    {}
func (*GetMetadataAddressEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{2}
}

func (m *GetMetadataAddressEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataAddressEndpointRequest.Unmarshal(m, b)
}
func (m *GetMetadataAddressEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataAddressEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetMetadataAddressEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataAddressEndpointRequest.Merge(m, src)
}
func (m *GetMetadataAddressEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataAddressEndpointRequest.Size(m)
}
func (m *GetMetadataAddressEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataAddressEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataAddressEndpointRequest proto.InternalMessageInfo

func (m *GetMetadataAddressEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetMetadataAddressEndpointRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type GetMetadataTxhashEndpointRequest struct {
	Txhash               string   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Private              bool     `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataTxhashEndpointRequest) Reset()         { *m = GetMetadataTxhashEndpointRequest{} }
func (m *GetMetadataTxhashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataTxhashEndpointRequest) ProtoMessage()    {}
func (*GetMetadataTxhashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{3}
}

func (m *GetMetadataTxhashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataTxhashEndpointRequest.Unmarshal(m, b)
}
func (m *GetMetadataTxhashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataTxhashEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetMetadataTxhashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataTxhashEndpointRequest.Merge(m, src)
}
func (m *GetMetadataTxhashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataTxhashEndpointRequest.Size(m)
}
func (m *GetMetadataTxhashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataTxhashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataTxhashEndpointRequest proto.InternalMessageInfo

func (m *GetMetadataTxhashEndpointRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *GetMetadataTxhashEndpointRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type GetMetadataBlockhashEndpointRequest struct {
	Blockhash            string   `protobuf:"bytes,1,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Private              bool     `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetadataBlockhashEndpointRequest) Reset()         { *m = GetMetadataBlockhashEndpointRequest{} }
func (m *GetMetadataBlockhashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetadataBlockhashEndpointRequest) ProtoMessage()    {}
func (*GetMetadataBlockhashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{4}
}

func (m *GetMetadataBlockhashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetadataBlockhashEndpointRequest.Unmarshal(m, b)
}
func (m *GetMetadataBlockhashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetadataBlockhashEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetMetadataBlockhashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetadataBlockhashEndpointRequest.Merge(m, src)
}
func (m *GetMetadataBlockhashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetadataBlockhashEndpointRequest.Size(m)
}
func (m *GetMetadataBlockhashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetadataBlockhashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetadataBlockhashEndpointRequest proto.InternalMessageInfo

func (m *GetMetadataBlockhashEndpointRequest) GetBlockhash() string {
	if m != nil {
		return m.Blockhash
	}
	return ""
}

func (m *GetMetadataBlockhashEndpointRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type PutMetadataAddressEndpointRequest struct {
	Keypair              []*KeyPair `protobuf:"bytes,1,rep,name=keypair,proto3" json:"keypair,omitempty"`
	Address              string     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Private              bool       `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutMetadataAddressEndpointRequest) Reset()         { *m = PutMetadataAddressEndpointRequest{} }
func (m *PutMetadataAddressEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PutMetadataAddressEndpointRequest) ProtoMessage()    {}
func (*PutMetadataAddressEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{5}
}

func (m *PutMetadataAddressEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMetadataAddressEndpointRequest.Unmarshal(m, b)
}
func (m *PutMetadataAddressEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMetadataAddressEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PutMetadataAddressEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMetadataAddressEndpointRequest.Merge(m, src)
}
func (m *PutMetadataAddressEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PutMetadataAddressEndpointRequest.Size(m)
}
func (m *PutMetadataAddressEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMetadataAddressEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMetadataAddressEndpointRequest proto.InternalMessageInfo

func (m *PutMetadataAddressEndpointRequest) GetKeypair() []*KeyPair {
	if m != nil {
		return m.Keypair
	}
	return nil
}

func (m *PutMetadataAddressEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PutMetadataAddressEndpointRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type PutMetadataTxhashEndpointRequest struct {
	Keypair              []*KeyPair `protobuf:"bytes,1,rep,name=keypair,proto3" json:"keypair,omitempty"`
	Txhash               string     `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Private              bool       `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutMetadataTxhashEndpointRequest) Reset()         { *m = PutMetadataTxhashEndpointRequest{} }
func (m *PutMetadataTxhashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PutMetadataTxhashEndpointRequest) ProtoMessage()    {}
func (*PutMetadataTxhashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{6}
}

func (m *PutMetadataTxhashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMetadataTxhashEndpointRequest.Unmarshal(m, b)
}
func (m *PutMetadataTxhashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMetadataTxhashEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PutMetadataTxhashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMetadataTxhashEndpointRequest.Merge(m, src)
}
func (m *PutMetadataTxhashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PutMetadataTxhashEndpointRequest.Size(m)
}
func (m *PutMetadataTxhashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMetadataTxhashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMetadataTxhashEndpointRequest proto.InternalMessageInfo

func (m *PutMetadataTxhashEndpointRequest) GetKeypair() []*KeyPair {
	if m != nil {
		return m.Keypair
	}
	return nil
}

func (m *PutMetadataTxhashEndpointRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *PutMetadataTxhashEndpointRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type PutMetadataBlockhashEndpointRequest struct {
	Keypair              []*KeyPair `protobuf:"bytes,1,rep,name=keypair,proto3" json:"keypair,omitempty"`
	BlockHash            string     `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Private              bool       `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutMetadataBlockhashEndpointRequest) Reset()         { *m = PutMetadataBlockhashEndpointRequest{} }
func (m *PutMetadataBlockhashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*PutMetadataBlockhashEndpointRequest) ProtoMessage()    {}
func (*PutMetadataBlockhashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{7}
}

func (m *PutMetadataBlockhashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMetadataBlockhashEndpointRequest.Unmarshal(m, b)
}
func (m *PutMetadataBlockhashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMetadataBlockhashEndpointRequest.Marshal(b, m, deterministic)
}
func (m *PutMetadataBlockhashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMetadataBlockhashEndpointRequest.Merge(m, src)
}
func (m *PutMetadataBlockhashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_PutMetadataBlockhashEndpointRequest.Size(m)
}
func (m *PutMetadataBlockhashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMetadataBlockhashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMetadataBlockhashEndpointRequest proto.InternalMessageInfo

func (m *PutMetadataBlockhashEndpointRequest) GetKeypair() []*KeyPair {
	if m != nil {
		return m.Keypair
	}
	return nil
}

func (m *PutMetadataBlockhashEndpointRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *PutMetadataBlockhashEndpointRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

type DeleteMetadataAddressEndpointRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMetadataAddressEndpointRequest) Reset()         { *m = DeleteMetadataAddressEndpointRequest{} }
func (m *DeleteMetadataAddressEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMetadataAddressEndpointRequest) ProtoMessage()    {}
func (*DeleteMetadataAddressEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{8}
}

func (m *DeleteMetadataAddressEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMetadataAddressEndpointRequest.Unmarshal(m, b)
}
func (m *DeleteMetadataAddressEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMetadataAddressEndpointRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMetadataAddressEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMetadataAddressEndpointRequest.Merge(m, src)
}
func (m *DeleteMetadataAddressEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMetadataAddressEndpointRequest.Size(m)
}
func (m *DeleteMetadataAddressEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMetadataAddressEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMetadataAddressEndpointRequest proto.InternalMessageInfo

func (m *DeleteMetadataAddressEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteMetadataAddressEndpointRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteMetadataTxhashEndpointRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Txhash               string   `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMetadataTxhashEndpointRequest) Reset()         { *m = DeleteMetadataTxhashEndpointRequest{} }
func (m *DeleteMetadataTxhashEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMetadataTxhashEndpointRequest) ProtoMessage()    {}
func (*DeleteMetadataTxhashEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{9}
}

func (m *DeleteMetadataTxhashEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMetadataTxhashEndpointRequest.Unmarshal(m, b)
}
func (m *DeleteMetadataTxhashEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMetadataTxhashEndpointRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMetadataTxhashEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMetadataTxhashEndpointRequest.Merge(m, src)
}
func (m *DeleteMetadataTxhashEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMetadataTxhashEndpointRequest.Size(m)
}
func (m *DeleteMetadataTxhashEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMetadataTxhashEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMetadataTxhashEndpointRequest proto.InternalMessageInfo

func (m *DeleteMetadataTxhashEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteMetadataTxhashEndpointRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type DeleteMetadataBlockheightEndpointRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BlockHeight          string   `protobuf:"bytes,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMetadataBlockheightEndpointRequest) Reset() {
	*m = DeleteMetadataBlockheightEndpointRequest{}
}
func (m *DeleteMetadataBlockheightEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMetadataBlockheightEndpointRequest) ProtoMessage()    {}
func (*DeleteMetadataBlockheightEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8a16b8775dd4d7, []int{10}
}

func (m *DeleteMetadataBlockheightEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMetadataBlockheightEndpointRequest.Unmarshal(m, b)
}
func (m *DeleteMetadataBlockheightEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMetadataBlockheightEndpointRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMetadataBlockheightEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMetadataBlockheightEndpointRequest.Merge(m, src)
}
func (m *DeleteMetadataBlockheightEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMetadataBlockheightEndpointRequest.Size(m)
}
func (m *DeleteMetadataBlockheightEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMetadataBlockheightEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMetadataBlockheightEndpointRequest proto.InternalMessageInfo

func (m *DeleteMetadataBlockheightEndpointRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteMetadataBlockheightEndpointRequest) GetBlockHeight() string {
	if m != nil {
		return m.BlockHeight
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyValues)(nil), "fairwaycorp.blockchainprotobuf.KeyValues")
	proto.RegisterType((*KeyPair)(nil), "fairwaycorp.blockchainprotobuf.KeyPair")
	proto.RegisterType((*GetMetadataAddressEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.GetMetadataAddressEndpointRequest")
	proto.RegisterType((*GetMetadataTxhashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.GetMetadataTxhashEndpointRequest")
	proto.RegisterType((*GetMetadataBlockhashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.GetMetadataBlockhashEndpointRequest")
	proto.RegisterType((*PutMetadataAddressEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.PutMetadataAddressEndpointRequest")
	proto.RegisterType((*PutMetadataTxhashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.PutMetadataTxhashEndpointRequest")
	proto.RegisterType((*PutMetadataBlockhashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.PutMetadataBlockhashEndpointRequest")
	proto.RegisterType((*DeleteMetadataAddressEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.DeleteMetadataAddressEndpointRequest")
	proto.RegisterType((*DeleteMetadataTxhashEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.DeleteMetadataTxhashEndpointRequest")
	proto.RegisterType((*DeleteMetadataBlockheightEndpointRequest)(nil), "fairwaycorp.blockchainprotobuf.DeleteMetadataBlockheightEndpointRequest")
}

func init() { proto.RegisterFile("metadataMessage.proto", fileDescriptor_5e8a16b8775dd4d7) }

var fileDescriptor_5e8a16b8775dd4d7 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x8b, 0x9b, 0x50,
	0x14, 0xc5, 0x31, 0x69, 0x93, 0xe6, 0xa6, 0x8b, 0x22, 0x6d, 0x71, 0xd1, 0x16, 0x63, 0x0a, 0xcd,
	0x46, 0x43, 0xdb, 0x55, 0xe9, 0x2a, 0xa1, 0xa5, 0x85, 0x90, 0x92, 0x4a, 0x68, 0xa1, 0x50, 0x86,
	0xa7, 0xde, 0xe8, 0x23, 0x89, 0x3a, 0xfa, 0xcc, 0x8c, 0x9f, 0x64, 0x60, 0x76, 0xf3, 0x4d, 0x07,
	0x9f, 0x4f, 0x62, 0x82, 0x9a, 0x81, 0xc9, 0xee, 0xfe, 0xf1, 0xfe, 0x3c, 0x9c, 0xf3, 0xe0, 0xd5,
	0x16, 0x19, 0x71, 0x08, 0x23, 0x73, 0x8c, 0x63, 0xe2, 0xa2, 0x11, 0x46, 0x01, 0x0b, 0xe4, 0x77,
	0x2b, 0x42, 0xa3, 0x2b, 0x92, 0xda, 0x41, 0x14, 0x1a, 0xd6, 0x26, 0xb0, 0xd7, 0xb6, 0x47, 0xa8,
	0xcf, 0x97, 0x56, 0xb2, 0xd2, 0x7e, 0x41, 0x6f, 0x86, 0xe9, 0x1f, 0xb2, 0x49, 0x30, 0x96, 0x27,
	0xd0, 0x5d, 0x63, 0x1a, 0x12, 0x1a, 0x29, 0x92, 0xda, 0x1e, 0xf5, 0x3f, 0x7d, 0x30, 0x9a, 0xcf,
	0x8d, 0x19, 0xa6, 0x0b, 0x42, 0x23, 0xb3, 0xb8, 0xd3, 0x3e, 0x42, 0x57, 0xcc, 0xe4, 0x17, 0xd0,
	0x5e, 0x63, 0xaa, 0x48, 0xaa, 0x34, 0xea, 0x99, 0x59, 0x29, 0xbf, 0x84, 0xa7, 0xbb, 0xec, 0x4f,
	0x4a, 0x8b, 0xcf, 0xf2, 0x46, 0xfb, 0x0b, 0x83, 0x1f, 0xc8, 0xe6, 0x42, 0xfe, 0xc4, 0x71, 0x22,
	0x8c, 0xe3, 0xef, 0xbe, 0x13, 0x06, 0xd4, 0x67, 0x26, 0x5e, 0x26, 0x18, 0x33, 0x59, 0x81, 0x2e,
	0xc9, 0x37, 0x02, 0x58, 0xb4, 0xd9, 0x26, 0x8c, 0xe8, 0x8e, 0xb0, 0x1c, 0xfb, 0xcc, 0x2c, 0x5a,
	0x6d, 0x09, 0x6a, 0x09, 0xbc, 0xbc, 0xf6, 0x48, 0xec, 0x1d, 0x73, 0x5f, 0x43, 0x87, 0xf1, 0x85,
	0xc0, 0x8a, 0xae, 0x81, 0xfa, 0x1f, 0x86, 0x25, 0xea, 0x34, 0xf3, 0xa4, 0x0a, 0xfc, 0x06, 0x7a,
	0x56, 0xb1, 0x13, 0xec, 0xfd, 0xa0, 0x01, 0x7f, 0x2b, 0xc1, 0x60, 0x91, 0x9c, 0xb2, 0xe3, 0xf1,
	0x49, 0x95, 0x1d, 0x6d, 0xd5, 0x3a, 0xda, 0x3e, 0x14, 0x77, 0x23, 0x81, 0x5a, 0x12, 0x57, 0x6d,
	0xe9, 0x19, 0xb4, 0xed, 0x53, 0x69, 0xd5, 0xa5, 0x72, 0xa4, 0xec, 0x4e, 0x82, 0x61, 0x49, 0x59,
	0x6d, 0x2c, 0x67, 0x10, 0xf7, 0x16, 0x80, 0x7f, 0x76, 0x51, 0x12, 0x98, 0x47, 0xfb, 0xb3, 0x59,
	0xe3, 0x12, 0xde, 0x7f, 0xc3, 0x0d, 0x32, 0x3c, 0x11, 0xae, 0x0c, 0x4f, 0x7c, 0xb2, 0x45, 0xf1,
	0x6a, 0x78, 0x5d, 0x9f, 0x96, 0xf6, 0x1b, 0x86, 0x87, 0xd4, 0xea, 0x54, 0xaa, 0xa0, 0x35, 0x36,
	0x6b, 0x04, 0x46, 0x87, 0xc8, 0xdc, 0x4e, 0xa4, 0xae, 0xc7, 0x1e, 0xc2, 0x1d, 0xc0, 0x73, 0xe1,
	0x10, 0x3f, 0x11, 0xf4, 0x7e, 0xee, 0x11, 0x1f, 0x4d, 0xbf, 0xfe, 0xfb, 0xe2, 0x52, 0xe6, 0x25,
	0x96, 0x61, 0x07, 0xdb, 0xb1, 0x88, 0x40, 0xcf, 0x32, 0x18, 0xef, 0x33, 0xd0, 0x8b, 0x10, 0xc6,
	0xbc, 0xb0, 0x75, 0x17, 0x7d, 0xdd, 0x0d, 0xac, 0x0e, 0x6f, 0x3f, 0xdf, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xb9, 0x19, 0xcf, 0x3a, 0xf4, 0x04, 0x00, 0x00,
}
